amundsen-io/amundsen

docs/developer_guide.md
Cut some time and things to handle in your head/keystrokes away:
* Little need to limit the build to single containers. Due to docker caching additional build time is negligible. 
* No need to `stop` as part of compose relaunch, `up` will detect changed containers and only relaunch as needed
* Also, indent code snippets in the numbered steps
yep!
=> Local docker dev speedup and simplification

amundsen-kube-helm/templates/helm/amundsen/Chart.yaml, amundsen-kube-helm/templates/helm/amundsen/templates/deployment.yaml, amundsen-kube-helm/templates/helm/amundsen/values.yaml, amundsen-kube-helm/templates/helm/elasticsearch/templates/deployment.yaml, amundsen-kube-helm/templates/helm/elasticsearch/values.yaml, amundsen-kube-helm/templates/helm/neo4j/templates/deployment.yaml, amundsen-kube-helm/templates/helm/neo4j/values.yaml
I have added resources, tolerations, node selectors, and affinities to the helm charts. We need these to deploy to our kubernetes cluster. I also added some default value files to charts.
=> Adding resources, tolerations, node selectors, and affinities to the helm charts

amundsen-kube-helm/README.md, amundsen-kube-helm/templates/helm/amundsen/values.yaml, amundsen-kube-helm/templates/helm/elasticsearch/templates/deployment.yaml, amundsen-kube-helm/templates/helm/elasticsearch/values.yaml, amundsen-kube-helm/templates/helm/neo4j/templates/configmap.yaml, amundsen-kube-helm/templates/helm/neo4j/values.yaml
This updates the helm templates & docs to make deployments work better out-of-the box for first-time users.
1. Uses latest amundsen versions to fix issues saving tags/descriptions
2. Increases the `vm.max_map_count` from an initContainer so that ES doesn't exit on startup
- This approach is similar to that used by the official Helm chart
3. Makes Neo4j memory settings (heap & page cache) configurable, and recommends smaller values for test setups
These are the steps I needed to get Amundsen running on a fresh 3-node EKS cluster with m5.large instances.
cc @jornh @javamonkey79
I documented how to configure Neo4j memory settings and added smaller example settings than the existing defaults.
=> Improve flexibility & user-friendliness of helm deployment

amundsen-kube-helm/templates/helm/neo4j/templates/deployment.yaml, amundsen-kube-helm/templates/helm/neo4j/templates/pvc.yaml
* In order to allow other pods to access neo4j disk, we need to setup a pvc and point neo4j at it
* No doc changes
=> setting up a pvc to allow for neo4j backups

.gitignore, docker-amundsen-local.yml, docs/developer_guide.md
I would like to persist the elasticsearch and neo4j data locally when developing using docker-amundsen-local
This is mainly so `docker-compose -f docker-amundsen-local.yml down` becomes safe to run without destroying local data
I updated the developer guide to include a note to remove the neo4j / elasticsearch files in order to clean up their states
=> Persist data locally when running docker-amundsen-local

docker-amundsen.yml
Addressing this:
https://github.com/lyft/amundsen/issues/247
Explicitly setting the ulimits in the docker-compose file fixes the above problem (`max file descriptors is too low`).
=> Add ulimits to elasticsearch.

amundsen-kube-helm/templates/helm/amundsen/templates/oidc_config.yaml, docs/authentication/oidc.md, docs/developer_guide.md
I modified one uri and added an additional uri that were required for my configuration (not sure if this is universal? if not I will just add them to readme)
Adding more info to the oidc_config.yaml readme. NOTE: I did not include information on how to build custom frontend at this time.
I added some information to the oidc README (is this the right place still?) for how to get specifically okta and amundsen integrated
=> adding 2 properties to oidc config 

README.md
In 
> Users could either load the data with [a python script](https://github.com/lyft/amundsendatabuilder/blob/master/example/scripts/sample_data_loader.py) with the library or with an [Airflow DAG](https://github.com/lyft/amundsendatabuilder/blob/master/example/dags/sample_dag.py) importing the library.
the link to the DAG example was broken, as the folder and file it pointed to no longer exist. I replaced the url with the new corresponding folder, but I didn't point to a specific file as there are now 3 different samples provided as example. So the link points to the folder: https://github.com/lyft/amundsendatabuilder/tree/master/example/dags
=> Repairing the link to sample DAG

README.md, mkdocs.yml
All the supported color could be found at https://www.materialui.co/colors . Felt the new one looks better, but ok to not change.
Also fix a badge link to be https
=> Fix a badge to be https and change color

amundsen-kube-helm/README.md, amundsen-kube-helm/templates/helm/values.yaml
The DBMS settings `23000m` cause Neo4j pod OOM, because it didn't a valid value for Neo4j.
It will be fix by change unit. e.g `2G`
=> Fixup Neo4j pod OOM by adjust DBMS config

docs/tutorials/user-profiles.md, mkdocs.yml
Add a brief tutorial on configuring "all things people" namely user profiles and authentication.
Based on part of a Slack thread https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1585925405270300?thread_ts=1585857717.224700&cid=CGFBVT23V
> Note I made and tested the links with `mkdocs serve` so they should work when published to the docs site. Not sure if there's a way to have it working fully across both that and locally/when browsed directly in the GitHub repo.?
=> User profiles tutorial

amundsen-kube-helm/README.md, amundsen-kube-helm/templates/helm/requirements.yaml
Currently when you run 
```bash
helm install amundsen amundsen-kube-helm/templates/helm
```
You get an error like this
```
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]
```
This was caused by elasticsearch's Helm Chart version `1.24.0`. Bumping it to the latest version, which is `1.32.0`, solved the issue.
Updated `amundsen-kube-helm/README.md` to reflect elasticsearch's version.
=> fix: Bump elasticsearch chart version from 1.24.0 to 1.32.4

amundsen-kube-helm/templates/helm/templates/deployment-search.yaml
Check this issue : #486
Issue
Following https://github.com/lyft/amundsen/tree/master/amundsen-kube-helm to install amundsen to kube using helm 3. Using the default values without providing the ES endpoint in the values.yaml, it search service uses {{ .Release.Namespace }}-elasticsearch-client.{{ .Release.Namespace }}.svc.cluster.local as the url to connect to ES. It gives error as it does not find this service. It should be Release.Name in the beginning of the url to connect
Summary of Changes
Replaced {{ .Release.Namespace }}-elasticsearch-client.{{ .Release.Namespace }}.svc.cluster.local with {{ .Release.Name }}-elasticsearch-client.{{ .Release.Namespace }}.svc.cluster.local
Documentation
NA
=> chore: Updated the deployment search file with Release.Name instead of Release.Namespace

docker-amundsen.yml
This PR includes two changes:
1. Adds persistent Docker volumes for Neo4J and Elasticsearch so data in both services is preserved across restarts.
1. Renames the default compose file from `docker-amundsen.yml` to `docker-compose.yml`. This simplifies the commands used to run the default docker compose setup, since compose will automatically use an available `docker-compose.yml` file.
I sequestered both changes into separate commits, so if it's preferred to keep `docker-amundsen.yml` over `docker-compose.yml` I can jettison the second commit and we can retain the mounted volume changes in this PR.
I've also tested this locally to make sure that changes persist 😄 
Updated all references to `docker-amundsen.yml` to `docker-compose.yml` and simplified commands where possible.
Make sure you …
=> other: Add persistent volumes for docker-compose images

amundsen-kube-helm/templates/helm/templates/configmap-neo4j.yaml, amundsen-kube-helm/templates/helm/templates/deployment-neo4j.yaml
Use [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) for Neo4j deployment plugin volumes instead of [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath).
With this change we get rid of the dependency on hostPath and thus the dependency on the hosts filesystem and pods permissions to the hostPath.
The custom Neo4j deployment can now also run on GKE (and other k8s clusters).
I also sorted the config options for for Neo4j and disabled auth. The disabling of Neo4j auth seems to be a consistent setting through this repo (docker examples, and ECS examples).
=> fix: Update helm Neo4j deployment

amundsen-kube-helm/templates/helm/templates/deployment-frontend.yaml, amundsen-kube-helm/templates/helm/values.yaml, docs/authentication/oidc.md
Updated helm chart to be compatible with @verdan's recent updates to flask-oidc.
Also bumped dockerimage tags to latest versions.
=> chore: Add compat with flask-oidc v0.1.x in amundsenfrontendlibrary

amundsen-kube-helm/templates/helm/templates/pvc-neo4j.yaml
I suggest that helm delete should persist neo4j pvc's. Those should be deleted manually afterward to prevent dataloss.
=> chore: Helm will keep persistent volume claims on delete

docs/roadmap.md
Updates our roadmap document to remove already done items
Updates planned features and focus (biased by Lyft's roadmap)
Updates the doc
=> docs: Updated Roadmap document

amundsen-kube-helm/README.md, amundsen-kube-helm/templates/helm/requirements.yaml
Update chart location, the old one stopped working, every time I do something like `helm dep update` it returns `failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden`
The old location was moved to https://charts.helm.sh/stable as explained here https://helm.sh/blog/new-location-stable-incubator-charts/
=> fix: update chart location

docs/installation.md
After Docker-compose run, when ES was called the first time, the container crashed with Docker error 137 Out Of Memory. Add a troubleshooting guide on how to add memory to the Docker engine.
This PR is for documentation.
=> docs: Add Troubleshooting Information for Docker error 137

amundsen-kube-helm/templates/helm/templates/deployment-search.yaml, amundsen-kube-helm/templates/helm/values.yaml
Adds the ability to specify a user and password for elasticsearch when you bring your own cluster. I added this because I am using a hosted elasticsearch on AWS and I need to set my user and password to the empty string (`''`).
Added some description in the values.yaml file.
=> fix:Expose elastic search credentials in helm deploy

amundsen-kube-helm/templates/helm/templates/pv-neo4j.yaml, amundsen-kube-helm/templates/helm/templates/pvc-neo4j.yaml
I am using an EFS from AWS on EKS for the neo4j deployment and the volume claim fails to bind to the volume because the storage-class is not specified in the pv-neo4j.yaml template. Adding it in fixed the issue for me.
I also added a reference to the volumeName in pvc-neo4j.yaml. I believe this will make sure that the volume claim uses the neo4j volume that is being created with this helm deployment. 
No documentation
=> fix: Specify storageClassName for neo4j persistent volume

amundsen-kube-helm/templates/helm/values.yaml
Signed-off-by: benrifkind <ben.rifkind@gmail.com>
The neo4j.serviceType is not documented in values.yaml so I added it. Here's where it is used: https://github.com/amundsen-io/amundsen/blob/master/amundsen-kube-helm/templates/helm/templates/service-neo4j.yaml#L18. I think it defaults to ClusterIP if not set but nice to have it documented.
=> docs:neo4j.serviceType is not documented

docs/tutorials/badges.md
**Summary of Changes**
Added examples of how to use API for column badge
**Documentation**
Relevant to: amundsen-io/amundsenmetadatalibrary#273
=> Column Badge Documentation 

docker-amundsen-atlas.yml
Update proxy settings for atlas in docker-compose, I removed http:// from the host and added an environment variable that disables encrypted traffic ([as suggested](https://github.com/amundsen-io/amundsen/issues/590#issuecomment-667322796) by @verdan).
Current settings are contacting non-existent URL, fix will ensure that the docker-compose for Atlas works again.
=> fix: Update proxy settings for atlas in docker-compose

docs_overrides/main.html, mkdocs.yml
This PR fixes the "Edit this page" for symbolic links (submodules and linked readme files) by overriding part of the template. The solution is slightly ad-hoc (hardcoded replacements), however resolves the issue. This could be improved by writing a [custom filter](https://jinja.palletsprojects.com/en/2.11.x/api/#writing-filters) that dynamically finds symbolic links.
https://www.amundsen.io/amundsen/metadata/docs/proxy/atlas_proxy/
=> docs: fixes the "Edit this page" for symbolic links

docs_overrides/main.html
Fixes CI in https://github.com/amundsen-io/amundsen/runs/2366741094. 
Docs update in #989 was designed for the latest version of mkdocs-material (7.1.1), while amundsen uses 4.6.3.
This PR uses the code specific to the 4.6.3 version.
=> fix: override content block in docs for `mkdocs-material==4.6.3`

.github/workflows/metadata_pull_request.yml
`working-directory` isn't valid for non-shell actions, so this was a copy-paste error
=> ci: fix metadata ci config

databuilder/README.md, databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_owner_extractor.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_owner_extractor.py
Update ModeDashboardOwnerExtractor to use Mode discovery api. Metadata can be extracted in one api endpoint call instead of using 3 endpoints (it used to be one for spaces, one for reports, and one for creator email)
Test added.
ModeDashboardOwnerExtractor config example in README
=> perf: Update ModeDashboardOwner extractor to use Mode discovery api

databuilder/README.md, databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_executions_extractor.py
Temporarily fix potential 404 in mode dashboard executions extractor. Reached an agreement with Mode team that they will include last_execution_timestamp in reports discovery api. Once Mode team finishes it, we can switch to reports discovery api in this extractor
update mode dashboard executions extractor config in README
=> fix: Temporarily fix potential 404 in mode dashboard executions extractor

databuilder/databuilder/rest_api/rest_api_query.py
Potential bugs in rest api query:
The yield `record_dict` for example `{'product': 'mode'}` may be transformed in an extractor to a dict like `{'product': 'mode', 'new_field': 'new_field'}`. When the next yield record is extracted, it still should be `{'product': 'mode'}` instead of `{'product': 'mode', 'new_field': 'new_field'}` since two records should be unrelevant.
See this extractor as an example that changes record_dict https://github.com/amundsen-io/amundsen/blob/1cece5b4461c8623414ccfb635e495e794a55988/databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_queries_extractor.py#L74
This is not causing a problem on our end right now. It is a proactive change to avoid possible problems. 
- In …
=> fix: fix bug in rest_api_query

databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_utils.py, databuilder/databuilder/rest_api/query_merger.py, databuilder/databuilder/rest_api/rest_api_query.py, databuilder/tests/unit/rest_api/test_query_merger.py
Adding this functionality in support of moving Move Dashboard Extractors to discovery API.
Based on discovery api documents, [space discovery api ](https://mode.com/developer/discovery-api/analytics/spaces/)has dashboard_group_id, dashboard_group_name, and dashboard_group_description, while [report discovery api](https://mode.com/developer/discovery-api/analytics/reports/) has dashboard_id, dashboard_name, dashboard_group_id, and dashboard_description etc.  If we want to extract DashboardMetadata that has all these information in one record, we have to join them based on dashboard_group_id. The purpose of this PR is to address this.
There are some other use cases that we need to merge results as well, for example, total_views_count that lives in [report stats discovery …
=> feat: Add merge query results functionality to rest_api_query

.github/boring-cyborg.yml
Proposes to use https://probot.github.io/apps/boring-cyborg/ as an automatic PR labeler.
After migrating to monorepo we could benefit from this to have better traceability of PRs that are filed.
n/a
n/a
=> Automatic PR labeling

frontend/amundsen_application/static/js/pages/TableDetailPage/TableHeaderBullets/index.tsx
Signed-off-by: Grant Seward <grant@stemma.ai>
Previously, when selecting the database from the table details page the value placed into the `source` field was an object, not a string. This PR updates the value being passed to be the actual value of the database.
Previous:
Current:
This is inline with how other filters are being passed, for example, dashboard and table tags: https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/static/js/components/Tags/TagInfo/index.tsx#L63
N/A
=> fix: Database filter to return string, not object

README.md
I'm not sure when or how these were broken, but the URLs are cleaner now
=> docs: fix some broken links

databuilder/databuilder/rest_api/mode_analytics/mode_paginated_rest_api_query.py
For the Mode main API, it is 30 per page. For the discovery, by default, it is 1000 records per page.
=> chore: update ModePaginatedRestApiQuery default parameters

databuilder/databuilder/extractor/base_bigquery_extractor.py, databuilder/databuilder/extractor/bigquery_usage_extractor.py, databuilder/databuilder/extractor/bigquery_watermark_extractor.py, databuilder/tests/unit/extractor/test_bigquery_usage_extractor.py, databuilder/tests/unit/extractor/test_bigquery_watermark_extractor.py
Changes made according to the issues: #1070 & #1071
Additional changes made not mentioned in the issue: 
- Skip usage counts for wildcard tables: When there is a query like `select * from project:dataset:tableprefix*`, the `'referenced tables'` in the logging response contains the tableId as tableprefix* resulting in a FK constraint violation between table_usage and table_metadata tables.
Added unit tests for the new configs in bigquery_usage_extractor and bigquery_watermark_extractor. 
N/A
- All the public functions and the classes in the PR contain …
=> Fix: Make BigQuery extractors support Relational Metadata store

databuilder/README.md, databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_extractor.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_extractor.py
Provide a config in ModeDashboardExtractor that we can skip some spaces we don't want to index.
Added test for this functionality
Described it in the comment and also updated the README
=> feat: support skipping configured Mode spaces

databuilder/databuilder/publisher/neptune_csv_publisher.py
fix typo aws_secret_access_key in neptune csv publisher
=> fix: typo aws_secret_access_key in neptune csv publisher

common/amundsen_common/utils/__init__.py, common/amundsen_common/utils/atlas_utils.py, common/tests/unit/utils/test_atlas_utils.py, frontend/amundsen_application/api/utils/metadata_utils.py, frontend/setup.cfg, frontend/tests/unit/utils/test_metadata_utils.py, metadata/metadata_service/proxy/atlas_proxy.py, metadata/requirements.txt, metadata/setup.cfg, metadata/tests/unit/proxy/fixtures/atlas_test_data.py, metadata/tests/unit/proxy/test_atlas_proxy.py
Introduces support for lineage retrieval in Atlas Proxy.
- added tests for get_lineage
- added tests for atlas_utils.py
- documented new methods in atlas proxy
=> feat: Atlas Lineage support

search/setup.cfg
In Search service `setup.cfg` section changed from `[pytest]` to `[tool:pytest]`. Linked to issue #1143 
No tests modified. Install latest `pytest` and run.
N/A
=> fix: pytest setup.cfg section fix

frontend/amundsen_application/api/metadata/v0.py, frontend/amundsen_application/api/utils/metadata_utils.py, frontend/tests/unit/api/metadata/test_v0.py
=> feat: FE ML Feature get_feature_metadata

common/amundsen_common/models/table.py, common/setup.py
This change introduces the common models that will be used by the frontend and metadata services per the [rfc](https://github.com/amundsen-io/rfcs/pull/37) to index query compositions.
Two new models are introduced:
- SqlJoin
- SqlWhere
In addition, the `TableSummary` was moved higher up in the file to enable it to be reused. 
N/A - changes are limited to making schema models
=> feat: Common query models

metadata/metadata_service/__init__.py, metadata/metadata_service/config.py
Adds a new metadata configuration to initialize custom extensions and routes in the metadata package. This is same as this in frontend: https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/config.py#L65
=> feat: Configuration option to init custom routes

metadata/setup.py
https://github.com/amundsen-io/amundsen/issues/1157
fix: 1157 issue - metadata sql alchemy for iodc component
=> fix: 1157 issue - metadata sql alchemy for iodc component

amundsen-kube-helm/templates/helm/values.yaml
It addresses the issue #1069, that with current versions of search and frontend service, the tag search update doesn't work correctly. On our current setup I run this set of versions together and it works fine between with each other, including that the issue #1069 is fixed.
1. Add tag manually in frontend
2. Search for this tag using advanced search
N/A
=> fix: Helm service versions moved up to latest ones

README.md
Just a quick driveby to fix a few doc links that still point to old locations.
None needed - docs only.
README.MD
=> docs: Fix doc links in README.md

search/README.md
docs: add information about default ES indexes to search Readme
=> Docs: add information about default ES indexes to search Readme

frontend/amundsen_application/config.py, frontend/amundsen_application/proxy/issue_tracker_clients/jira_client.py, frontend/docs/flask_config.md, frontend/requirements.txt
Re:  #1206 
Implements issue creation on Jira cloud instances addressing two problems:
- issue type id on Jira cloud is not fixed to 1, allow customization (invalid issue type causes rejection by the api)
- reporter needs to be adjusted from `{'name': 'name of user'}` to `{'accountId': 'atlassian account id'}`
Introduced a new setting allowing to override issue type ID.
Used the jira client library deployment type detection to branch out on reporter payload.
Bumped jira library version to 3.x tree. (only breaking change was 2.7 support removal)
N/A - internal to jira_client
Listed the ability to override Jira cloud issue type id's in the relevant documentation section. 
- In case you are adding a dependency, check …
=> fix: Allow support for Jira cloud (preserves backward compatibility)

databuilder/databuilder/models/schema/schema_constant.py, databuilder/tests/unit/models/schema/test_schema.py
We at Brex have databases named with numbers and underscores in it. There were exceptions when we tried to use Badges, as Badges checked key format https://github.com/amundsen-io/amundsen/blob/54f5ed6bb4dbcb0ed59182e485bd109374d549a9/databuilder/databuilder/models/badge.py#L52-#L67
Gladly, those checks haven been removed recently https://github.com/amundsen-io/amundsen/commit/aa67a0c14d191501b23ea488f1a4b9d4bbe20230#diff-1eb09b5d29f66bcea3cd4a4a23befe3c93d8e577a33de1e9d903f3fb9c1faffdL52
This PR is to change another place that checks a key should match a pattern.
Added unit tests …
=> fix: Fix db key constraints

common/amundsen_common/models/index_map.py, common/setup.py
This change fixes the discrepancy between the user ES index located in [common](https://github.com/amundsen-io/amundsen/blob/main/common/amundsen_common/models/index_map.py#L230) vs [databuilder](https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/publisher/elasticsearch_constants.py#L224). The discrepancy is in one field: `full_name` vs `name`.
This is being done in preparation for deleting the `elasticsearch_constants.py` databuilder file and importing these mappings from common instead. 
The same cleanup was performed [here](https://github.com/amundsen-io/amundsendatabuilder/pull/385) but had to be [reverted](https://github.com/amundsen-io/amundsendatabuilder/pull/389) because of some marshmallow thing that's …
=> fix: bw-incompatible update to user elasticsearch index

databuilder/setup.py
Forgot to bump version here: https://github.com/amundsen-io/amundsen/pull/1235
Proposing a major bump given the bw-incompatibility in above PR.
=> fix: bump databuilder version

databuilder/databuilder/models/badge.py, databuilder/tests/unit/models/test_badge.py
Change badge name and category to lower case so badges are searchable.
Amundsen UI by default formats badge display with first letter capitalized while other letters are lowercase.
https://github.com/amundsen-io/amundsen/blob/6ec9b398634264e52089bb9e1b7d76a6fb6a35a4/frontend/amundsen_application/static/js/config/config-utils.ts#L128
Clicking table badges in UI always results in searching lower cases badges.
https://github.com/amundsen-io/amundsen/blob/6ec9b398634264e52089bb9e1b7d76a6fb6a35a4/frontend/amundsen_application/static/js/components/BadgeList/index.tsx#L56
If badges stored in neo4j are not lowercase, they won't be searchable in UI.
Add a unit test 
- In case you are adding a dependency, check if the license …
=> fix: change badge name and category to lower case

common/amundsen_common/models/table.py, metadata/metadata_service/proxy/neo4j_proxy.py, metadata/tests/unit/proxy/test_neo4j_proxy.py
Adds query components that are associated to a table to the metadata table details API for neo4j as part of [RFC 37](https://github.com/amundsen-io/rfcs/blob/master/rfcs/037-index-query-composition.md). This does not need to be added to the other proxies because `common_join` and `common_filter` attributes on the common `Table` model are optional.
Also fixed spelling in `QueryWhere`
Existing tests updated to include new response attributes.
n/a
=> feat: Query components metadata

common/Makefile, common/requirements-common.txt, common/setup.py, frontend/setup.py, metadata/setup.py, requirements-common.txt, search/setup.py
This formally ends [The Great Unpinning](https://github.com/amundsen-io/amundsen/pull/1264). In effect, I realized it does not solve the problem of `amundsen-common` as it still results in this simple library requiring many unrelated dependencies. Additionally, the loss of reproducible builds introduced by unpinned service dependencies is possibly not worth the benefit.
Instead, I propose to keep amundsen-common separate with its small requirements set. Why is this okay? Because, when `amundsen-common` is used inside databuilder/frontend/metadata/search, the `install_requires` of `amundsen-common` will be completely irrelevant. In other words, the pain of desynchronized dependencies will not return and the benefits of @mgorsk1's …
=> refactor: undo the great unpinning

databuilder/README.md
databuilder will only work with elasticsearch version 6.x. I tried using es 7.10 and it threw an error because es 7 removes mapping types (https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html) and amundsen uses these in the index declaration templates (ex: https://github.com/amundsen-io/amundsen/blob/main/common/amundsen_common/models/index_map.py\#L13-L114). This commit adds a single line to the databuilder README that says the elasticsearch requirements. This line is already in the search_service README so it makes sense to have in the databuilder README as well.
=> docs: databuilder/README: add es version

frontend/amundsen_application/static/js/components/Lineage/Graph/chart.spec.ts, frontend/amundsen_application/static/js/components/Lineage/Graph/chart.ts, frontend/amundsen_application/static/js/components/Lineage/Graph/types.ts, frontend/amundsen_application/static/js/components/Lineage/GraphContainer/index.spec.tsx, frontend/amundsen_application/static/js/fixtures/globalState.ts
The current rendering relies on two graphs emerging from a single root.
This PR adds the ability to reflow the direction of relationships described in the upstream_entities response to support this.
Examples below:
<details>
<summary>Example 1</summary>
```javascript
{
"downstream_entities": [
{
"badges": [],
"cluster": "demo",
"database": "hive_table",
"key": "hive_table://demo.sri_lanka/murphy_taylor_and_rivera",
"level": 2,
"name": "murphy_taylor_and_rivera",
"parent": "hive_table://demo.sri_lanka/howard_harrington_and_mendoza",
"schema": "sri_lanka",
"source": "hive_table",
"usage": 0
},
{
"badges": [],
"cluster": "demo",
"database": "hive_table",
"key": "hive_table://demo.sri_lanka/howard_harrington_and_mendoza",
"level": 1,
"name": "howard_harrington_and_mendoza",
"parent": …
```
=> fix: Table Lineage - Upstream rendering adjustments

frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/docs/application_config.md
Added wildcard functionality to notices (ie if we wanted to add a notice to every table in the shadow schema, could do that with ..shadow.*) and dynamic HTML messages (ie if we wanted to have each of those notices have a different message depending on which table it was)
Added notices tests to test the functionality of the wildcard and the dynamic message.
Added documentation in frontend/docs/application_config.md
=> feat: Making notices more general (real)

databuilder/databuilder/extractor/bigquery_usage_extractor.py, databuilder/tests/unit/extractor/test_bigquery_usage_extractor.py
Following the discussion on slack [here](https://amundsenworkspace.slack.com/archives/C01857S0V1V/p1625767472165900)
* keeps default behavior of ignoring counts from different project_id
* Add configuration key to allow ingestion of counts from different project_id 
Add a unit test case to enable the configuration variable and validate that `bigquery_usage_extractor` consume the reads that are outside of the defined project_id
=> feat: Allow counting reads from different GCP project id as config in bigquery_usage_extactor

databuilder/example/sample_data/sample_col.csv, databuilder/example/sample_data/sample_table.csv, frontend/amundsen_application/static/js/features/ColumnList/ColumnType/parser.spec.ts, frontend/amundsen_application/static/js/features/ColumnList/ColumnType/parser.ts
feat: add complex delta type rendering on frontend
This PR adds support to render complex delta types as nested columns on the UI. This is modeled after the implementation already done for `hive` and `presto` types.
The change here is fairly simple in that it just adds a new `DatabaseId` to the `parser.ts` enum in order to render nested fields nicely on the UI. I also linked the docs for Delta Types above the `SUPPORTED_TYPES` const similar to `hive` and `presto`.
I added tests to `parser.spec.ts` to specifically test for delta complex types and make sure they are turn into the proper column rendering.
I also added some sample delta tables to `sample_data/sample_table.csv ` and sample columns to `sample_data/sample_col.csv` with some nested fields and ran the application locally to verify …
=> feat: add complex delta type rendering on frontend

amundsen-kube-helm/templates/helm/values.yaml
A new frontend build was released: https://hub.docker.com/layers/amundsendev/amundsen-frontend/3.11.1/images/sha256-5211d896cf9ebdc07288cb91008cf4ffa1df1d417d3fa5b1c6e13b883a09be36?context=explore. Bump the helm chart frontend image tag.
N/A
Linked the dockerhub image tag in the commit description
=> chore: bump frontend image in helm chart

databuilder/README.md, databuilder/databuilder/extractor/delta_lake_metadata_extractor.py, databuilder/tests/unit/extractor/test_deltalake_extractor.py
This change implements proper extraction of complex & nested types for delta tables in the delta_metadata_extractor. This commit was slightly modeled off of the bigquery_metadata_extractor which supports nested columns (https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/extractor/bigquery_metadata_extractor.py). However, this implementation is slightly more complex because delta allows support for arrays and maps whose elements, keys, and values can also be nested types.
This PR also includes a new test suite to test delta tables with these complex types and make sure the parsing works properly.
I also added this behind a configuration value. Since users of amundsen might be using the delta extractor as is, it could be jarring that one day they have X number more …
=> feat: support complex & nested column extraction for delta

common/amundsen_common/models/api/health_check.py, common/setup.py
Signed-off-by: Grant Seward <grant@stemma.ai>
This content for PR is also contained in https://github.com/amundsen-io/amundsen/pull/1355 but is being submitted separately since the updated common version is required to be on pypi as a pre-requisite before the other PR tests can run.
Added a health check model that will be used by the frontend, metadata and search service. Allows for multiple, arbitrary checks to be run by each of the services.
A health check has a status (e.g. `ok` or `fail`). The HTTP status code returned to the client is determined from the status of the health check (e.g. ok=200, fail=503) and any type of checks that the underlying service/proxy decides. Checks may look like:
```json
{
"status": "ok",
"checks": {
"Neo4jProxy:connection": {
"overview_enabled": false
}
} …
```
=> feat: Common models to support better health checks

databuilder/databuilder/extractor/base_postgres_metadata_extractor.py, databuilder/databuilder/extractor/postgres_metadata_extractor.py, databuilder/example/scripts/sample_postgres_loader.py, databuilder/tests/unit/extractor/test_postgres_metadata_extractor.py
In PostgreSQL information_schema is limited to only tables you have access to. However, the pg_catalog tables are not.
This means that if we want to do a metadata-only integration via a User that has read access to zero tables, at present they'd have to do a materialized view of information_schema. 
This PR makes use of pg_catalog instead properly, to make sure the data is ingested for all users, even with no access. 
- All the public functions and the classes in the PR contain docstrings that explain what …
=> refactor: Updates Postgres extractor to not use information_schema

databuilder/databuilder/models/query/base.py, databuilder/databuilder/models/query/query.py, databuilder/databuilder/models/query/query_where.py, databuilder/tests/unit/models/query/test_base.py, databuilder/tests/unit/models/query/test_query.py, databuilder/tests/unit/models/query/test_query_execution.py, databuilder/tests/unit/models/query/test_query_join.py, databuilder/tests/unit/models/query/test_query_where.py
Currently key generation transforms a query into a key by making it
lowercase, removing all whitespace, and removing all ';' characters.
This fix:
- performs no transformations of the query inside of quoted regions (', ", `)
- collapses runs of whitespace characters to a single ' '
- only removes ';' from the end of the query
This ensures that the queries such as `select 'X; Y; Z'` and
`select 'xyz'` receive different keys.
While this does mean that a query will now most likely now be assigned a
different key than before, this is likely preferable to the current situation.
Existing tests have been updated with the new keys and hashes as appropriate, and additional tests have been added which document and verify the new behavior and will help to prevent regressions. 
The docstrings provide …
=> fix: key generation in databuilder query models.

amundsen-kube-helm/templates/helm/templates/deployment-frontend.yaml, amundsen-kube-helm/templates/helm/values.yaml, frontend/amundsen_application/api/utils/metadata_utils.py, frontend/amundsen_application/config.py, frontend/docs/flask_config.md, frontend/tests/unit/utils/test_metadata_utils.py
This commit adds a new configuration value for the concept of uneditable schemas. The two options right now UNEDITABLE_SCHEMAS and UNEDITABLE_TABLE_DESCRIPTION_MATCH_RULES are not conducive to folks who are deploying amundsen from the docker containers in dockerhub. Here we add a new configuration value ALL_UNEDITABLE_SCHEMAS that pulls it's value from an environment variable andand is a blanket on/off switch to allow schema editing on the UI.
Within my organization, we want don't want users updating anything on the UI. We want to handle all of the metadata during ETL and not allow users to mess with it. I suspect other people using amundsen will want to do the same.
I added some comments in the code about these config values and also updated the documentation for Uneditable Table …
=> feat: blanket uneditable schema option

databuilder/README.md, databuilder/databuilder/extractor/salesforce_extractor.py, databuilder/setup.py, databuilder/tests/unit/extractor/test_salesforce_extractor.py
This is an implementation of https://github.com/amundsen-io/amundsen/issues/1352. It adds a SalesForceExtractor which pulls metadata about SalesForce objects into a `TableMetadata` object.
tests/unit/extractor/test_salesforce_extractor.py
Added to the README
=> feat: Add Salesforce extractor

metadata/metadata_service/proxy/mysql_proxy.py
Context: `description_source` is missing when inserting a new table/column description in mysql_proxy.py
slack link: https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1626999566426200
Change: Add description_source 'description' for upserting table/column description in put_table/column_description() of mysql_proxy.py
N/A
N/A
=> fix: add description_source when inserting table/column description in mysql_proxy

databuilder/databuilder/extractor/delta_lake_metadata_extractor.py, databuilder/tests/unit/extractor/test_deltalake_extractor.py
This commit fixes/refactors the implementation of complex delta columns. There was an edge case not taken into account for arrays of arrays (`array<array<string>>`), maps of maps (`map<int,map<int,int>>`), and combinations where intermediate nested types were not struct fields. This also prompted a slight re-write of the function where the base case of the recursion is StructField. Basically we only want to add columns that are StructField types since they are named and can be accessed.
I added three new test cases for these cases and made sure all previous test cases still passed.
N/A --> already documented
=> fix: nested delta edge case

frontend/amundsen_application/api/metadata/v0.py, frontend/setup.py, frontend/tests/unit/api/metadata/test_v0.py, search/search_service/proxy/elasticsearch.py, search/setup.py, search/tests/unit/proxy/test_elasticsearch.py
This PR changes the method that updates tags with the search service after a user adds/deletes them in the UI. The method is made more generic to work with other entity types (ML Features, specifically). 
I also simplified this slightly by removing the validation in the search service which disallowed the `:` and `/` characters. These characters simply needed to be escaped. This validation was added here: https://github.com/amundsen-io/amundsensearchlibrary/pull/100. After this validation was removed, we can filter more simply by `key`.
I have also changed the `request_search` call from passing `json` to passing `data`. The `data` arg is what all other API calls from frontend use. The `json` arg is a bit of syntactic sugar which saves …
=> feat: Update feature tags in search on user action

docs/installation.md
Changed git clone command to use HTTPS instead of SSH, so that Windows users can follow along with the documentation. This alternative command will also work the same for Mac and Linux users.
No new tests are needed. 
Changed git clone command to use HTTPS instead of SSH, so that Windows users can follow along with the documentation. This alternative command will also work the same for Mac and Linux users.
=> docs: Use HTTPS Git clone command instead of SSH in installation documentation

amundsen-kube-helm/templates/helm/templates/deployment-frontend.yaml
This commit fixes the deployment-frontend.yaml from a slightly bad change that was introduced in #1353. Namely:
- The logic to render the env var for `ALL_UNEDITABLE_SCHEMAS` was improperly nested in the OIDC config so if you wanted to use it but didn't populate OIDC config then the logic would not work
- Use the quote function to properly make an environment variable.
Unforuntely there are no integration tests to make sure the helm chart compiles for different sets of values. I was only able to expose this issue when I tried to deploy #1353 in my production build. It would be nice to have that though? Maybe helm has something? Unsure at the moment.
N/A
- In case you are adding a dependency, check if the license …
=> fix: deployment-frontend env nested & quote issue

databuilder/databuilder/publisher/neptune_csv_publisher.py, docs/tutorials/how-to-use-amundsen-with-aws-neptune.md
As described in the issue #1338, we could use STS regional endpoint instead global one, since AWS recommends it.
I added an optional parameter to the NeptunePublisher  which does not have unit tests
I changed the Neptune tutorial adding the new parameter
=> feat: Adding regional endpoint url for NeptunePublisher

databuilder/databuilder/extractor/delta_lake_metadata_extractor.py, databuilder/tests/unit/extractor/test_deltalake_extractor.py
For the deltalake metadata extractor, when fetching columns the code `describe`s the table, and then tries to look at schema by doing `spark.table('<table>').schema`; this is wrapped in a try-catch to fail gracefully.
We ran into an issue recently where running `spark.table('<table>').schema` raised an exception, causing this method to drop into the except and log the error and return `raw_columns`. However, the type of `raw_columns` is not `List[ScrapedColumnMetadata]`, it's a list of spark Row objects, e.g.
```
[Row(col_name='date', data_type='date', comment=''),
Row(col_name='hour_start', data_type='timestamp', comment=None),
...
```
which caused the eventual user of the result (`create_table_metadata`) to encounter an exception because the metadata was not the type it was expecting. …
=> fix: return empty list from exceptions in fetch_columns on deltalake extractor

.github/workflows/databuilder_pull_request.yml, .github/workflows/frontend_pull_request.yml, .github/workflows/metadata_pull_request.yml, .github/workflows/search_pull_request.yml
Adds `common/**` to pull request paths in github workflows for databuilder, frontend, metadata and search so that any changes to common will also trigger tests for these services. This should help catch changes to common that will break any services that were not updated within the same PR.
No tests were changed since this PR was for CI changes.
N/A
=> test: Trigger ci on all services for changes to common

databuilder/setup.py
Bumps the databuilder version.
N/A
N/A
- [N/A] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [N/A] In case of new functionality, my PR adds documentation that describes how to use it.
=> chore: bump databuilder version to 5.2.5

databuilder/setup.py
Signed-off-by: Parth Upadhyay <parth.upadhyay@gmail.com>
Bumps databuilder to 5.2.6 to try again to release.
N/A
N/A
- [N/A] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [N/A] In case of new functionality, my PR adds documentation that describes how to use it.
=> chore: bump databuilder version to 5.2.6

databuilder/databuilder/publisher/elasticsearch_publisher.py, databuilder/requirements.txt, databuilder/tests/unit/publisher/test_elasticsearch_publisher.py, docker-amundsen-local.yml, docker-amundsen.yml, search/requirements.txt, search/search_service/config.py, search/search_service/proxy/elasticsearch.py, search/tests/unit/proxy/test_elasticsearch.py
=> chore: Upgrades ES to 7.13.3

search/tests/unit/proxy/test_elasticsearch.py
Test case for elastic healthcheck is in a failing state on the main branch.
Use mocks to circumvent the incompatibility.
N/A
N/A
=> fix: Adjust elastic healthcheck test case to prevent mypy failing.

frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts
Update notices pattern matching to be more general so that `*.*.*.event_*` would put a notice on all tables that had a table name starting with event_ (for example). Right now, pattern matching on notices are only implemented so that you can match whole clusters, datasources, schemas, or tables, not part of tables.  One use case for this would be adding notices to all event tables in the case of a SEV.
Added relevant test cases to existing tests for notices
=> feat: more general notices

databuilder/databuilder/extractor/delta_lake_metadata_extractor.py
PR #1329 added a call to the schema property of the Dataframe.  For certain tables (a presto view in our case) Spark can throw a `ParseException`.  This change adds `ParseException` in the try block, and returns an empty list.
N/A
N/A
- [N/A] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [N/A] In case of new functionality, my PR adds documentation that describes how to use it.
=> fix: Handle ParseException when reading schema property

databuilder/example/dags/postgres_sample_dag.py
Changed the name of a column in a SQL snippet which was throwing errors when running the postgresql extractor dag. Previously there was an erroneous 'where' and a column name was incorrectly referenced, so the DAG would not run successfully. I removed the 'where' and replaced the undefined column name with the one that is defined.
No tests were modified or added, however this was tested manually by extracting from a PostgreSQL db. No tests were added since a database instance, and Apache Airflow is required to run the code. The change was tested locally and it made the Airflow DAG run sucessfully.
No documentation added.
- [x ] PR title addresses the issue accurately and concisely. Example: "Updates the version of …
=> fix: Fixed postgresql extractor airflow DAG

amundsen-kube-helm/README.md, amundsen-kube-helm/templates/helm/Chart.yaml, amundsen-kube-helm/templates/helm/templates/configmaps.yaml, amundsen-kube-helm/templates/helm/values.yaml
`cluster.local` was hardcoded in the ConfigMap which breaks the setup where the Kubernetes Cluster Domain is not the default. And, most of the production clusters running with custom domain names. It's good to have a variable to set the Cluster Domain. 
- Deployed helm chart in Kubernetes cluster with different cluster domains
- Deployment completed 
- None of the apps were working as all apps were using services DNS with cluster.local as it was hardcoded in the ConfigMap
- Added `clusterDomain` variable and updated README.md
- All the public functions …
=> fix: Removing hardcoded K8s Cluster Domain

databuilder/databuilder/models/application.py, databuilder/setup.py
In #1398 we generalized the Application model to be any application not just airflow. In that PR, I removed a arguement to the init for the model. This broke the sample data loader but it could also break peoples workflows who are already using Application model.
This commit brings the argument back.
N/A
N/A
=> fix: Application model backwards compatibility

databuilder/example/scripts/sample_postgres_loader.py
fix https://github.com/amundsen-io/amundsen/issues/1465
Add entity type to elastic search job
No tests needed for example
=> fix: Postgres extractor example

databuilder/README.md, databuilder/databuilder/task/neo4j_staleness_removal_task.py, databuilder/tests/unit/task/test_neo4j_staleness_removal_task.py
Currently, the neo4j staleness removal task can only remove stale nodes and/or relations based on specified types. This new functionality allows users to specify a condition along with the type. To do this, you can specify the inputs to be a list of `TargetWithCondition` objects that each define a target type and a condition. Only stale nodes or relations of that type and that meet the condition will be removed when using this type of input.
For example, you could add a condition that you only want to remove stale nodes of type Table that have some kind of relation to a node of type Column, rather than deleting all stale Table nodes.
This change is backwards compatible so users may continue to only specify the type without conditions for …
=> feat: Adding ability to include conditions along with node and relation types in the neo4j staleness removal task

frontend/amundsen_application/api/issue/issue.py, frontend/amundsen_application/base/base_issue_tracker_client.py, frontend/amundsen_application/proxy/issue_tracker_clients/asana_client.py, frontend/amundsen_application/proxy/issue_tracker_clients/jira_client.py, frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/ducks/issue/api/tests/index.spec.ts, frontend/amundsen_application/static/js/ducks/issue/api/v0.ts, frontend/amundsen_application/static/js/ducks/issue/tests/index.spec.ts, frontend/amundsen_application/static/js/interfaces/Issue.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/index.tsx, frontend/tests/unit/api/issue/test_issue.py, frontend/tests/unit/issue_tracker_clients/test_jira_client.py
When Jira tickets are created from the `Report an issue` button in a table view, there is no way to return to the table from which the ticket was created. This change sends the link to the table in the create issue API, and the Jira client adds the link to the description for created tickets.
I modified JS tests to include the resource path of the table wherever `CreateIssuePayload`s were defined, and I modified `test_jira_client.py` to ensure that the link is added to the description properly.
N/A
- All the …
=> feat: Modifying the create issue action to send a link to the table from which the issue was created

metadata/metadata_service/client/rds_client.py, metadata/metadata_service/proxy/mysql_proxy.py, metadata/tests/unit/proxy/test_mysql_proxy.py
Context:
https://github.com/amundsen-io/amundsen/blob/main/metadata/metadata_service/api/popular_resources.py#L38
`/popular_tables/ endpoint and get_popular_tables() proxy method have been deprecated since version (3.6.0) and will be removed in version 4. Please use /popular_resources/ endpoint instead.`
- add implementation of `get_popular_resources()` with the support of `get_popular_tables` and `get_popular_dashboards`
- some trivial refactoring: removed unneeded projection in mysql_proxy and redundant packages in rds_client
tests for get_popular_resources were added/updated …
=> feat: support popular_resources() in mysql_proxy

databuilder/databuilder/extractor/bigquery_metadata_extractor.py, databuilder/tests/unit/extractor/test_bigquery_metadata_extractor.py
This PR intends to add the column mode when consuming column metadata for bigquery. The column mode indicates if the column is of an array type.
Added a test case for a repeated nested field
=> feat: Add bigquery column mode when consuming bigquery metadata

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/config/config-custom.ts, frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/index.tsx, frontend/docs/application_config.md
This change adds the option to configure a template string that will be inserted in the description of the `Report an issue` modal when creating a ticket from a table view. If defined, the template string will prepopulate the issue description text field and can be used to suggest more detailed information to be provided by the user when an issue is reported.
`frontend/amundsen_application/static/js/config/index.spec.ts` was modified to test the retrieval of the config, and `frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/index.spec.tsx` was modified to test that the description textarea is populated with the expected config, or nothing if the config is a blank string.
A description of the config has been added …
=> feat: Adding configurable description template for reporting issues

frontend/amundsen_application/static/js/components/ResourceListItem/DashboardListItem/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/FeatureListItem/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/UserListItem/index.tsx, frontend/amundsen_application/static/js/ducks/log/api/v0.ts
Added field `position` to click log object which captures the position of the clicked search result on the search results page.
=> feat: extend search result click logging

frontend/amundsen_application/base/base_s3_preview_client.py, frontend/amundsen_application/base/examples/example_s3_json_preview_client.py, frontend/docs/examples/s3_preview_client.md
This commit implements a new preview client that gets preview data from S3. The preview client is good for folks who want to persist their preview data somewhere rather than relaying on an external API call that can both fail and take a while depending on the table the query is being run on.
In addition to the base client, I implemented a JSON version of the preview client that my organization is using. This fetches data from S3 in a JSON format and works very nicely with marshmellow serialization to the PreviewData format.
N/A. I didn't see tests for any other preview client so I decided not to implement any. The preview clients seem to be fairly custom so testing is probably overkill.
Added a documentation file adjacent to the Apache Superset Preview Client docs 👍 
Make sure you have …
=> feat: s3 preview client

databuilder/databuilder/extractor/glue_extractor.py, databuilder/tests/unit/extractor/test_glue_extractor.py
fix: no longer break on resource links and add option to filter on resource type
- [Resource links](https://docs.aws.amazon.com/lake-formation/latest/dg/create-resource-link-database.html) do not include the 'StorageDescriptor' field. As the code was always trying to extract this field, it would break on resource links.
- Add the option to pass `resource-share-type` in order to specify in what tables a user is interested (all or only foreign)
A test was added to verify that resource links no longer break the logic.
Important note: at the moment, AWS provides a different response for resource links when calling the [_search-tables_ API](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.search_tables) depending on the value you provide for …
=> Fix: glue extractor issues

frontend/amundsen_application/api/issue/issue.py, frontend/amundsen_application/base/base_issue_tracker_client.py, frontend/amundsen_application/models/issue_results.py, frontend/amundsen_application/proxy/issue_tracker_clients/asana_client.py, frontend/amundsen_application/proxy/issue_tracker_clients/jira_client.py, frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/config/config-custom.ts, frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/ducks/issue/api/tests/index.spec.ts, frontend/amundsen_application/static/js/ducks/issue/api/v0.ts, frontend/amundsen_application/static/js/ducks/issue/reducer.ts, frontend/amundsen_application/static/js/ducks/issue/sagas.ts, frontend/amundsen_application/static/js/ducks/issue/tests/index.spec.ts, frontend/amundsen_application/static/js/ducks/issue/types.ts, frontend/amundsen_application/static/js/fixtures/globalState.ts, frontend/amundsen_application/static/js/interfaces/Issue.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/constants.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/styles.scss, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/constants.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/styles.scss, frontend/docs/application_config.md, frontend/tests/unit/api/issue/test_issue.py, frontend/tests/unit/issue_tracker_clients/test_jira_client.py
Currently, only one issue tracking project ID can be specified in the flask config. This change adds a configuration that when enabled, the `Report an issue` modal will include a new text input field that allows the user reporting the issue to specify a different Jira project key where they want the issue created instead.
The second component has to do with sorting of the issues displayed on the page. Before this change, it only showed open issues first, then closed issues, and sorted within those categories by descending created date order. Now, within the open and closed categories it will sort by priority first and then created date, and it will not display closed tickets older than 90 days. In addition, instead of linking to view all …
=> feat: Allow override of default issue tracking project and improving sorting of issues displayed

common/amundsen_common/models/table.py, common/setup.py, frontend/tests/unit/api/metadata/test_v0.py
We'd like to support associating multiple applications per table. The databuilder model already permits this (Tables to Applications relationship is many-to-many), but the rest of Amundsen does not. 
Here's the design we're working on (i.e. if there's multiple Applications, they'd get a dropdown, grouped per application name).  
We will make this work for generic applications, following https://github.com/amundsen-io/amundsen/pull/1398.
=> feat: allow multiple applications

databuilder/databuilder/models/application.py, databuilder/setup.py, databuilder/tests/unit/models/test_application.py, metadata/metadata_service/api/swagger_doc/template.yml, metadata/metadata_service/proxy/neo4j_proxy.py, metadata/setup.py, metadata/tests/unit/proxy/test_neo4j_proxy.py, requirements-common.txt
Continuing the work started in https://github.com/amundsen-io/amundsen/pull/1569. To recap, we'd like to generalize `Application` to support multiple apps per resource and add "consumes" as a new possible relationship type in addition to "generates". See design in the earlier PR. 
Here we have generalized the databuilder model and updated the neo4j proxy. Other proxies will keep their current behavior of fetching and returning one app as the `table_writer`.
This PR takes advantage of the fact that the Application model had [an unused field](https://github.com/amundsen-io/amundsen/blob/main/common/amundsen_common/models/table.py#L78) named `kind` which we're using to specify the relationship (consuming or producing).
Note about bw-compatibility:
**Most** of this PR is fully …
=> Feat: Further generalize applications

databuilder/setup.py
Signed-off-by: sinkuladis <sink.vlad@gmail.com>
Removes hard version pinning of `pyatlasclient` used in databuider.
=> chore: remove pyatlasclient version pinning

amundsen-kube-helm/README.md, amundsen-kube-helm/templates/helm/requirements.yaml, amundsen-kube-helm/templates/helm/templates/configmaps.yaml, amundsen-kube-helm/templates/helm/templates/ingress-frontend.yaml, amundsen-kube-helm/templates/helm/values.yaml
1. Migrate deprecated elastic search chart dependency to the official elastic search chart.
2. Update es 6 to es 7
3. Remove elastic search chart advance privilege requirement.
4. Allow users to set up the elastic search service name in values.yaml
5. Change Amundsen docker image tag to the latest
1. Add ingress support for those who deploy Amundsen on a K8s cluster on-premise
When I use the helm chart to deploy Amundsen on my k8s cluster. I have encountered several problems:
1. elastic search chart dependency is deprecated
2. elastic search chart requires advance privileges to deploy pods, which my k8s account does not have.
3. can't change elastic search service name inside values.yaml
4. the docker image version tag is not up to date
So after helm install, I don't have a working …
=> feat: Helm chart improvements 

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/ducks/search/filters/reducer.spec.ts, frontend/amundsen_application/static/js/ducks/search/filters/reducer.ts, frontend/amundsen_application/static/js/ducks/search/filters/sagas.spec.ts, frontend/amundsen_application/static/js/ducks/search/filters/sagas.ts, frontend/amundsen_application/static/js/interfaces/SearchFilterInput.ts, frontend/amundsen_application/static/js/interfaces/index.ts, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/CheckBoxFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/CheckBoxFilter/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/FilterSection/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/FilterSection/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/InputFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/InputFilter/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/constants.ts, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/styles.scss, frontend/amundsen_application/static/js/pages/SearchPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/constants.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/index.tsx
Currently when filtering on the search page, there are `Apply` and `Clear` buttons for every filter section. Only one filter category/value pair could be passed at a time to the search API due to frontend constraints. This change adds just one `Apply filters` button and one `Clear all` button at the bottom of the filters side panel which allows multiple filters to be passed to the API at the same time.
Another change that was made is related to the `Clear all` behavior. The global state was not aware of the filters in the input text fields until they were applied, so with the new UI changes the single clear button did not work at first if the filters had been typed in but not applied. Now the global state is updated whenever anything is typed …
=> feat: Adding single apply and clear buttons to apply to all search filters

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/ducks/search/reducer.spec.ts, frontend/amundsen_application/static/js/ducks/search/reducer.ts, frontend/amundsen_application/static/js/fixtures/globalState.ts, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/CheckBoxFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/CheckBoxFilter/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/FilterSection/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/FilterSection/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/InputFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/InputFilter/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/index.tsx
Fixes related to recent changes to search filtering here: https://github.com/amundsen-io/amundsen/pull/1605
- The original change checked whether the `Apply filters` button had been clicked to know if a search had occurred to provide the correct messaging to the user on the page. This didn't account for searches done from other locations, such as clicking on a tag on the home page, and this resulted in an unintended effect where the results were retrieved but not displayed. This update instead sets a boolean state value in the reducer that will tell if a search action has been taken, compared to an update to the global state without a search action (such as updating the filters).
- When the filters global state was updated on any input field …
=> fix: Search filtering behavior fix

databuilder/databuilder/extractor/dashboard/tableau/tableau_dashboard_table_extractor.py, databuilder/tests/unit/extractor/dashboard/tableau/test_tableau_dashboard_table_extractor.py
Tableau API returns null for dashboard name or project name when the user token does not have access privilege for the dashboard or the project.
If these names are None, we would ignore them and shows some warnings.
Related: #911, amundsen-io/amundsendatabuilder/pull/442
Add tests for the case of None table name
=> fix: Tableau dashboard extractor to ignore dashboards of insufficient privileges

search/search_service/config.py, search/setup.py
This PR bumps the version for amundsen-search to 3.0.0 because new search changes are bw in compatible. 
When bumping make sure to use the following client in config:
`'ELASTICSEARCH_V2': 'search_service.proxy.es_search_proxy.ElasticsearchProxy'`
Major FE release version 4.0.0 is comaptible with the new search service
=> chore: bumped search to 3.0.0

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/FilterSection/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/FilterSection/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/InputFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/InputFilter/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/constants.ts, frontend/amundsen_application/static/js/pages/SearchPage/index.tsx
This change introduces a few minor adjustments to the way that hint text is displayed for the search filters.
1. Placeholder text is now included on the input filters that reads `Exact name or *wild card*` to make it more immediately clear what the field accepts.
2. The hint text will pop up over the input field itself rather than a separate info icon to ensure users are noticing the hint information provided.
3. Now that the input search filters accept multiple values, include info about that in the hint text. This is included in the default values and will require a change on the side of others if they have custom filters.
Added to the `InputFilter` tests to test the new popover on the input text fields.
N/A
Make sure you have checked …
=> feat: Updating input placeholder text and hint text for search filters

amundsen-kube-helm/README.md, amundsen-kube-helm/templates/helm/templates/deployment-neo4j.yaml, amundsen-kube-helm/templates/helm/values.yaml
The current helm chart does not support air-gapped deployment when the k8s cluster being deployed on has no Internet connectivity.  Most of the components support specifying which image registry to use, but the `neo4j` deployment did not.  Not only it didn't support customizing the docker registry, but the initialization of plugins was hard-coded.
This PR adds support to customize the neo4j docker image registry.  It also provides a way to change how the neo4j plugins are injected (or initialized) in the neo4j container.  
By default, the same commands will be executed in the neo4j init container:
```
- "/bin/sh"
- "-c"
- |
curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.3.0.4/apoc-3.3.0.4-all.jar -O
curl -L …
```
=> fix: Added support in helm chart for air-gapped deployment

databuilder/databuilder/extractor/delta_lake_metadata_extractor.py, databuilder/tests/unit/extractor/test_deltalake_extractor.py
delta lake extractor is not able to add badge for the **partition columns**. This change is for extending delta lake extractor  as it detects partition column and add a badge to it.
In a nutshell:
- adding `badges` property to `ScrapedColumnMetadata` class
- setting Partition Column badge when it detects partition column
`databuilder/tests/unit/extractor/test_deltalake_extractor.py` is changed. badge is added to `partition_column`.
=> feat: add partition column badge

frontend/amundsen_application/base/base_bigquery_preview_client.py
Signed-off-by: Bruno Santos <bsilva89@hotmail.com>
Fixed BaseBigqueryPreviewClient so it can work with numeric data types from BQ tables.
No tests added due no new files or features.
N/A.
=> fix: bigquery preview with numeric data type - issue #1658

databuilder/README.md, databuilder/databuilder/task/neo4j_staleness_removal_task.py, databuilder/setup.py, databuilder/tests/unit/task/test_neo4j_staleness_removal_task.py
Neo4j data can exist without either attributes "published_tag" or "publisher_last_updated_epoch_ms" if it is created by an Amundsen user rather than by the publisher. In this case you may not want to have these nodes marked as stale and deleted by the Neo4jStalenessRemovalTask. This new config will allow you to keep these nodes by setting `retain_data_with_no_publisher_metadata` to `True`. The default value to keep the original behavior will be `False`, where any data without the publisher metadata will be marked as stale and deleted by this task.
Added tests to `test_neo4j_staleness_removal_task.py` to test the Neo4j query format when the config is set to `True`.
Added a note about the config and how it is used in `databuilder/README.md`. …
=> feat: Add config to prevent neo4j staleness removal task from removing data with missing publisher metadata

frontend/requirements.txt, frontend/setup.py
As neither JIRA nor Asana integrations are default for frontend this PR moves them to dedicated extra sections.
We want avoid having jira dependencies in frontend container as we are not really using jira integration and our security scanners complain about https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-22824 which is tied to one of the libraries jira client depends on.
n/a
n/a
=> feat: remove jira and asana from primary deps in frontend

metadata/metadata_service/config.py, metadata/requirements.txt, metadata/setup.py
Removes Gremlin from core dependencies of metadata proxy as it's not a default one. Enforcing installation of amundsen-gremlin along with is redundant and shouldn't happen.
n/a
n/a
=> chore: remove gremlin from core dependencies of metadata proxy

databuilder/README.md, databuilder/databuilder/extractor/glue_extractor.py
**glue extractor** does not get `region_name` argument. It might be needed in different scenarios. For example, while using **Databricks** for extracting data from AWS Glue, it gives `NoRegionError: You must specify a region.`
You might be questioning why cant we use aws configuration and set region with **.aws/config** $HOME directory. Databricks is using instance profile for associating cluster with AWS IAM role. It is not a good practice to install aws cli to databricks cluster and configure aws credentials. So, typically, there is no **.aws/config** file stored in databricks cluster, and it is not needed.
In a nutshell, it might be better to have an option to provide `region_name` parameter while creating glue extractor.
Make sure you have checked **all** steps below to ensure a …
=> fix: add region parameter to glue extractor boto3 client instantiation

docs/developer_guide.md
Fixes a broken link to https://www.amundsen.io/amundsen/frontend/docs/installation/ from https://www.amundsen.io/amundsen/developer_guide/.
The link is going to the local .md file, which gave 404 when clicked online: https://www.amundsen.io/frontend/docs/installation.md
Just a docs change
Fixed link
=> docs: Fix broken link to frontend installation

frontend/amundsen_application/static/js/components/SVGIcons/GraphIcon.tsx, frontend/amundsen_application/static/js/components/SVGIcons/constants.ts, frontend/amundsen_application/static/js/features/ColumnList/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/setup.py
Currently there is no indication if there is a need to expand the column details to see whether column has column stats available or not. Users need to expand details even if there is nothing there.
This PR introduces an icon which indicates that a given column has statistics available. I am not strongly opinionated towards icon or placement choice but I think such indicator is a must to improve user experience.
This is how it looks like after this initial implementation:
tbd
tbd
- [] PR adds unit tests, updates existing unit tests, __OR__ documents why …
=> feat: Add column statistics indicator for columns with TableColumnStats available

requirements-common.txt
itsdangerous was released a few hours ago that removed json. https://github.com/pallets/itsdangerous/commit/506ca21d8cc1d16313270c37b6990c9e7762f68e
https://pypi.org/project/itsdangerous/#history
With this newest release, image builds are broken. See this example: https://github.com/youngyjd/amundsen/pull/42
```
[2022-02-18T05:19:20Z] Traceback:
[2022-02-18T05:19:20Z] /usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
[2022-02-18T05:19:20Z]     return _bootstrap._gcd_import(name[level:], package, level)
[2022-02-18T05:19:20Z] /tests/api/brex_lineage/test_graph.py:1: in <module>
[2022-02-18T05:19:20Z]     from amundsen_application.api.brex_lineage.graph import render_attributes
[2022-02-18T05:19:20Z] amundsen_application/__init__.py:11: in <module>
[2022-02-18T05:19:20Z] …
```
=> fix: set itsdangerous version <= 2.0.1

docs/authentication/oidc.md
oidc.md - fix deprecated variable name, fix dockerfile formatting
File:
docs/authentication/oidc.md
1) Deprecated variable name replaced with an actual one:
"APP_WRAPPER" -> "FLASK_APP_MODULE_NAME"
"PP_WRAPPER_CLASS" -> "FLASK_APP_CLASS_NAME"
2) Added the "=" sign in the example Dockerfile ENV statement where it was missing
Reason - omitting of '=' symbol in VAR statements is discouraged as per official doc:
https://docs.docker.com/engine/reference/builder/
No tests, docs actualization.
Please see: Summary of Changes
- [+] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- In case you are adding a dependency, check if the license complies with the [ASF 3rd …
=> docs: Fix deprecated variable name, dockerfile formatting

common/amundsen_common/models/index_map.py, common/setup.py, databuilder/databuilder/publisher/elasticsearch_publisher.py, databuilder/databuilder/task/search/document_mappings.py, databuilder/databuilder/task/search/search_metadata_to_elasticsearch_task.py, databuilder/example/scripts/sample_search_metadata_task.py, databuilder/setup.py, databuilder/tests/unit/publisher/test_elasticsearch_publisher.py, docker-amundsen-local.yml, docker-amundsen.yml, search/README.md, search/search_service/proxy/elasticsearch.py, search/search_service/proxy/es_search_proxy.py, search/setup.py, search/tests/unit/proxy/fixtures.py, search/tests/unit/proxy/test_elasticsearch.py, search/tests/unit/proxy/test_es_search_proxy.py
Document types were already deprecated in ES 7 but are completely removed in ES 8. This PR proposes minor refactor which makes our search proxy and databuilder elasticsearch publisher job & task compatible with Elasticsearch 8 and also backwards compatible with Elasticsearch 7. 
**The change proposes:**
- stop relying on `_type` meta field (not available in ES 8, deprecated in ES 7)
- add mandatory `resource_type` keyword field in `SearchableResource`
- populate mandatory `resource_type` keyword field in databuilder jobs/tasks relying on `elasticsearch_type` property
- rely on `resource_type` in search proxy to properly select which resource is being returned from elasticsearch
- **discontinuation of Elasticsearch 6.x support as it's reached it's EOL https://www.elastic.co/support/eol** …
=> feat: Elasticsearch 8 compatiblity

requirements-common.txt
bump common version in requirements-common.txt to 0.25.0 after Elasticsearch 8 compatibility introduction
n/a
=> chore: bump common version in requirements-common.txt

requirements-common.txt
Currently pinning with only lower boundary makes our packages vulnerable to breaking changes in Amundsen common. This PR adds upper boundary so our packages are relying on common within range of neighbouring versions so we minimize risk of creating incompatible combinations.
Previous approach resulted in a fact that a significantly older version of any service (databuilder/frontend/search/metadata) was relying on the newest possible version of common (established on pip install) which could (and actually did on one occasion) break things.
n/a
n/a
- All …
=> chore: add upper boundary for amundsen-common pin

frontend/amundsen_application/api/__init__.py, frontend/amundsen_application/static/templates/index.html, frontend/amundsen_application/static/templates/opensearch.xml, frontend/amundsen_application/static/webpack.common.ts
When testing https://github.com/amundsen-io/amundsen/pull/1746 from @kristenarmes, I made a mistake and did not verify it correctly. This PR fixes those earlier problems, namely:
- opensearch.xml should come from a `<link rel="search" ...>` and not a script
- the content-type should be set to `application/xml`
- in XML, tags are case-sensitive. The webpack's asset minification lowercased all tags, which needed to be turned off.
Full admission: I got some help by following [datahub.io/opensearch.xml](https://datahubproject.io/opensearch.xml). Thanks to our DataHub friends. 
- In case you are adding a dependency, check if the license complies with the [ASF 3rd …
=> fix: Fix browser search integration

frontend/docs/search_from_browser.md
=> docs: document the opensearch.xml file

frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/styles.scss
Minor fixes for the Report an issue modal, including fixing the specificity of the close button and increasing the z-index so the modal will appear in front of everything.
N/A
N/A
=> fix: Minor styling fixes for Report an issue modal

databuilder/databuilder/extractor/delta_lake_metadata_extractor.py, databuilder/databuilder/models/watermark.py, databuilder/tests/unit/extractor/test_deltalake_extractor.py, requirements-dev.txt
Introducing watermark detection on Delta tables. Since [1] I lost track of this one around the time of going monorepo, here it is once more 🙈 
[1] https://github.com/amundsen-io/amundsendatabuilder/pull/427
Testing for watermarks.
Nothing.
=> feat: Delta table partition watermarks

databuilder/databuilder/transformer/complex_type_transformer.py, databuilder/databuilder/utils/hive_complex_type_parser.py, databuilder/setup.py, databuilder/tests/unit/transformer/test_complex_type_transformer.py, databuilder/tests/unit/utils/test_hive_complex_type_parser.py
Prior to this change, if there was anything that went wrong in the `ComplexTypeTransformer` then an exception would be thrown. Since `TypeMetadata` is an optional field for columns, if anything fails in this transformer it makes more sense to log the issues rather than throw exceptions so that any process using the transformer can continue.
Updated related tests in `test_complex_type_transformer.py` and added a test for if the parsing function fails.
N/A
- All the public functions and the classes in the PR …
=> refactor: Change error handling in ComplexTypeTransformer

databuilder/setup.py
Bump databuilder version to 6.7.4 to include the `ComplexTypeTransformer` error handling changes from https://github.com/amundsen-io/amundsen/pull/1766
N/A
N/A
=> chore: Bump databuilder version to 6.7.4

requirements-common.txt
Fixing Jinja2 version for backwards compatibility
N/A
N/A
=> fix: Add upper-bound for Jinja2 version for backwards compatibility

common/amundsen_common/entity/resource_type.py, common/setup.py, requirements-common.txt
This adds `TypeMetadata` to the list of `ResourceType` enums. This will allow the use of this resource type in the generalized description and badge metadata APIs for `TypeMetadata` resources.
This PR also pins the version of `werkzeug` to 2.0.3 due to the removal of an argument in version 2.1.0 that the current version of `flask` uses.
N/A
N/A
=> feat: Add TypeMetadata to ResourceType enums

common/amundsen_common/entity/resource_type.py, common/setup.py
`Type_Metadata` was originally added to common `ResourceType` with the name format matching the common class name. It needs to instead match the format of the node label which includes the underscore as defined [here](https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/models/type_metadata.py#L17).
N/A
N/A
=> fix: Type_Metadata ResourceType needs to match the node label format

metadata/metadata_service/__init__.py, metadata/metadata_service/api/swagger_doc/template.yml, metadata/metadata_service/api/swagger_doc/type_metadata/badge_delete.yml, metadata/metadata_service/api/swagger_doc/type_metadata/badge_put.yml, metadata/metadata_service/api/swagger_doc/type_metadata/description_get.yml, metadata/metadata_service/api/swagger_doc/type_metadata/description_put.yml, metadata/metadata_service/api/type_metadata.py, metadata/metadata_service/proxy/atlas_proxy.py, metadata/metadata_service/proxy/base_proxy.py, metadata/metadata_service/proxy/gremlin_proxy.py, metadata/metadata_service/proxy/mysql_proxy.py, metadata/metadata_service/proxy/neo4j_proxy.py, metadata/tests/unit/proxy/test_neo4j_proxy.py
This change adds a `TypeMetadata` object to each `Column` if the column node has any `TYPE_METADATA` relations when table metadata is retrieved using the `get_table` API.
The column query in `neo4j_proxy` now looks for optional `TypeMetadata` nodes along with any optional descriptions or badges related to each one. The list of all nodes are then processed based on their key paths to create the correct structure of `TypeMetadata`, where each one may have one or more nested child `TypeMetadata` objects.
Updated `test_neo4j_proxy.py` to include `TypeMetadata` values within `Column`s to make sure the object structure is created correctly from expected query results.
N/A
- …
=> feat: Update metadata neo4j proxy column query to retrieve its TypeMetadata

databuilder/databuilder/publisher/neo4j_csv_publisher.py
Adding a boolean config to control whether publisher metadata (e.g. ) need to be added as properties. Through this config (default True), we can [retain the data](https://github.com/amundsen-io/amundsen/blob/c9727bffaa6aeb53623ad2a808013e35c549f18a/databuilder/databuilder/task/neo4j_staleness_removal_task.py#L173) (won't get purged in async mode) when such metadata is not included.
n/a
n/a
=> feat: add boolean config for adding publisher metadata to neo4j node

metadata/metadata_service/api/type_metadata.py, metadata/metadata_service/proxy/neo4j_proxy.py
The original change to the table metadata API in https://github.com/amundsen-io/amundsen/pull/1776 looked for the type metadata path by splitting on the string `/type/`, however this did not work in all cases because a table or column could be named type. Fixed this issue by using a named groups regex to be clear about the expected location of the type metadata path within the full key.
Also, did some general cleanup of the logic for constructing the `TypeMetadata` objects with their children. Rather than constructing a dict of node name to a tuple of the object itself and a dict of its children, now two dicts are constructed. The first is a mapping of the type metadata path section of the key to the `TypeMetadata` object. The second is a …
=> fix: Fix neo4j proxy column query retrieval of type metadata, adding logging

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/components/SVGIcons/GraphIcon.tsx, frontend/amundsen_application/static/js/features/ColumnList/constants.ts, frontend/amundsen_application/static/js/features/ColumnList/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/styles.scss
Previously, an icon indicating that a column had stats was added to the left of the column name. This was to let users know at a glance if they should care about expanding the column details to see the stats. This change moves the location of that icon to the right side of the column name and moves the column name further left. This is to set up for coming improvements to nested columns, to allow for more screen space for indented column names. This also sets up the UI for the introduction of additional icons to indicate other column metadata, such as unique values, lineage, etc that can be added inline with the stats icon.
Added checking for `OverlayTrigger` components to the existing tests for the stats icon.
N/A
Make sure you have checked …
=> feat: Moving location of the column stats icon

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/css/_layouts.scss, frontend/amundsen_application/static/js/components/TabsComponent/styles.scss, frontend/amundsen_application/static/js/pages/DashboardPage/constants.ts, frontend/amundsen_application/static/js/pages/DashboardPage/index.tsx, frontend/amundsen_application/static/js/pages/DashboardPage/styles.scss, frontend/amundsen_application/static/js/pages/FeaturePage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/constants.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/styles.scss
The left side panel that is displayed on the table, dashboard, and feature detail pages has been reduced in size. This allows users to see more of the main content for these resources since this panel does not close. It is also part of a longer term plan for the table detail view to implement a right side panel that can open to display column details, and this change will also will allow more space when showing nested columns.
**Before:**
**After:**
Updated TableIssues tests to account for the change made to the text in the links to view open and closed issues, to accommodate for the reduced space.
N/A
- In case you are adding a dependency, check if the license complies …
=> feat: Reducing width of left side panel on resource detail pages

amundsen-kube-helm/templates/helm/templates/ingress-frontend.yaml
fix – Helm chart has forgotten directive in ingress template.
Added annotations template.
I needed certmanager annotations in my k8s cluster, and I noticed it missed.
I fixed and tested it.
=> fix:  helm chart: Add forgotten annotations to ingress template.

frontend/amundsen_application/static/js/components/Lineage/Graph/chart.ts, frontend/amundsen_application/static/js/components/Lineage/Graph/constants.ts, frontend/amundsen_application/static/js/components/Lineage/Graph/index.spec.tsx
This PR introduces some UI improvements to especially fix the overlapping of node labels in the Lineage chart when there are many nodes being rendered.
This is achieved by assigning a fixed the horizontal space between different labels in the graph and rearranging the position of the labels based on the graph direction.
Here are the screenshot to compare before and after:
*Before:*
*After:*
Updated one test case for Lineage graph dimension calculation.
N/A
- All the public functions and the …
=> fix: Improve Lineage chart UI

frontend/amundsen_application/static/js/components/Lineage/Graph/chart.ts, frontend/amundsen_application/static/js/components/Lineage/Graph/constants.ts
A follow-up to https://github.com/amundsen-io/amundsen/pull/1815, instead of assigning a fixed horizontal spacing between different levels of Lineage graph, this PR introduces the changes to set this spacing dynamically, based on the longest label length of that level.
Additionally, some changes are introduced to fix the transition effect of children nodes to move in and out from their respective parents. Previously, all nodes were transitioning from the root node.
No test changes are needed for this UI change.
N/A …
=> fix: Improve Lineage chart UI -- follow-up 

common/amundsen_common/models/search.py, common/setup.py, requirements-common.txt
Related PR for Search Service #1820 
Added optional `highlight_options` field to search request, these allow highlighting to be enabled for each resource like:
```
{
"results_per_page": 10,
"page_index": 0,
"resource_types": [
"table"
],
"query_term": "amundsen",
"filters": [],
"highlight_options": {
"table": {
"enable_highlight": true
}
}
}
```
=> feat: added highlight options to search API definition

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/css/_layouts.scss, frontend/amundsen_application/static/js/components/Table/index.spec.tsx, frontend/amundsen_application/static/js/components/Table/index.tsx, frontend/amundsen_application/static/js/components/Table/styles.scss, frontend/amundsen_application/static/js/components/Table/testDataBuilder.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/constants.ts, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnStats/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnStats/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/styles.scss, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx, frontend/amundsen_application/static/js/utils/index.spec.ts, frontend/amundsen_application/static/js/utils/navigationUtils.ts
This change adds in a right side panel to the table details page. When a column name is clicked, a panel on the right side of the page is expanded to display column details that have previously been displayed in the dropdown underneath the column name. This change is meant to free up the use of the dropdown for future nested columns work that is coming soon. See [this RFC](https://github.com/amundsen-io/rfcs/blob/master/rfcs/046-column-details-access-and-side-panels.md) for further details around design decisions for this feature.
When a column name is selected and the panel is expanded, that row is highlighted so it is easy to see which column name the current panel contents relate to. In addition, to save space within the main column table, when the panel is open the badges and usage …
=> feat: Create right side column details panel

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnLineage/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnLineage/styles.scss, frontend/amundsen_application/static/js/features/ColumnList/constants.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
An extra call needed to be made to retrieve the table column lineage when the column details side panel is opened. This change makes the call and also makes it so the layout of the upstream and downstream lineage is displayed in one column rather than two. In addition, the Sort By controls in the top right will be hidden when the panel is open to save space in the header for smaller screens.
Added some `TableDetailPage` tests to check the state changes and that the lineage loads when the side panel is toggled.
N/A …
=> fix: Loading/display for column lineage in column details panel

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/components/Table/index.spec.tsx, frontend/amundsen_application/static/js/components/Table/index.tsx, frontend/amundsen_application/static/js/components/Table/testDataBuilder.tsx, frontend/amundsen_application/static/js/ducks/tableMetadata/api/helpers.spec.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/index.spec.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/reducer.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/sagas.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/types.ts, frontend/amundsen_application/static/js/features/ColumnList/ColumnDescEditableText/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/testDataBuilder.ts, frontend/amundsen_application/static/js/fixtures/metadata/table.ts, frontend/amundsen_application/static/js/interfaces/TableMetadata.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/ListSortingDropdown/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/ListSortingDropdown/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
These changes are made in anticipation of the upcoming work to add in nested columns retrieved from the backend rather than frontend parsing outlined [here](https://github.com/amundsen-io/rfcs/blob/master/rfcs/047-nested-columns.md). This removes the dependence on the columns' indices around descriptions and side panel column details, and now relies on names and keys to be able to extend the same usage to nested columns.
- Add `TypeMetadata` in frontend model as an optional `TableColumn` field - this data was already being retrieved from the metadata API so now it is being populated
- Use the column `name` directly for getting/setting column descriptions rather than its index
- Add column `key` field to `TableColumn`s to be used to keep track …
=> refactor: Refactor various column details and add TypeMetadata to TableColumn model

frontend/amundsen_application/static/js/components/Tour/index.tsx
Fixes issue with active Tours not reseting when changing pages
Manual
N/A
=> fix: fixes tour not resetting on different pages

search/search_service/proxy/es_search_proxy.py
Change filters so if the field is not mapped for the resource the filter won't be applied to the query for that resource
=> fix: better behavior for search filters

frontend/amundsen_application/static/js/ducks/search/filters/reducer.ts
Before this change when default filters were configured we would make an extra load url search request which is not necessary.
=> fix: avoid extra load url search call when default filters are applied

frontend/amundsen_application/api/__init__.py, frontend/amundsen_application/config.py, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config.ts, frontend/amundsen_application/static/templates/index.html
Signed-off-by: rajasekhar reddy <reddy.rajasekhar.parvatha@gmail.com>
Currently the Amundsen frontend needs to be rebuilt for any config change (example: enabling dashboards, enabling ML features etc)
This feature allows this frontend appConfig to be overriden by an externally injected js file (example: via helmchart volume mounts, docker-compose volumes etc)
This will make it easier to run amundsen with custom config without the need to rebuild from source. 
Create new js file with name as  **config-external.js** in **static** directory as below 
filename : config-external.js
```
window['configExternal'] = {
badges: {},
browse: {
curatedTags: [],
showAllTags: true,
showBadgesInHome: true,
},
date: {
default: 'MMM DD, YYYY',
dateTimeShort: 'MMM DD, YYYY ha z',
dateTimeLong: 'MMMM Do YYYY …
```
=> feat: enable UI config overrides post build 

frontend/amundsen_application/static/css/_layouts.scss
Before:
Now:
css change. no new unit test created.
NA
=> fix: fix misaligned source icon

README.md
Add WePay to the company list in readme
N/A
N/A
=> chore: updated company list in readme

docs/installation.md, docs/windows_troubleshooting.md
An `extras_require` bug is documented in #1650 and #1447. Both suggest the same workaround and I only found this after trying to fix the bug myself. This adds an explicit note to the installation guide to point windows users to that workaround.
This is my first PR to the project, so if there are docs style guides which I'm unaware of, I'm very happy to re-draft. 😄 
=> docs: Update docs for Windows workaround to solve databuilder extras_require error.

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/components/Table/constants.ts, frontend/amundsen_application/static/js/components/Table/index.spec.tsx, frontend/amundsen_application/static/js/components/Table/index.tsx, frontend/amundsen_application/static/js/components/Table/styles.scss, frontend/amundsen_application/static/js/components/Table/testDataBuilder.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/styles.scss, frontend/amundsen_application/static/js/features/ColumnList/testDataBuilder.ts, frontend/amundsen_application/static/js/interfaces/ColumnList.ts, frontend/amundsen_application/static/js/interfaces/TableMetadata.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
These changes repurpose the column dropdown functionality to display nested columns rather than column details. Clicking on the column names will display the details instead of the dropdown (see https://github.com/amundsen-io/amundsen/pull/1831).
This dropdown usage will only be available to those using `TypeMetadata` on the backend, where the complex types are parsed in databuilder and stored in the db. For all others, the existing frontend parsing/display behavior for nested columns has been preserved. All users regardless of `TypeMetadata` usage will no longer be able to view column details through the dropdown.
Please note that in this specific PR the changes described here have been disabled. Once the changes reach parity with the …
=> feat: Adding nested columns to be displayed in the column dropdowns as rows

search/README.md
=> chore: updated search readme

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/css/_typography-default.scss, frontend/amundsen_application/static/js/components/Table/constants.ts, frontend/amundsen_application/static/js/components/Table/index.spec.tsx, frontend/amundsen_application/static/js/components/Table/index.tsx, frontend/amundsen_application/static/js/components/Table/styles.scss, frontend/amundsen_application/static/js/components/Table/testDataBuilder.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnType/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/amundsen_application/static/js/interfaces/ColumnList.ts
This work builds on the nested columns changes outlined in this [RFC](https://github.com/amundsen-io/rfcs/blob/master/rfcs/047-nested-columns.md). The changes included here are disabled for now until the nested columns dropdown behavior is enabled.
1. Smaller height rows are included in the table to clearly show which types are nested arrays and/or maps. This is to help distinguish from structs, which previously were the only ones being displayed since they had named nested columns.
2. The nested column rows will be expanded by default, unless a configured threshold is reached. This config is the same that has been used for the frontend parsing of nested columns.
Examples of the special type rows:
Array of structs
Map
Array of maps
- Check …
=> feat: Nested columns special type rows and expand by default

frontend/amundsen_application/api/metadata/v0.py, frontend/amundsen_application/api/utils/metadata_utils.py, frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/components/EditableText/index.tsx, frontend/amundsen_application/static/js/ducks/rootSaga.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/index.spec.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/reducer.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/sagas.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/types.ts, frontend/amundsen_application/static/js/features/ColumnList/ColumnDescEditableText/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDescEditableText/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/amundsen_application/static/js/interfaces/TableMetadata.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, frontend/tests/unit/api/metadata/test_v0.py
- Use the new type metadata description get and update APIs to allow users to view and add/edit descriptions for nested columns from the UI
- The column description APIs were changed on the frontend side only to take a column key instead of column name to be consistent with the type metadata APIs
- The logic to decide whether the badges column should be displayed was updated to check if any type metadata values have any badges as well instead of checking only the top level columns
- Added tests for get/update type metadata description APIs
- Added tests for `ColumnDescEditableText` to test when it is used by a top level column or a nested column
N/A
- In case you are …
=> feat: Use type metadata description get/update apis

databuilder/setup.py
Originally, the databuilder unit test will fail because of the fastAPI version problem. This blocked all the databuilder related PRs. Fast API is required by Feast.
An example of the failing workflow: https://github.com/amundsen-io/amundsen/runs/6646082819
The log looks like
```
tests/unit/extractor/test_feast_extractor.py:13: in <module>
from databuilder.extractor.feast_extractor import FeastExtractor
databuilder/extractor/feast_extractor.py:7: in <module>
from feast import FeatureStore, FeatureView
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/feast/__init__.py:13: in <module>
from .feature_store import FeatureStore
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/feast/feature_store.py:[38](https://github.com/amundsen-io/amundsen/runs/6646082819?ch …
```
=> test: Fix databuilder PR unit test import error

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/components/SVGIcons/DoubleChevronDown.tsx, frontend/amundsen_application/static/js/components/SVGIcons/DoubleChevronUp.tsx, frontend/amundsen_application/static/js/components/SVGIcons/index.tsx, frontend/amundsen_application/static/js/components/Table/index.spec.tsx, frontend/amundsen_application/static/js/components/Table/index.tsx, frontend/amundsen_application/static/js/components/Table/styles.scss, frontend/amundsen_application/static/js/features/ColumnList/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/constants.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/styles.scss
Added a button that displays `Expand all nested` or `Collapse all nested` to allow users to expand/collapse all nested columns with one click. This will default to show as `Collapse all nested` for most cases, but if the amount of columns exceeds the configured threshold then it will default to have all the rows collapsed and display `Expand all nested` on the button. In addition, a small caret button was added to the table header in vertical alignment with the other expand/collapse buttons per row that allows users to expand all/collapse all from there as well.
In the `Table` component, added tests for the rendering of the expand/collapse all button that appears in the table header, along with lifecycle tests for when the button is clicked. …
=> feat: Adding expand all/collapse all functionality for nested columns

databuilder/requirements.txt
Relax the pandas version requirements for the databuilder package, which is currently limited to a version released over 2 year ago, to allow for more recent versions. This will make it possible to easily include the package in repos that use modern versions of pandas.
Tested on pandas 1.4.2 (the current version).
Pandas usage was already tested in unit tests so no new tests are necessary.
Very little of the pandas API is used, essentially just `read_csv`, which is a very stable part of the API.
- All the public functions and the classes in the PR …
=> fix: relax pandas version requirements for databuilder

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/features/NavBar/index.tsx
Previously, if you configured a product/feature tour by using a wildcard path, the actual path of the page you visited would be stored rather than with the wildcard. This resulted in the tour showing up for every new page you visited under the wildcard. This change stores the actual configured path so that if wildcards are used, it will only show the tour on the first page you visit.
Updated tests to handle the change to the return value of `getProductToursFor`
N/A
- All the public functions and the classes …
=> fix: Updating tour feature to store wildcard path instead of the url path

databuilder/databuilder/extractor/dashboard/tableau/tableau_dashboard_table_extractor.py
When unpacking tableau datasources, if a table reference had more than two parts (i.e. `database.schema.table` rather than just `table` or `schema.table`) this would raise a `KeyError` during unpacking and the script would stop abruptly.
This fix adds handling code for greater degrees of qualification and also a graceful path for dbapis which have potentially very long qualification options (e.g. `foo.bar.baz.db.schema.table`). I haven't accounted for anything more specific that _something that will work_ for now, although that would be something that could be built on at a later date. This solution solves for the most common use case where the database may be qualified in the table reference.
No tests added as I don't believe there is an existing test which could be extended to cover …
=> fix: Handle qualified tableau datasources more gracefully

README.md, databuilder/README.md, databuilder/databuilder/extractor/eventbridge_extractor.py, databuilder/requirements.txt, databuilder/tests/unit/extractor/test_eventbridge_extractor.py
Added a new extractor for fetching schema metadata from AWS EventBridge schema registries.
Added `databuilder/tests/unit/extractor/test_eventbridge_extractor.py` for testing the new extractor.
Updated `README.md` and `databuilder/README.md` to reflect the addition of the new extractor.
=> feat: Amazon EventBridge Extractor

databuilder/README.md, frontend/amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx, frontend/setup.py
This change enables the new nested columns. This will not change anything for those who have not configured the `ComplexTypeTransformer` to create `TypeMetadata` objects for their `ColumnMetadata`s.
For those that do have the transformer configured, the following changes will be available:
- Expand/collapse [each level](https://github.com/amundsen-io/amundsen/pull/1865) (use arrows) or [all at once](https://github.com/amundsen-io/amundsen/pull/1888) (use button in the header)
- [View/edit descriptions](https://github.com/amundsen-io/amundsen/pull/1876) for nested fields: click on a row and use the sidebar
- Add badges for nested fields (same cURL workflow as before)
- More [clear/correct display of …
=> feat: Enable new nested columns

databuilder/databuilder/publisher/neo4j_csv_publisher.py, databuilder/setup.py
Added optional `additional_fields` property to publisher so we can add additional metadata about the publishing job to a node, like an airflow execution ID or name.
=> feat: added addition fields config to publisher

frontend/amundsen_application/static/js/config/config-custom.ts, frontend/docs/application_config.md
- Added default value for `announcements.enabled` to custom config to increase verbosity
- Fixed wrong object name (typo) in the documentation
- Added information about `config-default.ts` file to docs
- Added information about `announcement_client.md` README
I've checked that announcements are disabled when the variable added to `custom-config.ts` is set to false and that setting it to true enables the feature. No new automated tests are needed IMO.
Described above
=> docs: Improves the frontend documentation on announcements 

frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/ducks/search/api/tests/index.spec.ts, frontend/amundsen_application/static/js/ducks/search/sagas.ts, frontend/amundsen_application/static/js/pages/SearchPage/constants.ts, frontend/amundsen_application/static/js/pages/SearchPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/index.tsx
Instead of retrieving the search results per page from a constant, this PR introduces the changes to have configurable search results per page.
All related tests using the old constant (`RESULTS_PER_PAGE`) are updated.
N/A
=> feat: Extract search results per page into a config variable

databuilder/databuilder/task/search/document_mappings.py, databuilder/databuilder/task/search/search_metadata_to_elasticsearch_task.py, databuilder/setup.py
Added mapping subfields that contain the tokenized text with no stemming so we can prioritize exact text matches over stemmed ones when possible, using ngram to allow combinations of words too.
=> feat: added ngram subfield with no stemming on ES mappings

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/css/_layouts.scss, frontend/amundsen_application/static/css/_variables-default.scss, frontend/amundsen_application/static/js/components/Table/styles.scss, frontend/amundsen_application/static/js/components/TabsComponent/index.spec.tsx, frontend/amundsen_application/static/js/components/TabsComponent/index.tsx, frontend/amundsen_application/static/js/components/TabsComponent/styles.scss, frontend/amundsen_application/static/js/pages/TableDetailPage/constants.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/styles.scss
- Make the `TabsComponent` and the `Table` header sticky when you scroll on pages that use them
- Hide the Expand/Collapse All button in the top right of the `TableDetailPage` when the page is resized to smaller than a set width to not overflow on top of the tabs (this action is still available by clicking the arrow in the header in the top right of the table)
- Small bug fix to close the right side panel on the `TableDetailPage` if it is open when the tab is changed
N/A
N/A
- All the public functions and …
=> feat: Sticky TabsComponent and Table headers

metadata/metadata_service/proxy/gremlin_proxy.py
Currently, using AWS Neptune as the backend, the get_lienage function is not implemented at the `NeptuneGremlinProxy`,  `AbstractGremlinProxy` and `BaseProxy`, which means that the lineage graph & the frontend tab displaying lineage does not work properly due to the missing implementation. For details, you can refer to this chat : 
https://amundsenworkspace.slack.com/archives/C01A87A5EUU/p1653483057967299?thread_ts=1653374819.089879&cid=C01A87A5EUU
Hence, this PR attempts to create such functionality so that lineage works fine using Neptune as backend.
I tested the code using my company's aws environment (which uses AWS neptune & opensearch as the backend) and it worked fine.
N/A
- In case you are adding a …
=> feat: add get_lineage support for neptune backend

frontend/amundsen_application/static/js/components/TabsComponent/styles.scss
Changing the `TabsComponent` styling to only be sticky on pages that use scrolling tables or lists, including `TableDetailPage`, `DashboardPage`, and `FeaturePage`.
N/A
N/A
=> fix: Change TabsComponent styling to only be sticky in certain cases

metadata/metadata_service/proxy/gremlin_proxy.py
Currently, using AWS Neptune as the backend, the get_dashboard function is not implemented at the `NeptuneGremlinProxy,` `AbstractGremlinProxy `and `BaseProxy`, which means that the dashboard at frontend does not display properly due to the missing implementation. For details, you can refer to this chat :
https://amundsenworkspace.slack.com/archives/C01A87A5EUU/p1653483057967299?thread_ts=1653374819.089879&cid=C01A87A5EUU
Hence, this PR attempts to create such functionality so that dashbaord works fine using Neptune as backend.
I tested the code using my company's aws environment (which uses AWS neptune & opensearch as the backend) and it worked fine.
N/A
- [ x ] PR title addresses the issue accurately and …
=> feat: add get_dashbaord support for neptune

frontend/amundsen_application/static/js/features/ColumnList/ColumnType/parser.ts
Signed-off-by: Kian Ahrabian <kahrabian@yahoo.com>
Fix nested UI for metadata extracted from EventBridge
The PR only enables an existing feature for a certain set of extracted metadata.
-
=> fix: Fix nested UI for eventbridge metadata

databuilder/databuilder/extractor/neo4j_extractor.py, databuilder/databuilder/publisher/neo4j_csv_publisher.py, databuilder/databuilder/task/neo4j_staleness_removal_task.py, databuilder/requirements.txt, databuilder/setup.py, docker-amundsen.yml
The newest driver is compatible with neo4j DB version >= 3.5 which was released in 2018.
- Migrated amundsen-databuilder to use neo4j-driver 4.4.5
- The driver for Metadata will be upgraded in a separate PR
**Issue:** https://github.com/amundsen-io/amundsen/issues/1008
=> chore: migrate databuilder to neo4j-driver 4.4.5

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/features/ColumnList/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/index.tsx
This change adds a config to allow adding a list of stat types where, if they are the only ones present for a column, the stats icon will not be displayed next to that column's name. This is useful in the case of columns only having very common stats, such as column usage, so the users will not click on the column expecting to see more info. The default value is an empty list so this will only affect those who configure it.
Added a test for the config, and modified tests for determining whether the icon is displayed for a given column
N/A …
=> feat: Exclude stats icon if configured stat types are the only ones present

frontend/amundsen_application/static/js/components/Table/constants.ts, frontend/amundsen_application/static/js/components/Table/index.tsx
When navigating to a link for a specific column, this change will scroll the column row to the center of the table instead of the top so it doesn't hide behind the sticky header.
N/A
N/A
=> fix: Show the column in the center of the table when navigating to a column link

databuilder/databuilder/extractor/bigquery_metadata_extractor.py, databuilder/databuilder/extractor/neo4j_extractor.py, databuilder/databuilder/publisher/neo4j_csv_publisher.py, databuilder/databuilder/task/neo4j_staleness_removal_task.py, databuilder/setup.py
=> fix: session db name

databuilder/databuilder/extractor/hive_table_last_updated_extractor.py
- Related issue: https://github.com/amundsen-io/amundsen/issues/1608
- Similar PR: https://github.com/amundsen-io/amundsen/pull/1878
- Currently, HiveTableLastUpdatedExtractor is only workable with MySQL connection string. The syntax of the SQL statement is not compatible with Postgres
- Followed the [method](https://github.com/amundsen-io/amundsen/blob/30cf377ef9d4516cc36f4c7cf08fc5abc4d77461/databuilder/databuilder/extractor/hive_table_metadata_extractor.py#L115) in HiveTableMetadataExtractor
- Added SQL statement for Postgres
- Added a helper function to choose the SQL statement based on the connection string
This change has been running in our production environment for a couple of months. I believe no additional unit test is needed since it's simply fixing an unexpected behavior. …
=> fix: Add postgres compatibility in HiveTableLastUpdatedExtractor

databuilder/databuilder/extractor/presto_view_metadata_extractor.py
- Related issue: https://github.com/amundsen-io/amundsen/issues/1608
- Currently, PrestoViewMetadataExtractor is only workable with MySQL connection string. The syntax of the SQL statement is not compatible with Postgres
- Followed the [method](https://github.com/amundsen-io/amundsen/blob/30cf377ef9d4516cc36f4c7cf08fc5abc4d77461/databuilder/databuilder/extractor/hive_table_metadata_extractor.py#L115) in HiveTableMetadataExtractor
- Added SQL statement for Postgres
- Added a helper function to choose the SQL statement based on the connection string
This change has been running in our production environment for a couple of months. I believe no additional unit test is needed since it's simply fixing an unexpected behavior.
Make sure you have checked **all** steps below to ensure a timely …
=> fix: Add postgres compatibility in PrestoViewMetadataExtractor

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, frontend/amundsen_application/static/js/features/PreviewData/index.tsx, frontend/amundsen_application/static/package-lock.json, frontend/amundsen_application/static/package.json
The default handling of the preview data API response used `JSON.parse()` which does not handle big ints, and this resulted in loss of precision. This change makes use of the [json-bigint](https://www.npmjs.com/package/json-bigint) package to parse and display the values to correctly handle any large numbers.
N/A
N/A
=> fix: Fix handling of big ints in preview data

frontend/amundsen_application/static/js/components/Badges/BadgeList/index.tsx, frontend/amundsen_application/static/js/config/config-custom.ts, frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/docs/application_config.md
Adds a new boolean configuration, `hideNonClickableBadges`, to control whether non-clickable (only column type at the moment) badges should be shown on the homepage or not. This potentially improves the user experience and declutters the homepage.
Added a new unit test for the config util.
N/A
=> feat: Add config to hide non-clickable badges

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
Check to see if column lineage is enabled before attempting to retrieve it when toggling open the column details side panel.
Modified existing tests to confirm that column lineage is loaded only when column lineage is enabled.
N/A
=> fix: Don't retrieve column lineage when it is not enabled

frontend/amundsen_application/static/css/_list-group.scss, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.tsx, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/LineageList/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/LineageList/index.tsx
This PR adds a new optional configuration to existing `TableLineageConfig`, to set up field based rules, which are used to disable "lineage list view" links based on regular expression matching. This config is particularly useful when some of the table resources should appear in the Lineage graph, however are not ingested into catalog or should not be accessible by users.
No test changes are required.
A comment added to the new config explaining the purpose.
- All the public functions and …
=> feat: Add optional configuration to disable Lineage list view links

databuilder/databuilder/utils/publisher_utils.py, databuilder/setup.py
It appears the new neo4j driver uses a different error message than it did before for indicating that constraints or indices have already been created. This change updates the publisher check to look for the [error status code](https://neo4j.com/docs/status-codes/current/) instead of a line of text.
N/A
N/A
=> fix: For new publisher fix error handling for already created constraints/indices

metadata/metadata_service/proxy/neo4j_proxy.py
=> fix: no reason to raise a 404 when a user has no bookmarks or reads

metadata/metadata_service/api/user.py, metadata/metadata_service/proxy/neo4j_proxy.py
Added logging in case this happens again.
=> fix: Dashboard User relationships raised 404s also

metadata/metadata_service/proxy/neo4j_proxy.py
dbms.cluster.overview() will return one record per instance so expecting single record is incorrect
=> Get the first item from the healthcheck response

frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/LineageList/index.tsx
This PR extends the recently added Lineage list view configuration to include `badges` key, to be able to also disable Lineage list view UI links based on a badges list configuration.
No test changes are needed.
No documentation changes are needed.
=> feat: Extend Lineage list view configuration

frontend/amundsen_application/static/js/components/Badges/BadgeBrowseList/index.tsx, frontend/amundsen_application/static/js/components/Badges/BadgeList/index.spec.tsx, frontend/amundsen_application/static/js/components/Badges/BadgeList/index.tsx
At the moment, when `hideNonClickableBadges` is configured to be `true`, the column badges are hidden everywhere in the app. This PR makes to changes to hide them only on the homepage.
Existing tests should pass with these changes.
N/A
=> fix: Fix hideNonClickableBadges configuration

databuilder/databuilder/extractor/bigquery_usage_extractor.py
Related to issue #1979
Fix for removing the entire date suffix instead of a fixed length in a table name in bq_usage_extractor.py 
=> fix: Correct sharded table prefix extraction in Bigquery Usage Extractor

metadata/metadata_service/proxy/gremlin_proxy.py
My previous PR [here](https://github.com/amundsen-io/amundsen/pull/1927) didn't use the built-in retry-able query executor, which would result in connection lost with AWS neptune after amundsen runs for a while. Hence this PR targets to rectify the error and make sure all queries use the retryable query executor
All queries made to neptune will use the built-in retryable query executor
Tested in my company's environment and runs well
N/A
=> feat-use-retryable-query-executor

search/search_service/proxy/es_proxy_v2.py
=> fix: add f to search filter logging

databuilder/databuilder/loader/file_system_neo4j_csv_loader.py, databuilder/databuilder/publisher/neo4j_csv_unwind_publisher.py, databuilder/databuilder/publisher/publisher_config_constants.py
- Added publisher config `PRESERVE_EMPTY_PROPS` to `Neo4jCsvUnwindPublisher`
- True (default): existing behavior of publishing node or relation properties even if they have empty values
- False: set empty properties to NULL so they will not show up on the nodes or relations
- Allow multiple relations between the same two nodes when not publishing reverse relations
- Note: must add `key` as an attribute for the relation
- Now has the relation `key` as part of the merge statement so unique relations will all be published
- Appends the loader-generated key to the generated file names in case there are more than one for the same groupings of nodes and relations
N/A
N/A
- In …
=> feat: Allow null values set for empty props in neo4j unwind publisher and multiple rels between nodes

databuilder/databuilder/publisher/neo4j_csv_unwind_publisher.py, databuilder/databuilder/publisher/publisher_config_constants.py, databuilder/setup.py
Added publisher config `NEO4J_PROP_TYPES_TO_CONFIGURE` to `Neo4jCsvUnwindPublisher`. If used, this should be set to a dict using node or relation property names as keys mapped to the function name used to configure a specific type for that property. The values of the properties should be in the correct format that the function accepts.
For example, a config of `{'start_time': 'datetime', 'publish_tag': 'date'}` where the property values are in the format `<date>T<time>` and `<date>` would apply `datetime(n.start_time)` and `date(n.publish_tag)` in the prop merge statement to create the props as `DateTime` and `Date` types instead of strings.
N/A
N/A
- In case you are …
=> feat: Add configurable prop types to neo4j csv publisher

frontend/amundsen_application/static/js/components/ToggleSwitch/ToggleSwitch.tsx, frontend/amundsen_application/static/js/components/ToggleSwitch/styles.scss, frontend/amundsen_application/static/js/pages/SearchPage/ResourceSelector/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/CheckBoxFilter/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/ToggleFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/ToggleFilter/index.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/ToggleFilter/styles.scss, frontend/amundsen_application/static/js/pages/SearchPage/SearchPanel/styles.scss
Signed-off-by: Ben Dye <bdye@lyft.com>
Summary of Changes
Previously, toggle filters on the search page were functioning counterintuitively. When toggled to false, they excluded all results that did not have the filtered category set to false, rather than including all results, true and false.
Tests
Existing tests cover the toggle filters and still pass. I added some additional tests for the clearFilters callback and its expected behavior.
Documentation
Didn't modify any documentation.
CheckList
Make sure you have checked all steps below to ensure a timely review.
PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …
=> Fix toggle filter and styling; update tests

databuilder/README.md
[docs: Fix typo on BigQuery's instructions]
Fixing a typo on Bigquery's instructions
N/A
Reflected on the PR
=> docs: Fix typo on BigQuery's instructions

common/amundsen_common/models/api/health_check.py, common/amundsen_common/models/lineage.py, common/setup.py, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.spec.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.tsx, frontend/amundsen_application/static/js/interfaces/Lineage.ts, frontend/amundsen_application/static/js/interfaces/Resources.ts, requirements-common.txt
- use a link received from metadata that is different than the one that directs you to a new table details page for the table items list
=> feat: use different internal link than the table details page on lineage

common/amundsen_common/models/lineage.py, common/setup.py, frontend/amundsen_application/api/metadata/v0.py, frontend/amundsen_application/static/js/interfaces/Lineage.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/LineageList/index.tsx, requirements-common.txt
- Allow metadata to return an `in_amundsen` field for each lineage item so that table links can be disabled if a table that showed up in lineage data doesn't currently exist in Amundsen (ex: temporary tables)
=> feat: added optional in_amundsen bool to lineage items

frontend/amundsen_application/static/css/_list-group.scss, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/styles.scss
- when a list item is disabled it should look different than the ones that are still enabled to avoid user confusion
=> fix: better styling for disabled items

frontend/amundsen_application/static/js/components/ResourceList/styles.scss, frontend/amundsen_application/static/js/pages/TableDetailPage/LineageList/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/LineageList/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/constants.ts, frontend/amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
Adds loading spinners to the table lineage tabs
Makes it consistent with the dashboard tab loading state 
Added tests
=> fix: adds loading spinners to table lineage tabs

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/.betterer.ts, frontend/amundsen_application/static/js/components/Tour/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx, frontend/amundsen_application/static/js/utils/navigationUtils.ts
Fixes table scrolling issue
Updates betterer ESLint rules
Tested manually
=> fix: fixes scrolling issue after tab changes

databuilder/databuilder/extractor/bigquery_metadata_extractor.py, databuilder/tests/unit/extractor/test_bigquery_metadata_extractor.py
Changed the default type of table and column description in BigQuery_metadata_extractor to None.
This change was made so that the table and columns descriptions entered through the UI persist in the backend db (mysql in our case).
Currently because the default is an empty string every time metadata is extracted from BigQuery the descriptions entered through the UI are overwritten by the empty string.
This can be avoided by making sure description is set to None if it does not exist.
https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/models/description_metadata.py#L75 …
=> Fix: Change default value for 'description' in BigQuery_metadata_extractor results

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/css/_buttons-default.scss, frontend/amundsen_application/static/css/_popovers.scss, frontend/amundsen_application/static/js/components/Alert/alert.story.tsx, frontend/amundsen_application/static/js/components/Alert/index.spec.tsx, frontend/amundsen_application/static/js/components/Alert/index.tsx, frontend/amundsen_application/static/js/components/DefinitionList/definitionList.story.tsx, frontend/amundsen_application/static/js/components/DefinitionList/index.spec.tsx, frontend/amundsen_application/static/js/components/DefinitionList/index.tsx, frontend/amundsen_application/static/js/components/DefinitionList/styles.scss, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/features/Feedback/styles.scss, frontend/amundsen_application/static/js/pages/DashboardPage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/DataPreviewButton/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/DataPreviewButton/styles.scss, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx, frontend/docs/application_config.md
Extends the notices feature to support showing extra information about the notices
Creates reusable DefinitionList component
Tweaks button styles
Normalizes Modal styles
Added tests
Updated
- [] In case of new functionality, my PR adds documentation that describes how to use it.
=> feat: extends resource notices to support extra information

metadata/metadata_service/proxy/gremlin_proxy.py
- Swapped order of `path` and `downstream_tables` arguments in `_parse_lineage` function. 
- Added in kwargs when calling function to increase robustness.
Test suites not relevant for this bug fix, but changes have been tested internally with Neptune server.
No documentation to add as there is no change in behavior. 
=> Fix: Corrected position of arguments in _par

frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/index.tsx
Signed-off-by: Muhammad Mikaal S. Anwar <mikaalanwar@gmail.com>
This PR provides a fix for the [issue](https://github.com/amundsen-io/amundsen/issues/2053) by allowing multiple search filters per category.
The section filter key is updated to be unique (by appending an index) in order to ensure it gets re-rendered properly upon each transition of resource type (switching back and forth from Tables to Dashboards) on the search page.
It's a minor change in internal to a component so no further testing was needed. Relevant tests have been updated accordingly.
N/A …
=> Fixes UI crashing on "search page" if we multiple filters with the same category are added (issue #2053)

databuilder/README.md
Per https://github.com/amundsen-io/amundsen/pull/1722 and https://github.com/amundsen-io/amundsen/pull/1386, databuilder seems to already supports ES 8.x, but there is no mention in [requirements.txt](https://github.com/amundsen-io/amundsen/blob/main/databuilder/requirements.txt).
Should close https://github.com/amundsen-io/amundsen/issues/2050.
Specify ES 7.x as supported per actual [requirements.txt](https://github.com/amundsen-io/amundsen/blob/main/databuilder/requirements.txt).
- All the public functions and the classes in the PR contain docstrings …
=> docs: Update databuilder docs ES version reference

frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/ducks/lineage/index.spec.ts, frontend/amundsen_application/static/js/ducks/lineage/reducer.ts, frontend/amundsen_application/static/js/pages/LineagePage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
For certain deployments the graph view can get unreadable when it displays nodes at too great a depth. The app hardcodes the table lineage graph depth to 5 currently. This PR makes that value configurable using the config-types pattern that the rest of the front end uses.
There is some discussion about the feature in a previous PR that I botched:
https://github.com/amundsen-io/amundsen/pull/2069
Added a unit test for the function that gets the default graph depth
- All the public functions and the classes in the PR contain docstrings that explain what it …
=> feat: Make default depth configurable for table lineage graph view (commanded)

common/amundsen_common/models/dashboard.py, common/setup.py, requirements-common.txt
Changed dashboard summary model in comment to use `last_successful_run_timestamp: Optional[float] = None` since a value like `1668725028.424` is too large to be casted to an `int`
=> fix: int is too small for a unix timestamp

databuilder/databuilder/models/table_lineage.py, databuilder/example/scripts/sample_data_loader_mysql.py, databuilder/requirements.txt, databuilder/tests/unit/models/test_table_lineage.py, metadata/metadata_service/proxy/mysql_proxy.py, metadata/setup.py, metadata/tests/unit/proxy/test_mysql_proxy.py
The change is related to issue #2072. It is about supporting table/column lineage for mysql backend end to end.
- databuilder: updated table_lineage model for table/column lineage record iterator and the corresponding sample_data_loader_mysql.py
- metadata_service: updated mysql_proxy.py to add lineage related endpoint.
Added unit tests in both databuilder and metadata_service for lineage related change.
N/A
=> feat: support table/column lineage for mysql backend

docs/tutorials/how-to-use-amundsen-with-aws-neptune.md, metadata/metadata_service/config.py, metadata/metadata_service/proxy/neptune_proxy.py
Currently, when users deploy Amundsen with Neptune backend DB,  `NeptuneBulkLoaderApi` is instantiated with the default STS endpoint.
However, this might not work when users deploy the service in government cloud / regional cloud, and the default endpoint is disabled. This PR allows user to specify the STS endpoint in the metadata config file, if they wish to.
No tests added because it does not change any application behavior. It only creates an option for user to specify their STS endpoint upfront in the config file.
Added a line in `docs/tutorials/how-to-use-amundsen-with-aws-neptune.md` to explain that users can now specify STS endpoint.
- In case you are adding a dependency, check if the license complies with …
=> Fix: Enable neptune proxy custom sts endpoint

docs/tutorials/how-to-use-amundsen-with-aws-neptune.md
Signed-off-by: Jovi Loo <loojovi@u.nus.edu>
Added newline before bullet points. If there is no newline, bullet points will not get rendered properly. Image is an example (from my previous PR).
No test since there is only a change to documentation.
Irrelevant for this PR.
=> Fix: added newline so that bullet points can render properly

frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/docs/application_config.md
Adds a configuration option to allow for dynamic fetching of notices for different resources
Added configuration util tests
Updated docs
Related to the stretch goals on https://github.com/amundsen-io/rfcs/blob/master/rfcs/029-resource-notices.md
=> feat: adds dynamic notices flag on config

frontend/amundsen_application/static/js/pages/FeaturePage/index.tsx
Fixes erroneous rendering of bullet on Features page
Manually
Before:
After:
=> fix: rendering of bullet on the Features page

databuilder/databuilder/extractor/redshift_metadata_extractor.py, databuilder/tests/unit/extractor/test_redshift_metadata_extractor.py
Signed-off-by: Orion Delwaterman <delwaterman@gmail.com>
Fixes https://github.com/amundsen-io/amundsen/issues/1572
Changes the config of `RedshiftMetadataExtractor` `where_clause_suffix` to not require a user to include a `WHERE` statement in their sql partial. This follows the behavior of `PostgresMetadataExtractor`, and seems more consistent with the variable name `where_clause_suffix` by treating the partial as a _suffix_ to a where clause.
This will be a breaking change for anyone using redshift extractor (so probably will need a minor version bump). That being, IMHO, it's better to make the behavior follow expected patterns rather than ask users to hunt through source code to determine why their query is breaking (which happened to me). …
=> fix: #1572 - make where_clause_suffix an actual suffix

frontend/amundsen_application/static/js/components/Alert/alert.story.tsx, frontend/amundsen_application/static/js/components/Alert/index.tsx, frontend/amundsen_application/static/js/components/Alert/styles.scss, frontend/amundsen_application/static/js/components/StorySection/index.tsx
Tweaks UI alert notices spacing and colors
Manually
=> chore: tweaks notices icon color, storybook and spacing

frontend/amundsen_application/static/css/_buttons-default.scss, frontend/amundsen_application/static/css/_variables-default.scss, frontend/amundsen_application/static/js/features/NavBar/styles.scss
Thins out the Global Header
Fixes alignment on text links
Tweakes spacing
Better use of the vertical space
Manually and in the Storybook
N/A
=> feat: thins out the global header to gain vertical space

frontend/amundsen_application/static/js/pages/FeaturePage/constants.ts, frontend/amundsen_application/static/js/pages/FeaturePage/index.tsx
- Fix naming of sections
- Fix header spacing
- local dev environment
=> fix: clean up ML features page

metadata/metadata_service/proxy/neo4j_proxy.py, metadata/setup.py
Updating metadata GET APIs to use managed read transactions in the Neo4j proxy to provide retry capabilities.
We were having an issue with errors with our health check where our Neo4j instance was showing that our client connection was closing, so trying this out to see if it fixes the issue. In any case, it is the Neo4j recommended way of executing transactions.
- Ran the existing tests
- Started the service locally and hit multiple of the GET endpoints to verify that results were returned
N/A
=> fix: Use managed read transactions for queries in metadata service

search/search_service/proxy/es_proxy_v2.py, search/setup.py
=> fix: filters affected by mapping inheritance issue

frontend/amundsen_application/api/quality/v0.py, frontend/tests/unit/api/quality/__init__.py, frontend/tests/unit/api/quality/test_v0.py
- Adds a simple test for the quality/v0.py endpoint, to have some basic test coverage.
- Also updates the message returned when a quality checks client isn't configured to be more verbose and descriptive. Based on the analogous message in announcements/v0.py.
Test was similar to the one I wrote for the notice endpoint so seemed like an easy opportunity to improve test coverage.
Ran the new unit tests locally.
Didn't modify any documentation.
=> test: Add unit test for quality endpoint, improve message for not-implemented

.github/workflows/common_pull_request.yml, .github/workflows/databuilder_pull_request.yml, .github/workflows/deploy_release.yml, .github/workflows/frontend_pull_request.yml, .github/workflows/metadata_pull_request.yml, .github/workflows/search_pull_request.yml
Updates ubuntu version to 22.04 LTS for the github actions unit tests runner image.
Python unit tests being run through GitHub Actions were getting stuck, likely due to GitHub Actions planning to deprecate Ubuntu 18.04 (https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/). This PR replaces 18.04 with 22.04 LTS in the affected workflows.
The diff changing single quotes to double quotes was due to an auto formatter running locally, it's consistent with code style elsewhere in these yaml files.
I tested the ubuntu version upgrade by checking out an existing PR whose Python unit tests were stuck, making a new branch, updating the version there, pushing, and [creating a PR to trigger the …
=> chore - Update ubuntu version for python unit tests

frontend/amundsen_application/static/css/_buttons-default.scss, frontend/amundsen_application/static/css/_variables-default.scss, frontend/amundsen_application/static/js/components/AvatarLabel/index.spec.tsx, frontend/amundsen_application/static/js/components/AvatarLabel/index.tsx, frontend/amundsen_application/static/js/components/EditableText/constants.ts, frontend/amundsen_application/static/js/components/EditableText/index.spec.tsx, frontend/amundsen_application/static/js/components/EditableText/index.tsx, frontend/amundsen_application/static/js/features/ExpandableUniqueValues/index.tsx, frontend/amundsen_application/static/js/features/ExpandableUniqueValues/styles.scss, frontend/amundsen_application/static/js/features/NavBar/styles.scss, frontend/amundsen_application/static/js/pages/DashboardPage/styles.scss, frontend/amundsen_application/static/js/pages/ProfilePage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/RequestDescriptionText/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/WatermarkLabel/index.tsx
Adds logging on EditableText
Tweaks spacing on btn-link
Cleans up ESLint issues and tests
Deprecates use of 'body-2' class
Increasing instrumentation on the UI
Manually
=> chore: event logging in EditableText component

frontend/amundsen_application/static/js/components/OwnerEditor/constants.ts, frontend/amundsen_application/static/js/components/OwnerEditor/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/FeatureListItem/index.spec.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.spec.tsx, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/ducks/search/filters/reducer.ts, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.spec.tsx, frontend/amundsen_application/static/js/features/MyBookmarks/index.spec.tsx, frontend/amundsen_application/static/js/features/Tags/index.spec.tsx, frontend/amundsen_application/static/js/pages/DashboardPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/ProfilePage/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/ResourceSelector/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/FrequentUsers/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/LineageLink/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/LineageList/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableHeaderBullets/index.spec.tsx, frontend/amundsen_application/static/js/utils/dateUtils.ts, frontend/amundsen_application/static/js/utils/index.spec.ts
Removes the last instances of code using the AppConfig directly
Improved tracking on the OwnerEditor
Fixes some ESLint issues
Last part of a long refactor to use util functions instead of the AppConfig file
Manually
Added tests
=> chore: removes direct access to AppConfig object

frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts
Total unit test coverage for config util methods
Improving test coverage
Running test coverage
=> chore: gets to total test coverage on config-utils methods

frontend/amundsen_application/static/js/components/Alert/Alert.tsx
We found that the width of the label column was somewhat too small. 
Manually. Ran locally with different values to inspect the visual difference. 
None
=> fix - Increase width in resource notice modal

frontend/amundsen_application/static/js/components/Alert/styles.scss
The vertical alignment was inconsistent between different elements inside the Alert component. This PR adjusts the margins to make the Alert look better and properly aligned.
How the Alert component looked before:
After:
Manually. Building locally with the change and visually inspecting. 
None
=> style – Adjust margin on elements inside the Alert component

frontend/amundsen_application/static/js/components/DefinitionList/index.tsx, frontend/amundsen_application/static/js/components/DefinitionList/styles.scss
When the text of an item in the notice modal is too long for its container, it looks better for it to truncate with an ellipsis rather than wrapping.
Manually.
=> style - Truncate long notice modal text with ellipsis

README.md
Removes roadmap link from docs, as it is outdated
=> docs: removes roadmap link from the readme

.github/CODEOWNERS
- Add Ozan and Ben as codeowners for databuilder so they can approve PRs in that area
=> chore: Add newer maintainers as codeowners for databuilder

databuilder/databuilder/extractor/snowflake_metadata_extractor.py, databuilder/databuilder/utils/hive_complex_type_parser.py, databuilder/databuilder/utils/trino_complex_type_parser.py, databuilder/requirements.txt, databuilder/setup.py
- Update databuilder to use `text-unidecode` instead of `unidecode` due to license incompatibility issues
- Unrelated to the main change, now also ignoring the `None` type passed to `pyparsing`'s `nestedExpr` function. In the docstring for this function, it specifically says `if no expressions are to be ignored, then pass ``None`` for this argument.` so the type definition for the function is incorrect and this is a workaround
This fixes license incompatibility issues, since Amundsen is licensed under Apache 2.0 and `unidecode` is GPL. See this issue for further context: https://github.com/amundsen-io/amundsen/issues/2148
Python tests pass
N/A
=> chore: Use text-unidecode instead of unidecode package to fix license incompatibility

frontend/amundsen_application/static/package-lock.json
Fixes issue with wrong npm package references
Solves #2141 
Built locally
=> fix: fixes wrong npm links

frontend/amundsen_application/static/package-lock.json
"Re-fixes" npm registry links after https://github.com/amundsen-io/amundsen/pull/2171 accidentally reverted the previous fix
Solves https://github.com/amundsen-io/amundsen/issues/2141
Built locally
=> fix: re-fix wrong npm links

metadata/metadata_service/proxy/neo4j_proxy.py, metadata/setup.py, metadata/tests/unit/proxy/test_neo4j_proxy.py
For some users of Amundsen, it may prove helpful to customize logic for deciding who a table's "owners" are. This can be accomplished by breaking up the table metadata API's query to make a modular query for only the owners (as is already done when getting table readers, in `Neo4jProxy._exec_usage_query`).
The results of the new `Neo4jProxy._exec_owners_query` are then combined back into the return value of the `Neo4jProxy.get_table method`, preventing any disruption to the JSON shape expected by the frontend. 
This solves the problem of companies that use Neo4j-based Amundsen being unable to customize what data is returned as a table's owners. For example if a company wanted to apply a custom sorting logic to multiple owners, or impute table ownership based on specialized business logic. …
=> Refactor Neo4jProxy table owners query for easier customization

databuilder/databuilder/models/badge.py, databuilder/tests/unit/models/test_badge.py
This PR creates a rds table_badge association record when creating a record iterator.
Currently while creating a badge record a table_badge association record is not created. This only adds badges in the 'badge' table in MySql and hence the badges are not visible for each table on the UI when using csvTableBadgeExtractor
https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/extractor/csv_extractor.py#L80.
Tested changes using csvTableBadgeExtractor and sample table and badge csv files.
=> Fix: Add rds badge association records

search/search_service/proxy/es_proxy_v2_1.py, search/setup.py
This pull request handles an edge case with basic search. If more than one `resource_types` is configured for amundsen (e.g Tables and Dashboards) and one of them have missing indices (i.e. no data got ingested for either of them in an initial run), it will crash the basic search from working for all `resource_types`. In a clean deployment (blank neo4j and elasticsearch), it is possible to not have data for all configured resource types at once. In such a case the search should not return any results for the resource_type with missing data instead of crashing basic search altogether. This PR addresses this problem and ensures that we trigger an elasticsearch "search" against only those `resource_types` which have a corresponding index/alias present in the elasticsearch database.
For a …
=> Fix - Adds a guard clause to prevent crashing in case of missing es indices

search/search_service/proxy/es_proxy_v2_1.py, search/setup.py
This pull request handles an edge case with basic search. If more than one `resource_types` is configured for amundsen (e.g Tables and Dashboards) and one of them have missing indices (i.e. no data got ingested for either of them in an initial run), it will crash the basic search from working for all `resource_types`. In a clean deployment (blank neo4j and elasticsearch), it is possible to not have data for all configured resource types at once. In such a case the search should not return any results for the resource_type with missing data instead of crashing basic search altogether. This PR addresses this problem and ensures that we trigger an elasticsearch "search" against only those `resource_types` which have a corresponding index/alias present in the elasticsearch database.
For a …
=> Fix - Handle ES missing index edge case (bug fix)

databuilder/databuilder/extractor/sql_alchemy_extractor.py, databuilder/setup.py
feat: Make sqlalchemy_extractor compatible with sqlalchemy>=1.4
(Moved from  #2209)
These changes to the `sql_alchemy_extractor` module allow for using the extractors with updated versions of `sqlalchemy`.
This addresses issues such as
* #2108 which require the `text` function to be used to wrap queries in `SQLAlchemy>=2.0`
* Posts on the Slack channel such as [this](https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1698249835872919) and [this](https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1699242309714869) which require the change to explicitly map the `Row` objects to dicts for `SQLAlchemy>=1.4`
Tested using `sampple_mssql_metadata.py` script for
* `SQLAlchemy==1.3.16`
* `SQLAlchemy==2.0.23`
None
=> [ADD] Make sqlalchemy_extractor compatible with sqlalchemy>=1.4

frontend/amundsen_application/static/js/pages/FeaturePage/index.tsx
There was a bug on the feature page where lineage was retrieved even when not enabled, throwing an error when there was nothing available at the endpoint.
Fixes errors when feature lineage is not enabled
Ran the code locally and saw the feature lineage API was no longer being called after the change
N/A
=> fix: Do not attempt to retrieve feature lineage when it is not enabled

metadata/metadata_service/proxy/gremlin_proxy.py
Implemented method `get_resources_using_table` in gremlin_proxy.py.
This method is a gremlin implementation of the similar [method found in neo4j_proxy.py line 1892](https://github.com/amundsen-io/amundsen/blob/main/metadata/metadata_service/proxy/neo4j_proxy.py#L1892).
The method retrieves the list of dashboards that are using a specific table, in the form of [DashboardSummary](https://github.com/amundsen-io/amundsen/blob/main/common/amundsen_common/models/dashboard.py#L11) objects.
This function was not implemented for Gremlin (for users using AWS Neptune instead of neo4j).
Currently, there are [no existing unit tests](https://github.com/amundsen-io/amundsen/tree/main/metadata/tests/unit/proxy) for gremlin proxy. But this new function has been tested internally with our Neptune server. …
=> chore: Add method get_resources_using_table to metadata gremlin_proxy

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/.betterer.ts, frontend/amundsen_application/static/js/components/Alert/Alert.tsx, frontend/amundsen_application/static/js/components/Alert/AlertList.tsx, frontend/amundsen_application/static/js/components/Alert/alert.story.tsx, frontend/amundsen_application/static/js/components/Alert/styles.scss, frontend/amundsen_application/static/js/components/DefinitionList/definitionList.story.tsx, frontend/amundsen_application/static/js/components/DefinitionList/index.spec.tsx, frontend/amundsen_application/static/js/components/DefinitionList/index.tsx, frontend/amundsen_application/static/js/components/DefinitionList/styles.scss, frontend/amundsen_application/static/package.json
Aggregates alert notices that are passed into the AlertList component and then parses them in the DefinitionList.
The UI is cluttered when there are numerous alerts taking up space, especially when many of them have the same title. Aggregating them into one modal alleviates this and reduces the visual strain on the user.
- Utilizing mock data to recreate the notices that can be aggregated as well as without aggregation.
- Unit testing through already existing tests in place
- Verification and updates to storybook and related components
=> feat: Aggregating Alerts Feature

common/setup.py, databuilder/setup.py, frontend/setup.py, frontend/tests/unit/api/issue/test_issue.py, frontend/tests/unit/api/preview/test_v0.py, metadata/setup.py, metadata/tests/unit/api/column/test_column_badge_api.py, metadata/tests/unit/api/dashboard/test_dashboard_badge_api.py, metadata/tests/unit/api/dashboard/test_dashboard_tag_api.py, metadata/tests/unit/api/feature/test_feature_badge_api.py, metadata/tests/unit/api/feature/test_feature_lineage_api.py, metadata/tests/unit/api/feature/test_feature_tag_api.py, metadata/tests/unit/api/table/test_table_badge_api.py, metadata/tests/unit/api/table/test_table_lineage_api.py, metadata/tests/unit/api/table/test_table_tag_api.py, requirements-common.txt, search/setup.py, search/tests/unit/api/dashboard/test_search_dashboard_api.py, search/tests/unit/api/feature/test_search_feature_api.py, search/tests/unit/api/table/test_search_table_api.py
- Upgrading flask version to 2.2.5, along with some related dependencies.
- With the later version of werkzeug, I had to update tests that used API calls to pass `json` instead of `data` (or instead of nothing) as a param to indicate the expected content type. See [release notes](https://github.com/pallets/werkzeug/blob/817aac4d2c71b83752e451d23f96ac26cfd7bbcd/CHANGES.rst#L146) from version 2.3.0.
We need to upgrade flask due to py3.10 version requirements. This change will also resolve some security dependencies in the project.
Ran our frontend, metadata, and search services locally to ensure there were no issues.
N/A
=> chore: Upgrade flask to 2.2.5 and its related dependencies

frontend/amundsen_application/api/utils/metadata_utils.py
A change I made in the mypy upgrade broke when the field did not exist on the object. Small fix to resolve the problem.
Ran frontend service locally to confirm it is working with the update
=> fix: Small fix from mypy change when attribute is missing

frontend/amundsen_application/base/examples/example_announcement_client.py, frontend/requirements.txt
Upgrading sqlalchemy in frontend service to latest 1.x.x version
Match version of the package we use internally
Ran the tests and ran frontend service locally
=> chore: Upgrade sqlalchemy in frontend to latest 1.x.x version

databuilder/databuilder/extractor/neo4j_extractor.py, databuilder/setup.py
- Adding the ability to configure the neo4j extractor to use [implicit transactions](https://neo4j.com/docs/python-manual/current/query-advanced/#implicit-transactions). The default behavior of the extractor will remain the same.
- Most cases can continue to use the default explicit transactions, but implicit transactions are required for `CALL {} IN TRANSACTIONS` [subqueries](https://neo4j.com/docs/cypher-manual/current/subqueries/subqueries-in-transactions/). Using this can help improve performance for queries that use too much memory, for example when a `Neo.ClientError.General.TransactionOutOfMemoryError` exception is thrown this can help break up the query.
- Also adding `default_access_mode=neo4j.READ_ACCESS` to the session configuration for all queries for better performance.
Ran …
=> feat: Add config for implicit transactions to neo4j extractor

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/css/_layouts.scss, frontend/amundsen_application/static/js/features/Tags/TagInfo/index.tsx, frontend/amundsen_application/static/js/features/Tags/TagInfo/styles.scss, frontend/amundsen_application/static/js/features/Tags/TagInput/index.tsx
We found that there were some visual inconsistencies when dealing with long tag names. Handled the overflow with the layout and set `max-width` for the button to utilize the default overflow handling. Added titles to allow for accessibility.
To provide a better user experience.
Locally with mock data to force long tag names
=> fix: Adjusting Tag display to handle long tag names

frontend/amundsen_application/static/js/components/OwnerEditor/index.spec.tsx, frontend/amundsen_application/static/js/components/OwnerEditor/index.tsx
Prior PR didn't handle the case of having owner categories configured, but also having some owners without any categories.
Added unit tests for key cases, tested in our staging environment.
=> fix -- handle uncategorized owners

databuilder/databuilder/extractor/atlas_search_data_extractor.py, databuilder/databuilder/extractor/mysql_search_data_extractor.py, databuilder/databuilder/extractor/neo4j_search_data_extractor.py, databuilder/databuilder/extractor/neptune_search_data_extractor.py, databuilder/databuilder/models/user_elasticsearch_document.py, databuilder/setup.py, databuilder/tests/unit/extractor/test_mysql_search_data_extractor.py, databuilder/tests/unit/models/test_user_elasticsearch_document.py
Changes the search data databuilder extractors to extract a `name` field, for publishing to elasticsearch.
Currently, the user document schema in elasticsearch expects a `name` keyword, which is the primary field for searching users. (Expected from [Databuilder publish](https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/task/search/document_mappings.py#L262), and expected from [search service](https://github.com/amundsen-io/amundsen/blob/main/search/search_service/proxy/es_proxy_v2_1.py#L82))
The change is required because currently the elasticsearch query does not use the `name` field to create better matches for search results, and instead is likely just using first/last and key of the user. This is fine when searching for just first or last, but when searching …
=> fix: Change databuilder search data extractors to publish `name` in user document.

metadata/metadata_service/proxy/neo4j_proxy.py, metadata/tests/unit/proxy/test_neo4j_proxy.py
Updated neo4j proxy to return None instead of the empty string when a dashboard's last run timestamp is the empty string.
Case can arise where empty string for the timestamp causes serialization errors.
Added additional unit test.
=> Fix -- handle empty string dashboard run timestamps

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/css/_layouts.scss, frontend/amundsen_application/static/js/components/Table/styles.scss, frontend/amundsen_application/static/js/components/TabsComponent/styles.scss, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/styles.scss
- `css/_layouts.scss` - Removed the min-heights and instead let it utilize the height of its container, which wont force it past acceptable limits
- `Table/styles.scss` - increased `min-width` to 100% to fill the container, set the header widths to auto and removed the top margin
- `TabsComponent/styles.scss` - Set the height to 100%, utilizing flex to allow the contents to grow but not overflow. Limited the overflow scrolling to the inner table versus the entire container
- `TableDetailPage/styles.scss` - Switched from fixed to absolute positioning so it would stop overflowing, removed the background and adjusted the positioning at smaller sizes so it wouldn't overlap
- `TableDetailPage/index.tsx` - Removed the visibility handlers that hid the Collapse all functionality and instead …
=> fix: Adjustments to tabs components to prevent overflows

common/setup.py, databuilder/setup.py, frontend/setup.py, metadata/setup.py, search/setup.py
Adds [PyPI project classifiers](https://pypi.org/classifiers/) to explicitly declare the software license.
Classifiers are used to add information to the classifiers panel in PyPI. Example from [NumPy](https://pypi.org/project/numpy/):
The reason that it is very important for this information to be present is that in an enterprise environment, security tools like [Sonatype Nexus IQ](https://help.sonatype.com/iqserver) are used to manage open source software risk. Nexus IQ specifically can be configured to [classify packages according to their license](https://help.sonatype.com/iqserver/managing/policy-management/license-threat-groups). This prevents developers from inadvertently using licenses like [GNU General Public License v2.0](https://www.tldrlegal.com/license/gnu-general-public-licen …
=> chore: explicitly declare license with classifier

frontend/amundsen_application/api/log/v0.py, frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/components/ResourceListItem/DashboardListItem/index.spec.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/DashboardListItem/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/FeatureListItem/index.spec.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/FeatureListItem/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.spec.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/UserListItem/index.spec.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/UserListItem/index.tsx, frontend/amundsen_application/static/js/ducks/log/api/v0.ts, frontend/amundsen_application/static/js/ducks/log/index.spec.ts, frontend/amundsen_application/static/js/ducks/log/reducer.ts, frontend/amundsen_application/static/js/ducks/log/sagas.ts, frontend/amundsen_application/static/js/ducks/log/types.ts, frontend/amundsen_application/static/js/ducks/rootSaga.ts, frontend/amundsen_application/static/js/ducks/search/reducer.spec.ts, frontend/amundsen_application/static/js/ducks/search/reducer.ts, frontend/amundsen_application/static/js/ducks/search/utils.ts, frontend/amundsen_application/static/js/features/SearchBar/InlineSearchResults/ResultItemList/index.tsx, frontend/amundsen_application/static/js/features/SearchBar/InlineSearchResults/ResultItemList/tests/index.spec.tsx
feat: Enhance logs generated for search result click events.
This PR modifies the click events trigger by selecting search items. 
In particular, the following fields are present:
* `search_term` - The text user entered to retrieve these results
* `search_page_index` - 0 index of what page this result was retrieved from (0 for inline)
* `resource_href` - The link this resource item is taking the user to
* `resource_type` - One of `ResourceType`
* `search_results` - List of identifying keys for the current page of search results.
To provide more useful context for analysing user activity related to search.
Built amundsen + frontend locally, searched on dummy data and checked the network tab to see the `log_event`s being correctly fired.
None added
=> feat: Enhance search logging
