amundsen-io/amundsen

.github/PULL_REQUEST_TEMPLATE.md, .gitmodules, README.md, docker-amundsen.yml, docs/authentication/oidc.md, docs/installation.md
This PR configures the git submodules for our child repositories, adds a small PR template for some consistency with other repos, and updates the common documentation that was modified in amundsenfrontendlibrary over the past week.
Updates the common documentation that was modified in amundsenfrontendlibrary over the past week.
=> Configure submodules to child repos

.gitmodules
Updating the submodules to track master
N/A
=> Update submodules to track master

README.md, docker-amundsen-atlas.yml, docker-amundsen.yml
Updating documentation to capture recent changes in https://github.com/lyft/amundsenfrontendlibrary
Updating documentation to capture recent changes in https://github.com/lyft/amundsenfrontendlibrary
=> Updating some doc to keep in sync with temp doc in amundsenfrontendlibary

docs/installation.md
Update the installation documentation. It was copy pasted from `amundsenfrontendlibrary` and needed some changes to be correct in this repo, where users will have to `cd` into submodules.
docs/installation.md
=> Updated installation instructions

docker-amundsen-atlas.yml
setup environment variables such that amundsensearch searches on atlas
=> Configure search for docker-amundsen-atlas

docs/installation-aws-ecs/aws-ecs-deployment.md, docs/installation-aws-ecs/docker-ecs-amundsen.yml, docs/installation-aws-ecs/ecs-params.yml, docs/installation-aws-ecs/userData.sh
Weekly doc sync until we complete our umbrella repo. 
Copying documentation added by @joaolcorreia in https://github.com/lyft/amundsenfrontendlibrary/pull/224/files + fixed a typo.
=> Migrate doc for using aws esc

docker-amundsen-local.yml, docs/developer_guide.md
Addresses https://github.com/lyft/amundsen/issues/18.
This PR adds some documentation and a new `.yml` file for local development. At the moment, the local workflow we can support leverages using Docker to spin up all the necessary containers, just like in the installation. Some key pieces of information:
1. We needed a new `.yml` file that will build using the content in the local submodules, as opposed to an official tag. 
2. I ran into some issues building `amundsenfrontendlibrary` with the `public.Dockerfile`, and created a separate `local.Dockerfile`. More details in https://github.com/lyft/amundsenfrontendlibrary/pull/246 for why this was needed.
There's a lot of room for improvement, specifically surrounding the fact that rebuilding local changes in …
=> Add developer guide

README.md
Add another podcast.
_What documentation did you add or modify and why? Add any relevant links then remove this line_
=> Update readme with another podcast

docs/roadmap.md
I think it’s useful to be able to place deep links to items on the roadmap like https://github.com/jornh/amundsen/blob/patch-2/docs/roadmap.md#native-lineage-integration
Sadly enough it’s a bit less visually pleasing as `<br>`s are not respected in headings - but I still think the benefit outweighs that.
*Also, more as a point for discussion:* How about we add links to issues to start capturing discussion/design and work coordination of some of the roadmap items? It would allow to gradually break down features into smaller “bite size” parts that people in the community might pick up and start implementing. The idea is basically to funnel people from seeing and wanting a feature to actually being able to more easily be able to start contribute (or am I just overthinking all this? 😜)
Cc: …
=> Linkify Roadmap.md

README.md
Remitly data engineering has released Amundsen to our users, and we're now official!
=> add Remitly to README

.gitmodules
Added `amundsencommon` as submodule
N/A
=> Add amundsencommon submodule

README.md
Adding community meeting section to README
main README.txt
- [x ] PR title addresses the issue accurately and concisely.
- [ x] PR includes a summary of changes.
- [ x] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
=> Adding community meeting section to README

docker-amundsen.yml
* Fix for #82 unable to favorite by using test user. This allows Quickstart to demo the favorite ⭐️  feature by "clever misuse" of an existing test class without any additional need for configuring anything
* bump docker images to latest available on Docker hub
no doc changes
=> compose unable to fave fix

docs/architecture.md
Yes!
Mainly triggered by that I wanted to be able to deeplink to Neo4j/metadata model from #107 
=> Architecture.md Enable deep links - point to Swagger etc.

README.md, docs/architecture.md
_Include a summary of changes then remove this line_
_What documentation did you add or modify and why? Add any relevant links then remove this line_
=> Fix: actually put in the Swagger link and generally deep link :chain: all the things 

amundseninfrastructure/README.md, amundseninfrastructure/templates/helm/amundsen/Chart.yaml, amundseninfrastructure/templates/helm/amundsen/templates/deployment.yaml, amundseninfrastructure/templates/helm/amundsen/templates/service.yaml, amundseninfrastructure/templates/helm/elasticsearch/Chart.yaml, amundseninfrastructure/templates/helm/elasticsearch/templates/deployment.yaml, amundseninfrastructure/templates/helm/elasticsearch/templates/service.yaml, amundseninfrastructure/templates/helm/neo4j/Chart.yaml, amundseninfrastructure/templates/helm/neo4j/templates/configmap.yaml, amundseninfrastructure/templates/helm/neo4j/templates/deployment.yaml, amundseninfrastructure/templates/helm/neo4j/templates/service.yaml
_Include a summary of changes then remove this line_
_What documentation did you add or modify and why? Add any relevant links then remove this line_
=> issue 53; k8s + helm setup for amundsen

docs/roadmap.md
Add Amundsen Slack Channel Link in roadmap.md
- [ Y] PR title addresses the issue accurately and concisely.
- [ Y] PR includes a summary of changes.
- [ Y] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
=> Add Slack Channel Link in roadmap.md

.github/PULL_REQUEST_TEMPLATE.md, .gitignore, docker-amundsen.yml
Closes #109 ... aka the finishing touches towards that issue
On top of that a bit of doc-bopping chores here and there
**Note**: ~~Blocked by https://github.com/lyft/amundsenfrontendlibrary/pull/300 (we need the Gunicorn in the upcoming [`v1.1.0`](https://github.com/lyft/amundsenfrontendlibrary/pulls?utf8=%E2%9C%93&q=+sort%3Aupdated-desc+label%3A1.1.0+))~~ merged!
Documented a bit directly in `docker-amundsen.yml` as a followup to PR #97.
=> productionize docker-compose a bit more

README.md
=> Add the latest post

README.md
Update README.md to include Supported Connectors
=> Update README.md to include Supported Connectors

README.md
Added a conference to the README (IDEAS SoCal Data & AI)
=> Added a new conference talk to readme

README.md
https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1572979701291200?thread_ts=1561012353.146600&cid=CGFBVT23V
=> Add Edmunds to readme

README.md
=> add latest meeting note

amundsen-kube-helm/templates/helm/amundsen/templates/deployment.yaml
=> ISSUE 177 - updated deployment, to allow for full image paths

amundsen-kube-helm/README.md
=> Change heading to Amundsen k8s Helm Charts

docker-amundsen-atlas.yml, docs/installation.md
This PR updates the docker-compose-atlas.yml to have the latest version of amundsen services and the atlas itself. It also makes sure to install the sample data in Atlas and make that data ready for Amundsen out of the box. 
Updates the installation documents to make sure to have the correct steps to install amundsen with atlas.
=> Updates docker-compose-atlas to use latest atlas and sample data

README.md
=> feat: Update readme to include merlinjobs.com

README.md
=> Include Cimpress in list of companies

docs/installation.md
Updated the troubleshooting section with an item on how to deal with a `Failed to create node environment` error from Elasticsearch.
=> Documenting fix StartupException with local data persistence

README.md
=> Updated README to indicate supported Node versions

README.md
Adding iRobot to users list
N/A
=> [README] Adding iRobot to users list

amundsen-kube-helm/templates/helm/amundsen/templates/deployment.yaml, amundsen-kube-helm/templates/helm/amundsen/templates/oidc_config.yaml, amundsen-kube-helm/templates/helm/amundsen/values.yaml
Adds a flag for turning OIDC on and off and a flag to create the required secret.
Documentation is in comments.
=> Adding oidc to the helm chart

docker-amundsen-atlas.yml, docker-amundsen-local.yml, docker-amundsen.yml
Change ports to 5001, 5002 for search, metadatalibrary. Related to https://github.com/lyft/amundsenmetadatalibrary/pull/102 and https://github.com/lyft/amundsensearchlibrary/pull/80
None
=> change default ports to 5001,5002 for search, library

README.md
=> Upload latest meeting note

README.md
Adds slides and video link for my talk at BigData Vilnius.
=> Add slides/video for talks section BDVilnius

README.md
Change the wording for the user sections. Example: https://github.com/apache/incubator-superset#who-uses-apache-superset-incubating
=> Update the user section

amundsen-kube-helm/templates/helm/amundsen/templates/deployment.yaml
Added frontend_base env variable if it is set for k8s.
=> Adding frontend base environment variable if it is set.

README.md
Sync up with frontend readme in https://github.com/lyft/amundsenfrontendlibrary/pull/388
Last time I checked in I merged/stale WIP https://github.com/lyft/amundsensearchlibrary/pull/67#issuecomment-542869743 some tests didn’t run with Python 3.8. 
Yes! README update only
=> Python README version bump

amundsen-kube-helm/templates/helm/amundsen/templates/service.yaml
Bug fix in the kube-helm chart for metadata service port
None
=> Fixing kube helm metadata and search service port

README.md, docs/faq.md
=> Update READ.md adding service version guide

docker-amundsen.yml
Should match databuilder 2.0.x
See https://github.com/lyft/amundsen/blob/master/docs/faq.md#amundsen-1x---2x-migration-guide
=> Bump containers to 2.0.x

docs/installation.md
For context see https://github.com/lyft/amundsen/issues/311#issuecomment-593605986 and various Slack threads.
yep! Troubleshooting in quickstart
=> Add some troubleshooting hints

docker-amundsen.yml, docs/roadmap.md
Updated the quickstart to use the latest frontend and search library releases & updated the roadmap to reflect completed and in progress projects.
Updated the quickstart to use the latest frontend and search library releases & updated the roadmap to reflect completed and in progress projects.
=> Updare docker; Update roadmap

README.md
Include Verdan's talk in readme
=> Add Verdan's talk to readme

docs/architecture.md
=> Follow on fix to #355 in architecture.md

docs/installation.md
=> Troubleshooting improve layout and wording

README.md
Add a few articles on media coverage related to the project.
=> Add few articles on media coverage

README.md
=> Add two articles

amundsen-kube-helm/README.md
fix #372 kube-helm README. adjustments for helm3
=> fix #372 kube-helm README adjustments for helm3

README.md
=> Add a new badge

amundsen-kube-helm/README.md
=> Change the title to upper case

amundsen-kube-helm/README.md
=> Change readme from K8S to K8s

amundsen-kube-helm/templates/restore-backup/README.md, amundsen-kube-helm/templates/restore-backup/restore-neo4j-pod.yaml
* Added one-off pod for restoring neo4j backup from S3
* Added documentation with steps for running one-off pod
=> add one-off pod and documentation for restoring neo4j backup

README.md
=> Add doc site to readme

docker-amundsen-local.yml
docker-amundsen-local.yml, updated search service and metadata service ports for frontend service.
=> port correction for meta and search service

README.md
Add Devoted to Who uses Amundsen?
=> Add Devoted to README

README.md
=> Add a few related posts for Amundsen

README.md
=> Change logo format

README.md
=> Further center align logo

README.md
It never really got off the ground:
Also fix a link after logo was introduced instead of #Amundsen heading
=> Retire mailing list

docs/faq.md
Based on https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1587127310046500
=> Add an entry to faq

docs/developer_guide.md
Documentation about search service local testing that is consist of:
1. Standing up local Elasticsearch via Docker
2. (Optional) Standing up local Kibana via Docker
3. Publish staging data into local Elasticsearch
4. Launch search service
Documentation about search service local testing
=> Add documentation on search service local testing

docs/tutorials/data-preview-with-superset.md, docs/tutorials/index-postgres.md
=> Fix a few link references

README.md
=> Remove databuilder py27 note

README.md
Adds a blog post I wrote, in the related posts sections
The blog post covers Metadata hubs in general and Amundsen
I asked @feng-tao on Slack if it was relevant and where I could share it, so thank you for the initial review!
This is a friends link, so readers won't be stopped by the Medium paywall
=> Add "A Data Engineer's Perspective On Data Democratization"

README.md
Updating README with notes/info about community meetings
=> Updating README with notes/info about community meetings

README.md
Also replaced video with recording - but that may be just my personal preference.
=> Updating community meeting section

README.md
=> Change wording

README.md, mkdocs.yml
=> Update readme about dashboard

deploy_website.sh, mkdocs.yml
Adding Dashboard ingestion guide to github page
N/A
=> Adding Dashboard ingestion guide to github page

README.md
=> add a new doc on Amundsen

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
Adds Contributing document with instructions about how to get started contributing to Amundsen
Adds a bug and feature request templates
=> Adds Contributing document, bug and feature request templates

docs/faq.md
Prerequisites for running Amundsen with Atlas.
=> Documentation of Atlas integration prerequisites

README.md
The markdown in mkdocs has incorrect format (https://lyft.github.io/amundsen/) on certain sections. Fix them for now.
=> Fix readme doc layout

README.md
add a doc that covers Amundsen
=> add a doc that covers Amundsen

README.md
Add link for the integrations. also add a new section on etl integration support
=> Update readme with link for references

docs/roadmap.md
Update roadmap doc for dashboard
=> Update roadmap doc for dashboard

README.md
=> chore: remove duplicate article

.github/prlint.json
Add prlint rule. Starts with simple pr title check.
Other available rules could be found in https://github.com/apps/prlint
This is for https://github.com/lyft/amundsen/issues/459.
=> chore: add prlint rule

README.md
README.md additions to link to the contributing guide from the `PRs welcome` button and text further down.
Yep!
=> docs: Increase CONTRIBUTING.md visibility

README.md
add https://datastrategy.substack.com/p/in-house-data-discovery-platforms
=> docs: add one external doc about Amundsen

README.md
=> docs: add one doc that covers Amundsen

README.md
add @samshuster 's post (https://technology.edmunds.com/2020/05/27/Adding-Data-Quality-into-Amundsen-with-Programmatic-Descriptions/) .
=> docs: add data quality post from Sam

docs/CONTRIBUTING.md, mkdocs.yml
Add contributing doc. Test the doc rendering correctly locally
=> chore: Add contributing to docs

README.md
Add coles as Amundsen user based on https://www.itnews.com.au/news/coles-group-chases-retail-insights-with-data-platform-overhaul-548356 and https://i.nextmedia.com.au/News/Coles_EDP_architecture.png
=> chore: add coles as Amundsen user

README.md
=> docs: add a doc about Amundsen

docker-amundsen-atlas.yml
This MR updates sample docker-compose deployment for Amundsen & Atlas.
Updated docker-compose-atlas.yml with latest Atlas & Amundsen versions.
=> Update Amundsen & Atlas docker setup

README.md
Add https://towardsdatascience.com/how-to-find-and-organize-your-data-from-the-command-line-852a4042b2be to related article
=> docs: add metaframe doc

README.md
update the community meeting note.
=> docs: update community meeting notes with recording

README.md
Added link to article on using Amundsen in ING WBAA 
=> docs: Add article about using Amundsen in ING

README.md
=> docs: Updating date of next community meeting

docs/roadmap.md
the roadmap is created a year ago by a ex team mate. Update it to be more up to date. Here are a few changes:
- Dashboard is finished.
- Druid index is finished.
- Remove a few items that we no longer do.
- Provide context on trust in data initiative at Lyft as well as Lineage integration.
=> docs: update roadmap

README.md
=> docs: Update wording

README.md
Added Redash to list of dashboard connectors, following https://github.com/lyft/amundsendatabuilder/pull/300 and https://github.com/lyft/amundsenfrontendlibrary/pull/501#issuecomment-653249176.
README.md
=> docs: Add Redash to list of dashboard connectors

README.md
=> docs: add two talks from Airflow summit

README.md
Added Asana to the list of companies officially using Amundsen.
README.md
=> docs: Add Asana to list of Amundsen users

README.md
Based on https://medium.com/bagelcode/data-discovery-platform-at-bagelcode-b58a622d17fd post which is written in Korean, bagelcode is an Amundsen user as well.
=> docs: add bagelcode to Amundsen user

README.md
Quick PR to add the recently published Square blog post about Amundsen to the readme!
=> docs: Add Square blog post to readme

README.md
Add the home page to the repo as well.
=> docs: add homepage

README.md
Add a badge for twitter Amundsen account
=> chore: add a badge for twitter

README.md
Add Dcard as user (https://www.dcard.tw/f) based on https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1595571650198500
=> chore: add Dcard as user

docs/installation.md
Updated installation guide to clarify the need for creating a virtual env in addition to having a docker image that runs Amundsen service. It was not clear that the virtual env and installing dependencies was only required for the sample data loader script we provide.
=> docs: Update installation document to clarify sample data ingestion process

README.md
Update with notes from last meeting & date for next
N/A
=> docs: Update with notes from last meeting & date for next

docker-amundsen-atlas.yml
Fix an issue with using https instead of http for docker-compose based installation of Amundsen with Atlas.
=> fix: Wrong protocol in docker-amudnsen-atlas.yml

README.md
Updating README with a description to be consistent with other blog posts (like this one: https://eng.lyft.com/amundsen-lyfts-data-discovery-metadata-engine-62d27254fbb9)
=> docs: Update README.md to have a consistent description of the project

README.md
=> docs: add LFAI announcement

README.md
=> docs: update doc site

README.md
=> chore: add lfai to readme

OWNERS.md
=> docs: Add owners file

CONTRIBUTING.md, GOVERNANCE.md, README.md, amundsen-kube-helm/README.md, docs/architecture.md, docs/authentication/oidc.md, docs/developer_guide.md, docs/installation.md, docs/issue_labeling.md, docs/roadmap.md, mkdocs.yml
Towards completing https://github.com/amundsen-io/amundsen/issues/615
=> chore: replace links to lyft org with amundsen-io org

.gitmodules, amundsen-kube-helm/templates/helm/Chart.yaml, deploy_website.sh, docker-amundsen.yml, docs/tutorials/data-preview-with-superset.md, docs/tutorials/index-postgres.md
Correct and modify repo references
=> chore: clean and modify repo references

.github/workflows/deploy_docs.yml
Add a github action to publish our document. Confirm to be working using my local fork (https://feng-tao.github.io/amundsen/)
=> feat: add github action to publish doc

.github/workflows/deploy_docs.yml
Given we link the gitsubmodule docs in this central doc, we need to add another action to check out git submodule first. Otherwise the doc will be broken.
=> chore: add git submodule action

README.md
So we don't have to update readme every month with the new meeting date or old notes.
From here on, we simply update the Google doc: https://docs.google.com/document/d/1bsJWNt1GBFmV-aRbHFuYgMFnMgIIvAmbhsvDatb0Vis/edit#
Signed-off-by: Mark Grover <mark@apache.org>
README.md
- [x ] My commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
=> docs: Update README to be more concise

docs/roadmap.md
Adding a few more items to the roadmap that have been brought up recently.
roadmap.md
=> docs: Update roadmap.md

docs/tutorials/data-preview-with-superset.md
Fixed link guide for superset_preview_client.md
Fixed link guide for superset_preview_client.md
- [X ] PR title addresses the issue accurately and concisely, including a title prefix.
- [X ] PR includes a summary of changes.
=> docs: Update link for superset_preview_client.md on data-preview-with-superset.md

MAINTAINING.md
Adds a Maintaining document focused on the project's maintainers.
This document is supposed to be a guide for maintainers, and a great way to onboard people into the project.
=> docs: Draft for the Maintaining document

README.md
waiting for https://github.com/amundsen-io/amundsenfrontendlibrary/pull/616
=> doc: add tableau to readme

CODE_OF_CONDUCT.md
=> doc: update code of conduct

README.md
=> doc: add Gusto to the user list

README.md
Signed-off-by: mgorsk1 <gorskimariusz13@gmail.com>
Added 'Cataloging Tools for Data Teams' article mentioning Amundsen.
README.md - extenden list of `Related Articles`
=> docs: new article mentioning Amundsen (Cataloging Tools for Data Teams)

README.md
Added [DHI Group Inc](https://dhigroupinc.com/) as a user of Amundsen; preserved alphabetical order of users
Changed the README.md
=> docs: Add DHI Group as Amundsen user

docs/tutorials/how-to-track-user-metric.md
Add doc for https://github.com/amundsen-io/amundsen/issues/691
=> doc: add a doc on how to track user metric using action log

docs/faq.md, mkdocs.yml
based on several asks from the slack channel, put this in the faq doc.
=> doc: add a faq entry on create_only config

docs/tutorials/how-to-track-user-metric.md
the markdown is broken in https://www.amundsen.io/amundsen/tutorials/how-to-track-user-metric/. Not sure why valid markdown is broken in Mkdocs. But the following fix is working in my local env.
=> chore: fix markdown format for mkdoc page

README.md
Adds WeTransfer to `Who uses Amundsen?` in the README
As a side note, I'm sharing some of the things we did differently. Maybe helpful for some people.
- use Kuberenetes Ingress
- set up authentication with [OAuth Proxy](https://github.com/oauth2-proxy/oauth2-proxy)
- separate [config](https://github.com/amundsen-io/amundsendatabuilder/blob/71492a96066060cbc6395a3a9afdb6289f3ad491/example/dags/postgres_sample_dag.py#L87-L110) and application codes by using templated json (i.e .j2) for configuration and render values when passing them to Airflow tasks 
- use Factory Pattern so that developers with less experience in Amundsen can simply pass job, task, publisher, extractor, loader, transformer and prepare a j2 file.
```
runner = DataBuilderRunner(
job_type=dag_args.pop("job"), …
```
=> docs : add WeTransfer to 'Who uses Amundsen?'

docs/faq.md
Add in documentation for how to bypass adblockers for more accurate analytics
Section in https://github.com/amundsen-io/amundsen/blob/master/docs/faq.md for how to bypass content blockers to capture all analytics
=> docs: Add in documentation for how to bypass adblockers for more accurate analytics

README.md
Chatted with Yang and heard that Amundsen is now in production at Brex :) 
=> doc: add Brex as user

CONTRIBUTORS.md, README.md
Signed-off-by: Marcos Iglesias <miglesiasvalle@lyft.com>
Adds a page for the contributors of the project
Documentation change
=> docs: Adding Contributors page to fill with all-contributors bot

.all-contributorsrc.json, README.md
Signed-off-by: Marcos Iglesias <miglesiasvalle@lyft.com>
Updates all contributors configuration and links
=> chore: Configuring bot and updating links on Readme

.gitmodules, README.md
Add amundsen-gremlin submodule, docs
Mentioned what amundsen-gremlin is
=> feat: add amundsen gremlin

README.md
Summary of Changes
Add [Hurb](https://hurb.com) as a user of Amundsen
Documentation
Changed the [README.md](https://github.com/lyft/amundsen/blob/master/README.md)
CheckList
Make sure you have checked all steps below to ensure a timely review.
=> docs: add hurb to readme

.gitmodules
Per https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1601900774073200 , switching to https to match other submodules.
n/a, submodule change only
=> fix: update amundsengremlin submodule to use https

README.md
=> chore: add contributor badge

README.md
Add [Instacart](https://www.instacart.com/) as a user of Amundsen
Changed the [README.md](https://github.com/lyft/amundsen/blob/master/README.md)
=> docs: add Instacart to readme

.dependabot/config.yml
All the git submodule dependenbot prs should just be auto merged.
=> chore: auto merge git submodule update

docs/tutorials/how-to-track-user-metric.md
add a few sample query for user metric doc
=> doc: add a few sample query for user metric doc

docs/tutorials/how-to-search-effective.md
=> doc: add search tutorial

mkdocs.yml
=> chore: fix and update mkdoc file

docs/tutorials/how-to-search-effective.md
Edited for clarity on using general search.
Updated references in the documentation and clarified search behaviour per [conversation](https://github.com/amundsen-io/amundsen/pull/773#discussion_r509901772) with @feng-tao 
Search tutorial
=> docs: updates search tutorial

docker-amundsen.yml
=> chore: update version in docker script

README.md
Add delta lake to support connector as https://github.com/amundsen-io/amundsendatabuilder/pull/351 is merged
=> doc: Add delta lake support to readme

README.md
=> doc: add REA group to user

README.md
Starting to use Zoom instead of Google meet
Signed-off-by: Mark Grover <mark@apache.org>
Updating the community meetings to be Zoom
N/A
=> docs: Updating the community meetings to be Zoom

docker-amundsen.yml
update the service version in docker compose script
=> chore: update docker compose service version

README.md, SECURITY.md
This documents the new security vulnerability mailing list.
=> docs: add SECURITY.md, security reporting process

README.md
Change LFAI to LFAI & Data. Fix the broken image in readme
=> chore: update lfai logo

docker-amundsen.yml
=> chore: bump amundsen-frontend from 3.0.0 -> 3.1.0

README.md
=> chore: add a github badge for Amundsen

README.md
Signed-off-by: Alagappan <alagappan.als@gmail.com>
Remove contributors section from README as it is not accurate at the moment. 
=> Remove contributors section from README untill contribution bot is fixed

docs/authentication/oidc.md
I'm presuming this is a typo, `edmunds` vs `amundsen`.
I am still trying to set it all up so could be misunderstanding :-)
=> docs: Correct edmunds -> amundsen typo in OIDC readme

README.md
Signed-off-by: Lexi Santoro <lexisantoro1@gmail.com>
No code changed, just doc.  Closed previous PR attempts as I hadn't set up the github commit signing correctly, but I believe it is resolved now.
Add Convoy to the list of companies using Amundsen
=> doc: add convoy to the list

amundsen-kube-helm/templates/helm/templates/deployment-frontend.yaml
Update env name of oidc secret key of frontend
https://github.com/amundsen-io/amundsen/issues/857
=> fix: Update env name of oidc secret key in helm template

README.md
=> doc: add a post about Amundsen

README.md
Add [Plarium](https://plarium.com/) as a user of Amundsen
Changed the README.md
=> docs: Add Plarium to list of Amundsen users

README.md
Rename Plarium to Plarium Krasnodar. (user list)
changed README.md
=> docs: rename Plarium to Plarium Krasnodar

docs/authentication/oidc.md
=> doc: add a blog post for OIDC

README.md
=> doc: add a community post

README.md
Add company to user list
No code changes
=> other Add Company Lett Digital

.gitmodules, README.md
=> chore: add rds submodule

README.md
With @sangiri 's change (https://github.com/amundsen-io/amundsendatabuilder/pull/433), vertica is another supported connector for amundsen.
=> doc: add vertica as supported connector

README.md
=> doc: add a new blog from the community for feast and amundsen

README.md
Signed-off-by: Salil Kulkarni <salilk957@gmail.com>
Updated README.md to add Tile to the list of companies using Amundsen
=> docs: Added Tile to the list of companies officially using Amundsen

README.md
=> doc: add Databricks as Amundsen user

amundsen-kube-helm/README.md, amundsen-kube-helm/templates/helm/Chart.yaml, amundsen-kube-helm/templates/helm/templates/deployment-frontend.yaml, amundsen-kube-helm/templates/helm/templates/deployment-metadata.yaml, amundsen-kube-helm/templates/helm/templates/deployment-search.yaml, amundsen-kube-helm/templates/helm/values.yaml
Added imagePullSecrets option to Amundsen images to support pulling from a private repository. 
Added references and example for using imagePullSecrets to values.yaml
=> feat: Add imagePullSecrets to support amundsen private images

docs/tutorials/how-to-use-amundsen-with-aws-neptune.md, mkdocs.yml
Signed-off-by: Andrew Ciambrone <andrjc4@vt.edu>
Documentation for Neptune
=> docs: Tutorial for the Neptune Integration

docker-amundsen-local.yml
=> fix: use TestConfig for FE container

docker-amundsen.yml
This will fix https://github.com/amundsen-io/amundsen/issues/939
=> chore: bump amundsenmetadata to 3.3.0

docs/deployment-best-practices.md
Amundsen allows for many modifications, and many require code-level modifications. Until we put together a "paved path" suggestion on how to manage such a set-up, for now we will document what community members are doing independenly. If you have a production Amundsen deployment, please edit this doc to describe your setup.
=> docs: create start of best-practices doc

docker-amundsen-local.yml, docker-amundsen.yml, docs/installation-aws-ecs/docker-ecs-amundsen.yml, example/docker/neo4j/conf/neo4j.conf
This PR bumps the version of Neo4j specified in the relevant docker-compose files from 3.3 to 3.5. This change was initiated because an attempt to use modern Neo4j tooling (e.g. Neo4j Desktop Canary) to connect to a non-local Neo4j database running version 3.3 failed due to driver incompatibilities. Additionally, version 3.3 is [officially unsupported as of April 28, 2019](https://neo4j.com/developer/kb/neo4j-supported-versions/) (3.5 will be supported until November 28, 2021). Version 3.5 is a compatibility release which allows the newer v4 drivers to be used when connecting, so this resolves the aforementioned issue on modern tooling. Becuase it is a compat release, no Amundsen packages/code need to be changed for this upgrade. There were a few directory changes that needed to be made …
=> chore: Bump Neo4j version from 3.3 to 3.5

amundsen-kube-helm/templates/helm/templates/pv-neo4j.yaml, amundsen-kube-helm/templates/helm/values.yaml
Signed-off-by: benrifkind <ben.rifkind@gmail.com>
Allow the user to specify a subpath for the neo4j persistent volume.
I added the default value in the values.yaml file
=> feat: Add ability to specify subpath for neo4j persistent volume

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/components/ResourceListItem/DashboardListItem/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/UserListItem/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnLineage/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/LineageList/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
Fix lineage bugs
- Not loading upstream/downstream on page navigation
- "0" showing up when column lineage is missing
Tracking
- Add click tracking for table, dashboard, and user list item components
- Add upstream/downstream direction to lineage related events
=> fix: Lineage bug and tracking granularity

.gitignore
Signed-off-by: benrifkind <ben.rifkind@gmail.com>
Adds to the .gitignore so that Helm artifacts are not tracked. This is to avoid dirtying the working directory after running `helm update`. 
```
$> git status
Untracked files:
(use "git add <file>..." to include in what will be committed)
amundsen-kube-helm/templates/helm/charts/
amundsen-kube-helm/templates/helm/requirements.lock
```
=> chore:Ignore Helm artifacts

databuilder/README.md, databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_last_successful_executions_extractor.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_last_successful_executions_extractor.py
Update ModeDashboardLastSuccessfulExecutionExtractor to use Mode discovery api. Metadata can be extracted in one api endpoint call instead of using two endpoints (it used to be one for spaces and one for reports)
Test added.
ModeDashboardLastSuccessfulExecutionExtractor config example in README
=> perf: update ModeDashboardLastSuccessfulExecutionExtractor to discovery api

databuilder/README.md, databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_queries_extractor.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_queries_extractor.py
Update ModeDashboardQueryExtractor to use Mode discovery api. Test added.
ModeDashboardQueryExtractor config example in README
=> perf: update ModeDashboardQueryExtractor to discovery api

databuilder/setup.py
fix a typo in databuilder setup.py file
=> chore: fix databuilder dep typo

databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_last_modified_timestamp_extractor.py
Update return type of _build_restapi_query method in ModeDashboardLastModifiedTimestampExtractor
=> chore: Update ModeDashboardLastModifiedTimestampExtractor typing

databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_last_modified_timestamp_extractor.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_last_successful_executions_extractor.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_owner_extractor.py
Update some Mode dashboard extractor tests which will be more like an end-to-end test and increase test coverage a little bit
As summary says
=> test: update Mode dashboard extractor tests

databuilder/README.md, databuilder/databuilder/extractor/dashboard/mode_analytics/batch/__init__.py, databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_charts_batch_extractor.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/batch/__init__.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_charts_batch_extractor.py
1. Update test for the extractor for better coverage
2. Given almost all of the Mode dashboard extractors are moving to use Mode discovery api, this PR moves the location of ModeDashboardChartsBatchExtractor to the directory where other Mode Dashboard extractors live. 
Updated ModeDashboardChartsBatchExtractor test for better coverage
Update ModeDashboardChartsBatchExtractor in README. Only bearer token is needed for the extractor.
=> test: refactor: update test and directory of ModeDashboardChartsBatchExtractor

databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_usage_extractor.py
Temporarily fix potential 404 in ModeDashboardUsageExtractor Reached an agreement with Mode team that they will include view_counts in reports discovery api. Once Mode team finishes it, we can switch to reports discovery api in this extractor
=> fix: Temporarily fix potential 404 in ModeDashboardUsageExtractor

.github/workflows/deploy_docs.yml, docs/common, docs/databuilder, docs/frontend, docs/metadata, docs/search
=> chore: fix gh page build workflow

.mailmap
Each user could have multiple emails with the commit (https://blog.developer.atlassian.com/aliasing-authors-in-git/). Create mailmap file to associate multiple email to same user.
=> chore: add mailmap to associate the right user

databuilder/README.md, databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_extractor.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_extractor.py
Update ModeDashboardExtractor to use Mode discovery api. Test added.
unit test for ModeDashboardExtractor 
ModeDashboardExtractor config example in README
=> Update ModeDashboardExtractor to Mode discovery api

databuilder/setup.py
Bump up databuilder version. ModeDashboard extractors have been moved to use Mode discovery api for better performance, except:
1. ModeDashboardExecutionExtractor because last run timestamp is not provided in [Mode discovery api](https://mode.com/developer/discovery-api/analytics/reports/) https://github.com/amundsen-io/amundsen/blob/0988547cd4e551488001f8327dd5db67198d9060/databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_executions_extractor.py#L22
2. ModeDashboardUsageExtractor because there is a potential problem in Mode report_stats discovery api. I saw a report_report token and its stats returned in report_stats discovery api, however, I was not able to find that report's corresponding metadata entry from reports discovery api response. …
=> other: bump up databuilder version

.github/CODEOWNERS
Since we both are working on multiple packages of Amundsen, and are contributing to those packages, I've added both Dorian and myself as the code owners. 
=> Make Verdan and Dorian the code owners for common, databuilder and frontend packages

.github/workflows/deploy_release.yml
The docs aren't crystal clear here, but the earlier attempt didn't work, so I think this is right
=> ci: fix var substitution name

databuilder/README.md, databuilder/databuilder/extractor/atlas_search_data_extractor.py, databuilder/example/scripts/sample_atlas_search_extractor.py, search/docs/atlas-search.md
Extends atlas search extractor in databuidler to pull data for dashboards.
n/a
- Added extractor to README.md 
- Updated search documentation with most recent comments on approach for search with Atlas
=> Atlas Dashboards Search Extractor

databuilder/CHANGELOG.md
Signed-off-by: Dorian Johnson 2020@dorianj.net
=> chore: update CHANGELOG for release 4.4.0

common/amundsen_common/models/user.py, common/tests/unit/models/test_user.py
Signed-off-by: benrifkind <ben.rifkind@gmail.com>
This updates the `UserSchema` to ignore the extra fields. I am doing this because I am getting extra fields from the get_auth_user method (https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/oidc_config.py#L25) and this causes an error like:
```
{'exp': ['Unknown field.'], 'sub': ['Unknown field.'], 'at_hash': ['Unknown field.'], 'iss': ['Unknown field.'], 'amr': ['Unknown field.'], 'idp': ['Unknown field.'], 'auth_time': ['Unknown field.'], 'jti': ['Unknown field.'], 'ver': ['Unknown field.'], 'aud': ['Unknown field.'], 'iat': ['Unknown field.']}
2021-05-03T16:34:17+0000.056 [ERROR] v0.current_user:48 (11:MainThread) - Encountered exception: 'dict' object has no attribute 'user_id'
```
I believe this is because …
=> fix:Ignore extra user fields

frontend/tests/unit/api/mail/test_v0.py
This fixes the frontend test case error we've been seeing in the PRs for some time. 
few recent ones are: 
- https://github.com/amundsen-io/amundsen/pull/1091
- https://github.com/amundsen-io/amundsen/pull/1085
- https://github.com/amundsen-io/amundsen/pull/1084
- https://github.com/amundsen-io/amundsen/pull/1073
=> Use the app context in failing test case

.github/boring-cyborg.yml, databuilder/README.md, databuilder/databuilder/extractor/atlas_search_data_extractor.py, databuilder/example/scripts/sample_atlas_search_extractor.py, docker-amundsen-atlas.yml, metadata/docs/proxy/atlas/popular_tables.md, metadata/docs/proxy/atlas_proxy.md, metadata/metadata_service/proxy/atlas_proxy.py, metadata/tests/unit/proxy/fixtures/atlas_test_data.py, metadata/tests/unit/proxy/test_atlas_proxy.py, search/docs/atlas-search.md
Introduces support for Dashboards in AtlasProxy.
- tests for get_dashboard
- docs for atlas search data extractor
=> Atlas Dashboard Support

metadata/metadata_service/proxy/atlas_proxy.py
=> Fix: dashboard in atlas metadata proxy

.github/workflows/search_pull_request.yml
Signed-off-by: Grant Seward <grant@stemma.ai>
Search PR workflow previously used metadata directory, updated to use search
This should run the appropriate tests
n/a
=> fix: Update search PR workflow to use search directory

databuilder/README.md, databuilder/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_executions_extractor.py, databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_executions_extractor.py
Move ModeDashboardExecutionsExtractor to Mode discovery endpoint
added tests for ModeDashboardExecutionsExtractor
Update ModeDashboardExecutionsExtractor config in README
=> perf: Update mode dashboard executions extractor to discovery api

databuilder/databuilder/extractor/dbt_extractor.py
- It is possible for someone to (probably accidentally) have columns in the manifest.json, but not in the catalog.json. This prevents the databuilder extractor from failing on those.
- Also fixes some typos.
=> fix: dbt extractor - handle columns in manifest and not in catalog

.github/boring-cyborg.yml
Given that this doesn't actually check if people filled out the issue template, I think it's a bit unfriendly. I also don't think it will change behavior for people who don't follow the template
Signed-off-by: Dorian Johnson <2020@dorianj.net>
=> chore: make it a bit friendlier

docs/installation.md
docs: update databuilder directory name after deprecating databuilder submodule
No tests - just docs change
The installation manual required an update following the deprecation of https://github.com/amundsen-io/amundsendatabuilder repository
=> Updates the databuilder directory name after deprecating databuilder submodule

databuilder/setup.py
Bump up databuilder version to 4.4.1
=> chore: bump up databuilder version to 4.4.1

search/search_service/api/swagger_doc/table/search_table_filter.yml
The swagger file of search_table API did not show the request body in the UI because of which API was inaccessible. In this MR, the swagger file's indentation is fixed and an unwanted property from the request body has been removed.
No test case required as it's just a bug fix.
N/A
=> fix: search_table API swagger file bug fix

metadata/metadata_service/proxy/atlas_proxy.py
=> fix:  atlas proxy fix

search/search_service/proxy/elasticsearch.py, search/setup.cfg
Extends dashboard basic search with `chart_names` available in `DashboardESDocument`
n/a
n/a
=> feat: use chart_names in dashboard basic search

search/search_service/models/user.py
Remove a comment in the Search Service user model get_id function that contradicts the implementation details.
=> fix: remove a comment in the Search Service user model get_id function that conflicts with implementation

README.md
=> docs: Fix installation link

search/search_service/config.py
Fixes issue caused by https://github.com/amundsen-io/amundsen/pull/1141 (search proxy doesn't work unless aws config is used and properly configured)
n/a
n/a
=> fix: aws config

databuilder/databuilder/extractor/atlas_search_data_extractor.py
=> fix: add optional list to atlas_search_extractor

common/setup.py
=> feat: bump up amundsen-common to 0.13.0

databuilder/requirements.txt
=> fix: add amundsen-common requirement for databuilder

metadata/docs/proxy/mysql.md, metadata/metadata_service/__init__.py, metadata/metadata_service/cli/__init__.py, metadata/metadata_service/cli/rds_command.py, metadata/metadata_service/client/__init__.py, metadata/metadata_service/client/rds_client.py, metadata/metadata_service/config.py, metadata/metadata_service/proxy/mysql_proxy.py, metadata/requirements.txt, metadata/tests/unit/cli/__init__.py, metadata/tests/unit/cli/test_rds_command.py, metadata/tests/unit/proxy/test_mysql_proxy.py
Implementation of [RFC-mysql_support_in_metadata_service](https://github.com/amundsen-io/rfcs/blob/master/rfcs/000-mysql-support-in-metadata-service.md)
* Added mysql_proxy 
* A new config block for mysql use
* A new proxy: mysql_proxy.py
* Added cli support for rds schema migration 
* A new cli script: rds_command.py
* Cli registration in init.py of metadata service
- Unit tests for mysql_proxy
- Unit tests for rds_commands
A doc added for how the mysql_proxy works basically and the introduction to schema migration cli.
- All the public functions and …
=> feat: support mysql in metadata service

metadata/metadata_service/proxy/atlas_proxy.py, metadata/requirements.txt, metadata/tests/unit/proxy/fixtures/atlas_test_data.py, metadata/tests/unit/proxy/test_atlas_proxy.py
This PR increases test coverage for atlas proxy and fixes owner deletion bug.
Accessing `next` value of `active_owner` iterator after calling `list` function on it will always result in `StopIteration` exception.
Updated atlas proxy tests for better coverage.
=> test: Increase test coverage for atlas proxy

docs/installation.md
the section anchor for troubleshoot section is broken, I added the correct anchor.
No test
Troubleshoot section anchor
=> docs: Fix broken anchor link in readme

.github/workflows/metadata_pull_request.yml, metadata/requirements.txt, metadata/setup.py
Put additional proxy requirement into setup.py extra section.
Some contexts: https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1622780101143900, no RC of the issue yet
=> chore: update requirement file in metadata

metadata/README.md
docs: add AWS Neptune to metadata*s Readme
=> Docs: add AWS Neptune to metadata*s Readme

README.md, databuilder/README.md, databuilder/databuilder/extractor/generic_usage_extractor.py, databuilder/example/scripts/sample_snowflake_table_usage.scala, databuilder/tests/unit/extractor/test_generic_usage_extractor.py
Signed-off-by: Allison Doami <adoami@chanzuckerberg.com>
(replica of https://github.com/amundsen-io/amundsen/pull/1192 after merging fixes)
Implemented a Generic Usage Extractor which utilizes the TableColumnUsage to fill in the popular tables and frequent users feature. CZI uses Snowflake very heavily and because Snowflake does not have table usage built in like BigQuery, I've created a custom sql parser script in Scala that I run in Databricks from an Airflow DAG. The way I calculate popularity is by reading the query logs, parsing what tables are being used within the query, insert a row into the Snowflake popularity table with a unique user, and add one to its score.
I would love help to write tests for this! I have this deployed in 5 different Airflow deployments right now and it …
=> feat: Generic Usage Extractor with Scala custom sql script for Snowflake

.github/CODEOWNERS
Signed-off-by: Dorian Johnson <2020@dorianj.net>
=> chore: add myself as codeowner for other services

databuilder/databuilder/extractor/base_bigquery_extractor.py, databuilder/databuilder/extractor/bigquery_metadata_extractor.py, databuilder/databuilder/extractor/bigquery_usage_extractor.py, databuilder/databuilder/extractor/bigquery_watermark_extractor.py
It is related to [issue 1200](https://github.com/amundsen-io/amundsen/issues/1200) 
Date format validation added for table suffix
=> fix: update sharded_table filter in BigQuery extractor

databuilder/databuilder/extractor/bigquery_watermark_extractor.py, databuilder/setup.py
=> fix: Add forgotten init file to databuilder/models/feature module

databuilder/example/scripts/sample_data_loader_neptune.py
fix sample_data_loader_neptune.py AttributeError: 'NeptuneSearchDataExtractor' object has no attribute 'neptune_client'
=> fix: bug #1213 relates to AWS creds Neptune

databuilder/README.md
Forgot to update the README after the snowflake to generic usage change!
=> fix: Update README to GenericUsageExtractor

databuilder/requirements.txt, databuilder/setup.py
moves amundsen-rds back to requirements.txt 
n/a
n/a
=> fix: rds databuilder dependencies

databuilder/databuilder/models/feature/feature_generation_code.py, databuilder/databuilder/models/feature/feature_metadata.py, databuilder/setup.py, databuilder/tests/unit/models/feature/test_feature_generation_code.py, databuilder/tests/unit/models/feature/test_feature_metadata.py, databuilder/tests/unit/models/feature/test_feature_watermark.py
Update `Feature` and `Feature_Group` keys to reduce repetition. Add `source` attr to `Feature_Generation_Code`. 
tests for above models were modified.
=> feat: update feature models

databuilder/README.md
Updated links in databuilder docs after migrating to monorepo.
n/a
databuilder README.md
=> fix: Databuilder docs

databuilder/README.md
Signed-off-by: Allison Doami <adoami@chanzuckerberg.com>
Related to this thread on Slack: https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1623448529187300
=> fix: Update databuider README GenericUsageExtractor config

Dockerfile.frontend.public
Fix failing build of public frontend docker image due to missing requirements-common.txt
n/a
n/a
- [x In case of new functionality, my PR adds documentation that describes how to use it.
=> fix: failing build for public frontend docker image

amundsen-kube-helm/templates/helm/values.yaml, search/CHANGELOG.md, search/setup.py
=> chore: bump search version 2.5.1 -> 2.6.0

.github/CODEOWNERS, OWNERS.md
=> docs: update the owner file

search/search_service/proxy/elasticsearch.py
Minor non-breaking refactor making it easier to use ElasticsearchProxy with custom queries.
n/a
n/a
=> feat: refactor ElasticsearchProxy queries

docs/authentication/oidc.md, frontend/amundsen_application/__init__.py, frontend/amundsen_application/oidc_config.py, frontend/setup.py, metadata/setup.py, search/setup.py
This is a breaking change for anyone using Amundsen with OIDC. I have released a new version of `flaskoidc` which works with the Discovery endpoints. That means we don't need to take care of clients_secrets.json files anymore. 
People will still be able to use the `flaskoidc==0.2.3` as is, with the clients_secrets.json file if they want. 
From `1.0.0` I've dropped the changed the underlying package, and moved away from `flask-oidc` in favor of `authlib`. 
Configuration is documented here: https://github.com/verdan/flaskoidc#readme
There will be a blog post on what's new in `flaskoidc` soon. 
The new config will look something like this:
Updated the documentation to mention both the old and new versions and how to configure both. 
Make sure …
=> !refactor: Updates Amundsen to use new version of FlaskOIDC

frontend/amundsen_application/__init__.py
This PR makes sure we use the new environment variables for the class module and class wrapper. 
=> fix: Makes sure to use the new env variables

common/amundsen_common/models/index_map.py, common/setup.py
New ES index mapping for features to support ongoing feature work.
Tested manually by calling `elasticsearch.indices.create` with this mapping and then reading back the mapping.
none
=> feat: add ml feature ES index mapping

common/amundsen_common/models/index_map.py, common/setup.py
Forgot to include key in https://github.com/amundsen-io/amundsen/pull/1257. 
none
=> fix: add key to ES feature index

.github/workflows/deploy_docs.yml, databuilder/requirements.txt, mkdocs.yml, requirements-common.txt, requirements.txt
We are using the master branch of the GitHub action responsible for the docs deployment. 
The latest version of that action breaks the document's build. This PR tries to check if changing the version actually
fixes the build. 
=> fix: Fixes the Amundsen Builds

common/setup.py
=> chore: bumped version of common to 0.15.3

common/setup.py, frontend/setup.py, metadata/setup.py, requirements-common.txt, search/setup.py
The current setup introduces hard pins for `amundsen-common` and the hard pins may also be inconvenient for custom setups of the amundsen microservices. We are attempting to roll forward with this removal 
After discussing with @szczeles and @feng-tao, we've decided to try removing hard pins completely and see what kind of trouble we run into. 
I've also deleted some dependencies which appear to no longer be used. 
Rebuilt containers (following https://github.com/amundsen-io/amundsen/blob/master/docs/developer_guide.md#building-local-changes) and ran the quick start guide with sample data. Don't see any issues so far! 
- In case you are adding a dependency, …
=> refactor: remove hard pins in requirements-common.txt

databuilder/requirements.txt, databuilder/setup.py
bumps common in databuilder with the version from [The Great Unpinning ](https://github.com/amundsen-io/amundsen/pull/1264)
=> chore: bump common in databuilder

.github/titleLint.yml, README.md
Remove all the sub repos commit badges given it is now mono-repo. Fix the pypi version badges.
=> docs: update readme to fix the badges

frontend/amundsen_application/api/utils/search_utils.py
=> fix: filter names mismatch

frontend/amundsen_application/static/css/_layouts.scss
Closes: https://github.com/amundsen-io/amundsen/issues/1255
Scope of this PR to make consecutive PR in table description visually distinguishable. Originally, in the table description the `margin` CSS attribute was set to `0`. My assumption is this was done to make the table description be more compact given the relatively limited space that table descriptions can occupy. But w.r.t. to https://github.com/amundsen-io/amundsen/issues/1255 I think this causes more harm than good and hence the suggestion of this PR is to essentially revert the change and fallback to default `margin`. 
**Before:**
**After:**
No tests should be affected as it's a style change.
N/A
- In case you are adding a dependency, check if the …
=> style: Make consecutive paragraph visually distinguishable

common/setup.py
=> chore: bumped common to 0.18.0

frontend/amundsen_application/static/js/pages/FeaturePage/GenerationCode/index.tsx, frontend/amundsen_application/static/js/pages/FeaturePage/index.tsx
- show feature group on feature page title
- use configured name for features on subtitle
- handle empty string on generation code
=> fix: Minor cleanup for Features

docs/installation.md
Update documentation as per current example
NA as doc only changes
https://www.amundsen.io/amundsen/installation/#verify-setup
Documentation was out od date
=> docs: Update Verifying setup as per latest example

common/amundsen_common/models/index_map.py
This matches what we do for tables and dashboards.
=> fix: use simple analyzer for Feature ES index

common/setup.py
Signed-off-by: Dmitriy Kunitskiy <dkunitskiy@lyft.com><!---
forgot to bump it in https://github.com/amundsen-io/amundsen/pull/1300
=> chore: bump common

databuilder/setup.py
Bump databuilder version for release
=> chore: Bumped version to 5.2.2

databuilder/databuilder/extractor/atlas_search_data_extractor.py
=> fix: change atlas search extractor table key format from qualifiedName to uri

metadata/metadata_service/proxy/gremlin_proxy.py
```NeptuneGremlinProxy``` inherits ```AbstractGremlinProxy``` class which doesn't contain ```get_popular_resources()``` function. Hence the following error is produced:
```
File "/app/metadata_service/proxy/__init__.py", line 47, in get_proxy_client
client_kwargs=client_kwargs)
TypeError: Can't instantiate abstract class NeptuneGremlinProxy with abstract methods get_popular_resources
```
=> Fix: Remove inheritance error due to missing function in NeptuneGremlinProxy

frontend/amundsen_application/static/js/components/ResourceList/ResourceListHeader/index.spec.tsx, frontend/amundsen_application/static/js/components/ResourceList/ResourceListHeader/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem/index.tsx
* Removed the `resource-header` constant CSS element rendering for each
header span in the ResourceListHeader component..
* Refactored the test to use `resource-text` as a finder for header text
elements
* Updated the source columns entries to use `resource-source` in
addition to `resource-type`
These changes address a bug in the rendering of the resource list for tables 
The current main branch looks like this 
These changes correct the table page to this:
Co-authored-by: Ozan Dogrultan <ozan.dogrultan@deliveryhero.com>
* Refactored the tests to use `resource-text` as a finder for header text
elements …
=> Fix: ResourceList and ResourceListItem UI elements CSS

frontend/Makefile
Docker build is failing because of the wrong path in the make file. 
ref: https://github.com/amundsen-io/amundsen/runs/2908569910?check_suite_focus=true#step:4:1375
=> fix: Fixes the docker push build

databuilder/databuilder/extractor/atlas_search_data_extractor.py, databuilder/databuilder/extractor/dashboard/apache_superset/apache_superset_chart_extractor.py, databuilder/databuilder/extractor/dashboard/apache_superset/apache_superset_metadata_extractor.py, databuilder/databuilder/extractor/dbt_extractor.py, databuilder/databuilder/extractor/hive_table_last_updated_extractor.py, databuilder/databuilder/models/atlas_serializable.py, databuilder/databuilder/models/schema/schema.py, databuilder/databuilder/publisher/atlas_csv_publisher.py, databuilder/databuilder/publisher/elasticsearch_publisher.py, databuilder/databuilder/publisher/neo4j_csv_publisher.py, databuilder/databuilder/task/task.py, databuilder/example/scripts/sample_dbt_loader.py, databuilder/example/scripts/sample_deltalake_metadata.py, databuilder/example/scripts/sample_feast_loader.py, databuilder/example/scripts/sample_pandas_profiling_column_stats_loader.py, databuilder/setup.cfg, databuilder/tests/unit/extractor/test_csv_extractor.py, databuilder/tests/unit/extractor/test_kafka_source_extractor.py, databuilder/tests/unit/publisher/test_mysql_csv_publisher.py, databuilder/tests/unit/publisher/test_neo4j_csv_publisher.py
addressing issue https://github.com/amundsen-io/amundsen/issues/1212  -- fixing flake8 E117,E252,E741,F541,F841,W605 . 
Note: this keeps ignoring [W504](https://www.flake8rules.com/rules/W504.html), since looks like we are following [W503](https://www.flake8rules.com/rules/W503.html) . We can switch to ignore W503 if needed, but kept it as is for now.
N/A
N/A
=> style: fix flake8 databuilder lints

frontend/amundsen_application/api/search/v0.py
Initialize response for search api handlers.
Exceptions in the action logger for the handler helper methods bubble to the handler and produce a non json 500 for xhr requests:
```
File "/usr/local/amundsen/frontend/amundsen_application/api/search/v0.py", line 61, in search_table
return make_response(jsonify(results_dict), HTTPStatus.INTERNAL_SERVER_ERROR)
UnboundLocalError: local variable 'results_dict' referenced before assignment
```
N/A
N/A
=> fix: Handle action logger exceptions in search handlers

metadata/metadata_service/proxy/neo4j_proxy.py, metadata/tests/unit/proxy/test_neo4j_proxy.py
=> fix: Standardize the user serialization

databuilder/example/scripts/sample_neptune_data_cleanup_job.py
fix aws session token that is required for neptune to be called
=> fix: aws session token that is required for neptune to be called

frontend/docs/installation.md
from `frontend/docs/installation.md` we are pointing to the - now deprecated - amundsenfrontendlibrary repository. updating the documentation paths to follow the new monorepo `amundsen-io/amundsen/..` structure.
N/A
```diff
- $ git clone https://github.com/lyft/amundsenfrontendlibrary.git
- $ cd amundsenfrontendlibrary/amundsen_application/static
+$ git clone https://github.com/amundsen-io/amundsen.git
+$ cd amundsen/frontend/amundsen_application/static
```
=> docs: update frontend installation doc paths

search/search_service/config.py, search/setup.cfg
When trying to set up the AWS Elasticsearch Config for the search service, if you don't have all the nessescary configuration values populated (host, region, credentials) the service will still set up properly but the client will be None. This commit changes the flow AwsSearchConfig to fail if all the values aren't populated which will result in the service not starting up and throwing this error properly that is a lot easier to debug. Without this, it is a bit of a rabbit chase to figure out why you can't connect to AWS ES.
When trying to set up the AWS Elasticsearch Config for the search service, if you don't have all the nessescary configuration values populated (host, region, credentials) the service will still set up properly but the client will be None. This commit changes the flow …
=> feat: search_service/config: fail on bad AWS ES config

frontend/amundsen_application/static/js/config/index.spec.ts
Parametrize test cases to allow for notices test cases on dashboards/tables and different combinations of wildcards easily.
Modified notices test cases to be more readable.
=> style: parametrizing notices test cases

NOTICE
Disclaimer: Not a lawyer  :) change the notice file following https://github.com/envoyproxy/envoy/blob/main/NOTICE as an example
=> docs: update Notice file

metadata/metadata_service/proxy/atlas_proxy.py
Adjusts AtlasProxy lineage rendering after changes to UI
n/a
n/a
=> fix: Atlas lineage multiple parents

README.md
=> docs: update readme with contributor graph

metadata/setup.py
setup.py bump for metadata
n/a
n/a
=> chore: Release metadata 3.8.0

search/search_service/config.py, search/setup.cfg
This reverts commit 35cada7ab3ef8e86a84b7414f6bf1e3384428b94.
=> chore: Revert "feat search_service/config: fail on bad AWS ES config (#1305)"

metadata/metadata_service/proxy/gremlin_proxy.py
`gremlinpython==3.4.9` has default timeout set to 0.3 seconds, which causes WebSockets to timeout without completing the requests. Fix has been taken from the below references.
Reference: https://groups.google.com/g/gremlin-users/c/K0EVG3T-UrM/m/51bfkOZOCgAJ
https://github.com/apache/tinkerpop/commit/3f93fdc72f71a3191a88cc6e54a57b701b21e6b3
This is likely fixed in `gremlinpython==3.5.0` but since we are using `3.4.9` this fix is required. We can't use `gremlinpython==3.5.0` for now. Please refer: https://github.com/amundsen-io/amundsengremlin/pull/16
- …
=> fix: timeout for tornado

databuilder/databuilder/extractor/feast_extractor.py, databuilder/example/scripts/sample_feast_loader.py, databuilder/tests/unit/extractor/test_feast_extractor.py
Fixes #930, adding the Feast Serving URL to Feast Extractor
Feast extractor tests modified including Feast Serving URL
Examples script changed adding Feast Serving URL
=> fix: Add Feast Serving URL to Feast Extractor

databuilder/databuilder/task/task.py
Enhancement: add logging for total extracted records
=> feat: Enhancement: add logging for total extracted records

README.md
Updates Table Connectors in README.md with Elasticsearch.
n/a
- main README.md
=> chore: Update README.md with ES Table connector

Dockerfile.frontend.public, Dockerfile.metadata.public, metadata/Makefile, metadata/setup.py
Fixes reference to old Dockerfile for metadata oidc image build step.
m/a
n/a
=> fix: metadata oidc image build

databuilder/setup.py
Signed-off-by: Grant Seward <grant@stemma.ai>
=> chore: Bumped version

README.md
the link expired, recreate a new link
=> chore: update slack link

.github/CODEOWNERS
=> chore: Added  @sewardgw to *.py codeowner

frontend/amundsen_application/static/package-lock.json, frontend/amundsen_application/static/package.json
Signed-off-by: Marwan Baghdad <marwan.nabil@deliveryhero.com>
Adding google tag manager plugin 
=> feat: Added support for Google tag manager

docs/developer_guide.md, docs/roadmap.md, docs/tutorials/badges.md, docs/tutorials/data-preview-with-superset.md, docs/tutorials/how-to-use-amundsen-with-aws-neptune.md
Change links that used to point to `master` to `main` and update them to use the mono repo directory structure.
N/A
Updated links, no other changes made.
- [na] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [na] In case of new functionality, my PR adds documentation that describes how to use it.
=> docs: Fix links to point to correct branch and mono-repo

amundsen-kube-helm/templates/helm/templates/deployment-metadata.yaml
Replicas is referenced in the valuesfile for metadata but never used in the deployment template.  This change renders the replicas into the deployment yaml (defaults to 1).
Tested on an internal k8s cluster.
NA
- [NA] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [NA] In case of new functionality, my PR adds documentation that describes how to use it.
=> fix: Add replicas to metadata template

common/setup.py, databuilder/setup.py, metadata/setup.py
Bumps versions for services affected by Amundsen Atlas Databuilder feature.
n/a
n/a
=> chore: Update versions for Amundsen Atlas Databuilder release

databuilder/setup.py
Signed-off-by: MrwanBaghdad <marwan.nabil@deliveryhero.com>
Bump databuilder version 
=> Chore: Bump databuilder version to 6.0.1

frontend/docs/application_config.md
documentation for better notices wildcards
Updated documentation to align with changes from past pr (https://github.com/amundsen-io/amundsen/pull/1408)
=> docs: adding docs for notices generalization

databuilder/databuilder/models/atlas_serializable.py
Fixes https://github.com/amundsen-io/amundsen/issues/1428
fix: unpacking AtlasEntity named tuple in the wrong order causing incorrect error message
=> fix: unpacking AtlasEntity named tuple in the wrong order

databuilder/databuilder/extractor/dashboard/apache_superset/apache_superset_chart_extractor.py, databuilder/databuilder/extractor/dashboard/apache_superset/apache_superset_extractor.py, databuilder/databuilder/extractor/dashboard/apache_superset/apache_superset_metadata_extractor.py, databuilder/databuilder/extractor/dashboard/apache_superset/apache_superset_table_extractor.py, databuilder/setup.py, databuilder/tests/unit/extractor/dashboard/apache_superset/test_apache_superset_chart_extractor.py, databuilder/tests/unit/extractor/dashboard/apache_superset/test_apache_superset_metadata_extractor.py, databuilder/tests/unit/extractor/dashboard/apache_superset/test_apache_superset_table_extractor.py
Fixes & unifies approach for pagination of results in Apache Superset extractors.
n/a
n/a
=> fix: Apache Superset extractors pagination

docker-amundsen.yml
=> chore: Updates the package versions

databuilder/docs/models.md
The TableColumnUsage model lacked some documentation on minimum requirements and sent me on a bit of a wild goose chase. This commit adds the min requirements to the docs so folks don't fall down this rabbit hole as well.
N/A
See Summary section
=> docs: add minimum usage to docs

databuilder/example/sample_data/sample_application.csv
Fixes sample data loader after refactoring application model (removes unused exec_date field).
n/a
n/a
=> fix: Sample data (application)

.github/CODEOWNERS
Add youngyjd to CODEOWNERS of all subdirectories for the sake of PR reviewing.
=> docs: Add youngyjd to codeowners

frontend/amundsen_application/api/quality/__init__.py
=> chore: fix license CI for new file

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
Signed-off-by: Daniel Won <dwon@lyft.com>
=> fix: Reset tabs after loading a new table page

README.md
=> docs: add a blog from convoy

databuilder/README.md, databuilder/databuilder/transformer/base_transformer.py
* fixes grammatical mistakes and some unclear expressions 
* update outdated URLs
* fixed outdated Github links to new URLs in the Databuilder document.
- `https://github.com/amundsen-io/amundsendatabuilder` -> `https://github.com/amundsen-io/amundsen`
=> docs: Improve the documentation of Databuilder

frontend/setup.py, metadata/setup.py, search/setup.py
Signed-off-by: mgorsk1 <gorskimariusz13@gmail.com>
=> chore: bump flaskoidc deps

databuilder/setup.py
Signed-off-by: MrwanBaghdad <marwan.nabil@deliveryhero.com>
Bump minor version of databuilder
=> chore: Bump databuilder version to 6.1.0

databuilder/databuilder/extractor/dashboard/apache_superset/apache_superset_chart_extractor.py, databuilder/setup.py
Fixed Apache Superser chart extractor _get_dashboard_details function
=> fix: Apache Superset Chart extractor

.github/CODEOWNERS, databuilder/setup.py
=> chore: bumped databuilder to 6.2.0 + @dkunitsk added as code owner

requirements-common.txt
=> chore: bumped amundsen common to 0.20.0

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/features/ColumnList/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/testDataBuilder.ts
Fixes an issue where the column index is using the wrong value, since we flattened and added columns to the original array. 
=> Fix: Column description index incorrect

frontend/amundsen_application/api/log/v0.py, frontend/amundsen_application/static/js/ducks/log/api/v0.ts
=> fix: missed field on API

frontend/amundsen_application/static/js/components/Badges/BadgeBrowseList/styles.scss
Adds padding for badges when the list spans more than one line.
n/a
n/a
=> fix: browse badges paddding

README.md
=> docs: add a blog from aws

requirements-common.txt
=> chore: bump amundsen common to 0.23.0

search/search_service/api/search.py
=> fix: response schema issue in new search API

search/search_service/config.py
=> fix: add es v2 client config

search/search_service/proxy/es_search_proxy.py
=> fix: added page size argument for compatibility

frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/api/helpers.spec.ts, frontend/amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, frontend/amundsen_application/static/js/features/ColumnList/index.tsx
Add a config for enabling nested columns and a max column count for when to disable nested columns
=> feat: Add config for nested columns feature

frontend/amundsen_application/static/js/features/ColumnList/ColumnType/parser.spec.ts, frontend/amundsen_application/static/js/features/ColumnList/ColumnType/parser.ts
- Nested level were incorrectly incremented due to a recursive scope variable
being altered between calls.
- Also cleaned up some duplicate code.
Signed-off-by: Daniel Won <dwon@lyft.com>
=> Fix: nested columns bug

docs/installation-aws-ecs/docker-ecs-amundsen.yml
When trying out the provided ECS deployment, the different containers fail to communicate with eachother
(https://github.com/aws/amazon-ecs-cli/issues/662). I applied the workaround mentioned in that thread, linking the containers that should communicate with eachother. I also removed the unsupported `depends_on` and `container_name` attributes, to avoid confusion.
Closes #257
This functionality is currently not tested
This change is consistent with current documentation (https://www.amundsen.io/amundsen/installation-aws-ecs/aws-ecs-deployment)
- All the …
=> fix: use docker links for ecs deployment

common/amundsen_common/models/search.py, common/setup.py
- Added UpdateDocumentRequest to be used for requests made to search service /v2/document
=> feat: update es document request model

common/amundsen_common/models/search.py, common/setup.py
=> fix: updated UpdateDocumentRequest model to make value optional

search/search_service/proxy/es_search_proxy.py
=> fix: error on search with pagination

search/search_service/proxy/es_search_proxy.py, search/tests/unit/proxy/fixtures.py, search/tests/unit/proxy/test_es_search_proxy.py
- some fields missing that are needed for FE search results display
=> fix: added missing description fields to mappings

search/search_service/proxy/es_search_proxy.py
=> fix: add missing field for dashboard uri

frontend/amundsen_application/api/utils/search_utils.py, frontend/setup.py
=> fix: added uri and url fields to dashboard mapping function

search/search_service/proxy/es_search_proxy.py, search/tests/unit/proxy/fixtures.py
- This change provides the ability to overwrite the `must`, `should`, and `filter` portions of the boolean query used to query ES, makes it easier to implement customized search
=> feat: more flexible ES search proxy implementation

databuilder/databuilder/extractor/dashboard/apache_superset/apache_superset_table_extractor.py, databuilder/setup.py
Fixes redundant dict wrap messing with input dict.
n/a
n/a
=> fix: database mapping superset extract

databuilder/databuilder/extractor/hive_table_last_updated_extractor.py, databuilder/databuilder/extractor/hive_table_metadata_extractor.py, databuilder/setup.py
Refactor sql query references in hive extractor so it's easier to subclass this extractor and provide custom sql queries. 
n/a
n/a
=> feat: refactor hive extractor sql query refs

databuilder/databuilder/extractor/generic_usage_extractor.py, databuilder/setup.py
Refactors generic usage extractor for easier subclassing
n/a
n/a
=> feat: refactor generic usage extractor

metadata/metadata_service/proxy/neo4j_proxy.py
implements resource reports client available in Atlas proxy to Neo4j proxy
n/a
n/a
=> feat: introduce resource reports client in neo4j proxy

frontend/amundsen_application/api/search/v1.py, frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/components/Tags/TagInfo/index.tsx, frontend/amundsen_application/static/js/ducks/search/sagas.ts, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/FilterOperationSelector/index.tsx
Some small search related changes:
1. Fixing the logging for search actions
2. Clicking a tag from the homepage left features out of the search so added that in
N/A
N/A
=> chore: Log searches and add tag to filter for features when clicking from the homepage

docs/installation-aws-ecs/docker-ecs-amundsen.yml
Update service versions on docker-compose for AWS ECS deployment file.
We deployed "docker-ecs-amundsen.yml" file on AWS ECS service without issues.
=> fix: Update amundsen services versions on ECS installation

.github/workflows/common_pull_request.yml, .github/workflows/databuilder_pull_request.yml, .github/workflows/deploy_release.yml, .github/workflows/frontend_pull_request.yml, .github/workflows/metadata_pull_request.yml, .github/workflows/monthly_release.yml, .github/workflows/noop_pull_request.yml, .github/workflows/search_pull_request.yml, common/setup.py, databuilder/setup.py, frontend/setup.py, metadata/setup.py, search/setup.py
=> chore: remove py36 from github workflows

search/search_service/proxy/es_search_proxy.py
Minor refactor of new es proxy enabling easier fine-tuning of must fields.
n/a
n/a
=> feat: refactor must fields for new es proxy

databuilder/README.md, databuilder/databuilder/extractor/es_base_extractor.py, databuilder/databuilder/extractor/es_watermark_extractor.py, databuilder/databuilder/models/watermark.py, databuilder/tests/unit/extractor/test_es_watermark_extractor.py
Add `ElasticsearchWatermarkExtractor`.
I added a few unit tests for the newly added `ElasticsearchWatermarkExtractor`.
I added a new documentation section for `ElasticsearchWatermarkExtractor` just under `ElasticsearchColumnStatsExtractor` ( https://github.com/amundsen-io/amundsen/tree/main/databuilder#elasticsearchcolumnstatsextractor ).
=> feat: Add ElasticsearchWatermarkExtractor

metadata/metadata_service/api/user.py, metadata/tests/unit/api/test_user.py
This PR is to sort UserFollowsAPI response alphabetically so bookmarks displayed on the frontend are sorted the same way.
Updated tests to test the sort functionality.
=> feat: Sort UserFollowsAPI response alphabetically

frontend/amundsen_application/static/js/utils/index.spec.ts, frontend/amundsen_application/static/js/utils/stats.ts
regarding: https://github.com/amundsen-io/amundsen/issues/1686
`info.spec.ts` is extended with new case.
=> feat: new option added for column stats info text

README.md
This is a partial fix for https://github.com/amundsen-io/amundsen/issues/1683.
See "Path forward for additional broken links" below for next steps.
There are several broken links on the home page. The index.md from the /docs subdirectory is a symlink to the README.md which is displayed on github.com, and attempts to link to relative files. These do not work on the docs site, however, since the docs site has a /amundsen/ base path, and no .md extension.
Simple relative paths work both on github and the docs site, however, so I changed the first set of links to be relative.
For the links that attempt to go to a `./docs/somefile.md` relative file, I changed these to be absolute redirects to the docs website, since that interface is designed for browsing docs.
For links to files like …
=> docs: Fix broken links from docs home page

databuilder/databuilder/extractor/dbt_extractor.py, databuilder/tests/unit/extractor/test_dbt_extractor.py
**Fix for dbt example.**
**How is today:**
The [catalog.json](https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/sample_data/dbt/catalog.json) file has the column names in uppercase. The [manifest.json](https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/sample_data/dbt/manifest.json) file has the column names in lowercase.
To work, there is a line in the dbt_extractor.py file applying an upper and this resolves for the example json.
But when I used it, it didn't work, because my two json files were already in lowercase.
At first, removing the upper worked for me, but the example stopped working. So I looked for a solution to work in my case and also in the example.
**My suggestion to fix:**
Remove from the dbt_extractor.py file the upper applied to …
=> fix: Updating dbt extractor - to work on all json files

frontend/amundsen_application/static/js/components/EditableText/styles.scss
Before (We'd have to scroll horizontally to the right to see the rest of the text):
After (The text is visible fully without having to scroll horizontally):
=> fix: wrap table column description text

frontend/amundsen_application/static/css/_layouts.scss, frontend/amundsen_application/static/js/components/EditableText/styles.scss
Signed-off-by: Junda Yang <youngyjd@gmail.com>
As a followup of https://github.com/amundsen-io/amundsen/commit/d5b979e1fd04f2f447923652a5795db3e0673cb9 to wrap column description markdown, we found a bit more issues in our production.
**before this PR:**
1. Table description not wrapped correctly.
2. White spaces at the end of the page
gif demo:
**after this PR:**
gif:
css change. no test
css change. no documentation
=> fix: metadata-section and markdown-wrapper style

databuilder/databuilder/task/search/search_data_queries.py, databuilder/setup.py
=> fix: small error when using given queries

databuilder/databuilder/task/search/search_data_queries.py, databuilder/setup.py
=> fix: finalized cypher queries for new ES publishing task

search/search_service/proxy/es_search_proxy.py
cleans up some leftover print statements used for debugging
n/a
n/a
=> chore: cleanup print statements

databuilder/setup.py
Bumping databuilder version to release the changes to support nested columns: https://github.com/amundsen-io/amundsen/pull/1695
N/A
N/A
=> chore: Bump databuilder version for backend support for nested columns

metadata/metadata_service/proxy/neptune_proxy.py, metadata/tests/unit/proxy/roundtrip/roundtrip_janusgraph_proxy.py, metadata/tests/unit/proxy/roundtrip/roundtrip_neptune_proxy.py
as per https://lfscanning.org/reports/lfai/amundsen-2022-01-27-b4212469-d92f-463d-96ea-7d5050fae11a.html
Signed-off-by: Mark Grover <mark@apache.org>
Fixing typo in license headers
N/A
N/A
=> chore: Fixing license headers 

search/search_service/proxy/es_search_proxy.py
=> fix: moving method to get index to ES client

search/search_service/proxy/es_search_proxy.py
=> fix: array index out of bound in some cases

frontend/amundsen_application/api/search/v1.py, frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/ducks/search/filters/reducer.spec.ts, frontend/amundsen_application/static/js/ducks/search/filters/reducer.ts, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/index.tsx
Added the ability to configure a default value for filters. If this value is set the filter is on by default and applies to all searches unless reset by the user.
=> feat: configurable default filter values

databuilder/databuilder/task/search/search_data_queries.py, databuilder/setup.py
=> fix: dashboard query

frontend/amundsen_application/static/js/features/NavBar/index.spec.tsx, frontend/amundsen_application/static/js/features/NavBar/index.tsx, frontend/docs/application_config.md
This PR, as part of https://github.com/amundsen-io/rfcs/blob/master/rfcs/045-amundsen-tour-and-feature-walkthrough.md, finishes the implementation of the tour component.
Adds support for feature tours as well as page tours.
Added tests
Updated docs
=> feat: support for feature tours

frontend/amundsen_application/static/.npmrc
Adds registry in .npmrc file
This avoids confusions on users that have internal npm registry setups on their companies machines
=> chore: adds explicit npm registry on .npmrc

frontend/amundsen_application/static/js/components/Lineage/Graph/chart.ts, frontend/amundsen_application/static/js/components/Lineage/Graph/constants.ts
Introducing the same changes introduced [here](https://github.com/amundsen-io/amundsen/pull/1721) by [aorozco05](https://github.com/aorozco05)
No tests are affected by this change.
No documentation changes are needed.
=> fix: Add schema name to Lineage graph node labels

amundsen-kube-helm/templates/helm/templates/deployment-frontend.yaml
The kube deployment for frontend was using the resources for the metadata deployment.
No tests. Modified kube deploy.
=> fix: Use frontend resources for frontend deployment

databuilder/setup.py
Signed-off-by: Muhammad Mikaal S. Anwar <mikaalanwar@gmail.com>
Version bump for 'google-auth' package to fix gcp impersonation for bigquery. Previously there was an issue in this package that restricted impersonation functionality but Google fixed it with the recent update.
N/A
=> Fix: Version bump for 'google-auth' package to fix gcp impersonation for bigquery

frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/features/NavBar/index.tsx, frontend/docs/application_config.md
Fixes issue where the page tour couldn't be applied to nested URLs like the source detail table
Updated tests
Updated docs
=> fix: adds support for simple wildcards on page tour configuration paths

databuilder/databuilder/task/search/search_data_queries.py
- removed some unnecessary fields
- made fields which are used for filters lowercase to match FE input requirement
- fixed issue where columns where duplicated over and over because of how usage was calculate
=> fix: issue with neo4j query for ES data

databuilder/databuilder/task/search/search_data_queries.py, databuilder/setup.py
=> chore: bump databuilder to 6.7.5

requirements-common.txt
Upgrade `flask-cors` to address this CVE https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25032
=> chore: bump flask-cors to 3.0.10

common/amundsen_common/models/search.py, common/setup.py, requirements-common.txt
=> fix: added default value to optional field in search request

frontend/amundsen_application/api/utils/search_utils.py
=> fix: added highlight options to request

databuilder/databuilder/publisher/elasticsearch_publisher.py, databuilder/databuilder/task/search/document_mappings.py, databuilder/databuilder/task/search/search_metadata_to_elasticsearch_task.py, databuilder/requirements.txt, databuilder/setup.py
=> feat: add version meta field and term_vector to mappings

frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/ToggleFilter/index.spec.tsx, frontend/amundsen_application/static/js/pages/SearchPage/SearchFilter/ToggleFilter/index.tsx
=> fix: toggle filter should clear when off

frontend/amundsen_application/static/js/components/Tour/index.tsx, frontend/amundsen_application/static/js/features/NavBar/index.tsx
Fixes issue with tour where we share state between multiple pages' tours
Manually
=> fix: fixes state sharing between tours of different pages

frontend/setup.py, search/setup.py
=> chore: bump release versions for search and frontend

search/search_service/proxy/es_proxy_v2.py, search/search_service/proxy/es_proxy_v2_1.py, search/tests/unit/proxy/test_es_proxy_utils.py
=> fix: typos in search proxy impl

frontend/amundsen_application/static/js/components/ResourceListItem/styles.scss
- added more spacing for matching columns and other metadata field matches
- Removed gray text
=> fix: Highlighting styling improvement

databuilder/databuilder/extractor/bigquery_metadata_extractor.py
While iterating over the tables in a BigQuery dataset, some temporary tables might be deleted. This causes 404 errors and this PR adds the logic to handle these errors gracefully.
N/A
N/A
=> fix: Handle BigQuery 404s gracefully

databuilder/setup.py
Bump databuilder to release new package with changes in #1913 
=> chore: Bump databuilder to 6.10.0

databuilder/setup.py
=> chore: bumped databuilder to 6.11.0

databuilder/databuilder/extractor/neo4j_extractor.py, databuilder/databuilder/publisher/neo4j_csv_publisher.py, databuilder/databuilder/task/neo4j_staleness_removal_task.py, databuilder/setup.py
Removed neo4j driver config since it can't be used with out config library
=> fix: driver object pickle error

frontend/amundsen_application/static/js/features/ColumnList/styles.scss
*Before:*
*After:*
No test changes are needed.
No documentation changes are needed.
=> fix: Fix column description overflow-y value

README.md
Adding Delivery Hero to "Who uses Amundsen?" of README
N/A
N/A
=> chore: Update 'Who uses Amundsen?'

databuilder/setup.py
Bump databuilder version to 7.3.0
N/A
N/A
=> chore: Bump databuilder version to 7.3.0

metadata/metadata_service/api/badge.py, metadata/metadata_service/proxy/neo4j_proxy.py
=> fix: more logging for badges

frontend/amundsen_application/static/js/pages/TableDetailPage/styles.scss
Fixes visual bug
Manually
Before:
After:
=> fix: fixes Collapse text button overlapping lineage tabs

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/pages/TableDetailPage/RequestMetadataForm/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/RequestMetadataForm/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableOwnerEditor/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableQualityChecks/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/WatermarkLabel/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx, frontend/amundsen_application/static/package-lock.json, frontend/amundsen_application/static/package.json
Fixes lineage showing cached content while loading new one
Fixes ESLint issues
Updates ESLint
Updated tests
=> fix: fixes cached lineage list content

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/.betterer.ts, frontend/amundsen_application/static/js/components/Tour/index.tsx, frontend/amundsen_application/static/js/features/Feedback/FeedbackForm/BugReportFeedbackForm/index.tsx, frontend/amundsen_application/static/js/features/Feedback/FeedbackForm/RatingFeedbackForm/index.spec.tsx, frontend/amundsen_application/static/js/features/Feedback/FeedbackForm/RatingFeedbackForm/index.tsx, frontend/amundsen_application/static/js/features/Feedback/FeedbackForm/RequestFeedbackForm/index.tsx, frontend/amundsen_application/static/js/features/Feedback/constants.ts, frontend/amundsen_application/static/js/features/Feedback/index.tsx, frontend/amundsen_application/static/js/features/Feedback/styles.scss, frontend/amundsen_application/static/js/features/NavBar/index.tsx, frontend/amundsen_application/static/js/utils/analytics.ts
Updates UI logging to get data on Tour and Feedback component usage
Manually
=> chore: updates logging to cover tour and feedback widget

metadata/metadata_service/proxy/mysql_proxy.py, metadata/setup.py
- supported amundsen-rds == 0.0.7 for mysql_proxy.py and support sqlalchemy >= 1.4, which is a change coming from amundsen-rds.
- removed redundant package dependency for rds in setup.py
=> chore: support amundsen-rds == 0.0.7 for mysql_proxy in metadata_service

frontend/amundsen_application/static/js/features/ColumnList/ColumnLineage/index.tsx
Fixes https://github.com/amundsen-io/amundsen/issues/2011
N/A
N/A
=> fix: Use isColumnLineagePageEnabled

common/amundsen_common/models/lineage.py, common/setup.py, requirements-common.txt
Added `upstream_count` and `downstream_count` to the `Lineage` model.
=> feat: Add lineage item counts to lineage response

databuilder/setup.py
Bump databuilder version to 7.4.3 to include the change mentioned in #2034.
=> Chore: Bump databuilder version to 7.4.3

README.md
add https://medium.com/@owenleung_89035/amundsen-installing-in-an-istio-enabled-environment-d0b9bdaeac49 and  https://medium.com/@owenleung_89035/amundsen-integrate-with-okta-singlesignon-20ad0a22d3d9 to the readme
=> doc: add two new docs to readme

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, README.md, docs/issue_labeling.md
Updates docs and templates
Labelling doc
=> docs: updates labeling doc with lowercase labels; updates templates, readme

docs/installation.md
This PR improves the Installation Guide for clarity and fixed some typos.
=> docs: Edit docs for clarity and fix typos

frontend/amundsen_application/static/js/components/Button/bootstrap-button.story.tsx, frontend/amundsen_application/static/js/components/Button/custom-button.story.tsx
Adds a set of stories to show the current possibilities when using buttons in AMS's UI
=> chore: adds storybooks for default Bootstrap and custom buttons

frontend/amundsen_application/static/js/config/config-utils.ts, frontend/amundsen_application/static/js/config/index.spec.ts, frontend/amundsen_application/static/js/features/NavBar/index.spec.tsx, frontend/amundsen_application/static/js/features/NavBar/index.tsx, frontend/amundsen_application/static/js/features/NavBar/styles.scss
Cleans up code and extract components on the global navigation of Amundsen
Updates text styles
Cleans ESLint issues and Type warnings
Updated tests
=> chore: cleans and refactors global navbar code

frontend/docs/strategy.md
Proposes a Frontend Strategy with milestones for the long term view of Amundsen's frontend
Created by the team at Lyft, this document includes:
- Current State
- Ideal Future State
- Roadmap by milestones
- Next steps prioritized
=> docs: Proposal for a new Frontend Strategy for Amundsen

frontend/amundsen_application/static/js/config/config-custom.ts, frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/config/config-types.ts, frontend/docs/application_config.md
Adds and updates some Frontend app configuration documents
Organizes configuration object alphabetically
=> docs: updates application configuration docs

.github/PULL_REQUEST_TEMPLATE.md, .github/prLint.json, .github/titleLint.yml, frontend/amundsen_application/static/js/index.tsx
Adds page view tracking via our log tracker method
Tested manually
=> chore: adds page view tracking via logAction

frontend/amundsen_application/static/js/ducks/feature/reducer.ts, frontend/amundsen_application/static/js/fixtures/globalState.ts, frontend/amundsen_application/static/js/fixtures/metadata/feature.ts, frontend/amundsen_application/static/js/interfaces/Feature.ts, frontend/amundsen_application/static/js/pages/FeaturePage/constants.ts, frontend/amundsen_application/static/js/pages/FeaturePage/index.tsx
- Added left, right, other, programmatic descriptions sections to the feature details page
- achieve parity with other resources
- ran locally
=> feat: add programmatic descriptions to feature details page

frontend/amundsen_application/static/js/config/config-types.ts, frontend/amundsen_application/static/js/config/config-utils.ts, frontend/docs/application_config.md
Updates our Application Configuration docs with the missing items
Completing our docs
=> docs: updates the missing application configuration docs

frontend/amundsen_application/static/.betterer.results, frontend/amundsen_application/static/js/features/Breadcrumb/index.spec.tsx, frontend/amundsen_application/static/js/features/Breadcrumb/index.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.spec.tsx, frontend/amundsen_application/static/js/features/ColumnList/ColumnDetailsPanel/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/ListSortingDropdown/index.spec.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/ListSortingDropdown/index.tsx
Logs table column sorting features
Logs table column info drawer features
Logs back to search button
Improved logging
Manually
=> chore: adds table detail logging

frontend/amundsen_application/static/css/_variables-default.scss, frontend/amundsen_application/static/js/components/OwnerEditor/index.tsx, frontend/amundsen_application/static/js/components/ResourceListItem/styles.scss, frontend/amundsen_application/static/js/features/NavBar/styles.scss, frontend/amundsen_application/static/js/utils/analytics.ts
Improves tracking on the user profile actions
Tweaks list alignment
Fixes ESLint issues
Improving observability
Manually
=> chore: improves user profile page tracking

frontend/amundsen_application/static/js/features/SearchBar/InlineSearchResults/ResultItemList/ResultItem/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/ReportTableIssue/index.tsx, frontend/amundsen_application/static/js/pages/TableDetailPage/TableIssues/index.tsx
Adds extra tracking on user interactions
Updates to use data-type on some links
Increase tracking coverage
Manually
=> fix: adds rest of mouse interaction tracking

GOVERNANCE.md
Removes time requirements for maintainers
Making the requirements more realistic
=> docs: Updated GOVERNANCE.md to remove time requirements

.github/CODEOWNERS
Updates Codeowners files with the newest maintainers
=> chore: updates codeowners with latests maintainers

databuilder/setup.py
Bump databuilder version to 7.4.5 to include the change in #2179
=> Chore: Bump databuilder version to 7.4.5

.github/CODEOWNERS, OWNERS.md
=> Move dorianj to Emeritus contributor

README.md
Deleted article of [Data Discovery Platform at Bagelcode](https://medium.com/bagelcode/data-discovery-platform-at-bagelcode-b58a622d17fd)
Deleted Bagelcode from user list of Amundsen
The article link doesn't work.
Bagelcode no more uses Amundsen from about 3 month ago
=> docs: Remove Bagelcode from README.md

search/setup.py
Chore: Bump amundsen-search version to 4.1.4
There has been two fixes published without bumping the package version
=> Chore: Bump amundsen-search version to 4.1.4

.github/workflows/license.yml
Updates Github Actions versions
Activate back some workflows
=> chore: update actions versions

OWNERS.md
Adding Alagappan as core maintainer of Amundsen
=> chore: Update OWNERS.md adding Alagappan

metadata/metadata_service/proxy/gremlin_proxy.py, metadata/setup.py
Corrected 3 typos in `_get_dashboard_tables` where "table" was misspelled. 
Tested internally on Neptune server.  This change does not affect function logic and the function's return value in any way. 
No documentation added.
=> amend typos in get_dashboard_tables

frontend/amundsen_application/static/css/_icons-default.scss, frontend/amundsen_application/static/images/icons/logo-powerbi.svg, frontend/amundsen_application/static/js/config/config-default.ts, frontend/amundsen_application/static/js/interfaces/Enums.ts
This addition of the powerbi feature will allow people to show the dashboard with powerbi logo instead of the default dashboard logo. Making the dashboard page more interactive.
=> feat: PowerBi Logo for Dashboard mode PowerBi

metadata/requirements.txt
Upgrading neo4j driver to latest 4.x.x version
https://pypi.org/project/neo4j/4.4.11/
Get the latest version that also has py3.10 support
Ran the tests and ran metadata service locally
=> chore: Upgrade neo4j driver to latest 4.x.x version

requirements-common.txt
Upgrade boto3 package to latest version
We were getting some error logs from this package with py3.10, so wanted to upgrade to the latest version to be more compatible
Ran tests and ran frontend service locally
=> chore: Upgrade boto3 to latest version

databuilder/setup.py
Follow up on PR https://github.com/amundsen-io/amundsen/pull/2254, bump the version to release the change.
=> fix: bump version

OWNERS.md
Marcos Stepping down as active maintainer
=> chore: moving Marcos to emeritus maintainer
